/**
 * Authored Mock Exam 3 expanded items — Domains B, C, F.
 * Independent study content only; not affiliated with the BACB.
 * New vignettes distinct from Mock Exams 1 and 2.
 */
import type { BDSQuestion } from "@/lib/content-types";
import { authored3 } from "@/content/mockExam/exams/bcbaPractice3/authoredHelper";

export const EXPANDED3_B: BDSQuestion[] = [
  authored3(
    3101,
    "B",
    "A clinic pairs a whistle with a mild air puff to the eye until the whistle alone elicits blinking. Staff later present the whistle immediately before a clicker that had never preceded the puff; after several pairings, the clicker alone elicits blinking. Which process BEST names acquisition of blinking to the clicker?",
    "B",
    [
      "Operant shaping of blinking under differential reinforcement",
      "Higher-order (second-order) respondent conditioning using the whistle as an established CS",
      "Negative reinforcement of blinking by termination of the puff",
      "Stimulus equivalence because whistle and clicker became interchangeable nodes",
    ],
    [
      "No differential consequences for blinking are described; the relation is CS–US pairing history.",
      "A previously conditioned CS (whistle) paired with a new NS (clicker) can establish the new CS—higher-order conditioning.",
      "Escape/avoidance of the puff would be operant; here blinking is elicited by antecedent CSs.",
      "Equivalence requires trained conditional relations and derived probes, not CS–US pairing alone.",
    ],
  ),
  authored3(
    3102,
    "B",
    "After weeks of contingent praise for completed worksheets, a student completes work at high rates. Staff then deliver the same praise on a dense fixed-time schedule regardless of work. Completion rates fall toward baseline even though praise still occurs often. What BEST explains the decline?",
    "D",
    [
      "Praise became an unconditioned punisher through satiation alone",
      "The fixed-time schedule converted praise into an establishing operation for escape",
      "Habituation abolished all social stimuli as reinforcers permanently",
      "Noncontingent delivery removed the response–reinforcer dependency that had maintained completion",
    ],
    [
      "Satiation can reduce reinforcer value, but the vignette highlights loss of contingency, not mere overdelivery as punishment.",
      "FT praise does not establish escape; it weakens the contingency between work and praise.",
      "Later contingent gains in similar cases show social praise can still reinforce; permanence is not implied.",
      "Reinforcement requires a dependency; breaking contingency while keeping the stimulus often weakens the operant.",
    ],
  ),
  authored3(
    3103,
    "B",
    "A learner’s property destruction produces brief access to a locked tablet. When destruction is blocked and tablet access is unavailable for destruction, destruction initially intensifies for two sessions, then declines across the week. Which account is MOST precise?",
    "A",
    [
      "Extinction of tangible-maintained destruction, with an extinction burst followed by decrease",
      "Positive punishment because blocking adds a novel aversive stimulus each instance",
      "An abolishing operation from satiation on tablets before demands begin",
      "Stimulus generalization from prior break routines to the blocking procedure",
    ],
    [
      "Withholding the functional tangible reinforcer is extinction; temporary intensification then decline fits extinction dynamics.",
      "Blocking may feel aversive, but the defining change is removal of tablet access contingent on destruction.",
      "No pre-session tablet satiation is described; access is withheld contingent on the response.",
      "Generalization concerns transfer across stimuli/settings; this is within-contingency extinction.",
    ],
  ),
  authored3(
    3104,
    "B",
    "During free play, a child repeatedly spins a top and smiles while alone; rates stay high when adults ignore the spinning and when preferred toys are freely available nearby. Removing the top’s visual/spinning feedback (a nonspinning replica) drops the response near zero. What maintaining process is MOST consistent?",
    "C",
    [
      "Social positive reinforcement by intermittent adult comments",
      "Escape from peer proximity when spinning begins",
      "Automatic reinforcement produced by the sensory products of spinning",
      "Rule-governed compliance with an unstated classroom spinning rule",
    ],
    [
      "Persistence when adults ignore and when alternatives are free argues against social attention as the primary reinforcer.",
      "Escape is not implicated when the child seeks the top’s products while alone.",
      "Persistence without social mediation and collapse when sensory products are removed fit automatic reinforcement.",
      "No instructional rule history is provided; the pattern tracks sensory consequences.",
    ],
  ),
  authored3(
    3105,
    "B",
    "A BCBA trains A→B and B→C matching-to-sample relations with distinct sample sets. Without direct training, the learner then matches A samples to C comparisons at high accuracy. Which derived relation is MOST clearly demonstrated?",
    "A",
    [
      "Transitivity (A–C) emerging from trained A–B and B–C relations",
      "Reflexivity because identity matching to A was never probed",
      "Symmetry of the B–C relation alone",
      "Respondent higher-order conditioning of comparison selection",
    ],
    [
      "Untrained A–C matching after A–B and B–C training is the transitive derived relation.",
      "Reflexivity is identity matching (A–A); the vignette concerns cross-class A–C performance.",
      "Symmetry would reverse a trained relation (e.g., C–B); A–C is transitivity.",
      "Derived matching under conditional discrimination is an operant equivalence phenomenon, not CS–US elicitation.",
    ],
  ),
  authored3(
    3106,
    "B",
    "Under concurrent VI schedules for two computer games with equal backup magnitude, a student allocates 90% of responses to Game A, which yields only about 55% of obtained reinforcers. Which description is MOST accurate?",
    "B",
    [
      "Undermatching: response allocation is less extreme than relative reinforcement",
      "Overmatching: response ratios are more extreme than reinforcement ratios",
      "Perfect matching because both games receive some responding",
      "Ratio strain unique to concurrent VI arrangements",
    ],
    [
      "Undermatching would show less extreme allocation than the reinforcer ratio; here allocation is more extreme.",
      "90/10 responding against roughly 55/45 reinforcement is more differentiated than strict matching—overmatching.",
      "Matching is quantitative; extreme bias with near-equal obtained reinforcement violates strict matching.",
      "Ratio strain concerns collapse under lean ratio schedules, not concurrent VI bias patterns.",
    ],
  ),
  authored3(
    3107,
    "B",
    "A teacher announces, “If you finish the packet before the timer, you may choose the art center.” A student who has never contacted that contingency nevertheless rushes to finish. After several days of contacting the stated outcome, finishing remains high even when reminders stop. What BEST captures the change across time?",
    "D",
    [
      "Behavior was always contingency-shaped; the announcement was irrelevant",
      "Rule statements cannot evoke behavior until direct reinforcement occurs first",
      "The timer functioned as a CMO-T establishing art materials as reinforcers",
      "Initially rule-governed finishing, later increasingly contingency-shaped as direct contact with the outcome maintained the operant",
    ],
    [
      "Early performance without prior contact implicates instructional control, not only direct shaping.",
      "Rules can evoke novel instances before direct reinforcement; later contact then strengthens the operant.",
      "The announcement specifies a contingency; it does not establish a missing tool/complementary stimulus as in CMO-T.",
      "Verbal specification can start control; subsequent direct reinforcement often shifts maintenance toward contingency shaping.",
    ],
  ),
  authored3(
    3108,
    "B",
    "Before outdoor recess, a student has gone 90 minutes without access to a preferred scooter. Mand rates for “scooter” soar when the shed is unlocked. After 20 minutes of continuous scooter play, the same unlocked shed evokes few mands. What BEST explains the change?",
    "C",
    [
      "The shed became an S-delta for mands after recess through extinction alone",
      "Scooter play punished mands by pairing them with physical exertion",
      "Deprivation established an EO for scooter-related mands; satiation abolished that EO",
      "Stimulus control shifted because staff voice tone changed after recess",
    ],
    [
      "No differential extinction of mands versus non-mands after recess is described.",
      "Access after mands typically reinforces under deprivation; exertion alone does not define punishment here.",
      "Deprivation establishes value and evocative strength; satiation abolishes them—matching the rate drop.",
      "Tone change is speculative when MO effects account for the data.",
    ],
  ),
  authored3(
    3109,
    "B",
    "A therapist reinforces selecting a picture of “cup” only when a spoken sample “cup” is presented; selections given “shoe” produce extinction. Accuracy becomes near-perfect. Which concept BEST describes the spoken sample’s role?",
    "A",
    [
      "Discriminative stimulus (SD) signaling reinforcement is available for the corresponding selection",
      "Establishing operation increasing the value of cups independent of the sample word",
      "Conditioned punisher suppressing selections when “shoe” is heard",
      "Neutral stimulus undergoing respondent pairing with edible delivery",
    ],
    [
      "Differential consequences tied to the sample establish the sample as an SD for the conditional discrimination.",
      "An EO alters reinforcer value; the vignette describes differential reinforcement linked to a cue.",
      "Extinction in the presence of “shoe” is SΔ control, not presentation of a punisher.",
      "The primary relation is operant stimulus control, not CS–US elicitation of selecting.",
    ],
  ),
  authored3(
    3110,
    "B",
    "Hand-raising is reinforced on VR 6 during group. After stable rates, staff abruptly shift to VR 50. Raising becomes irregular, long pauses appear, and rates nearly collapse despite continued intermittent praise. Which schedule phenomenon is MOST likely?",
    "C",
    [
      "Spontaneous recovery after a rest from extinction",
      "Behavioral contrast from an unchanged concurrent schedule in another room",
      "Ratio strain from thinning the VR schedule too abruptly",
      "Limited-hold expiry on a fixed-interval schedule",
    ],
    [
      "Spontaneous recovery follows time away from extinction, not abrupt ratio thinning.",
      "Contrast requires a comparison component; only one schedule change is described.",
      "Large, sudden VR increases often produce ratio strain—paused or collapsed responding.",
      "Limited hold and FI parameters are not the programmed schedule here.",
    ],
  ),
  authored3(
    3111,
    "B",
    "A learner says “water” while reaching toward a closed bottle and receives water. Later, when shown a picture of water with no drink forthcoming, the learner says “water” and receives praise for labeling. How do these utterances DIFFER most usefully for verbal-behavior analysis?",
    "B",
    [
      "Both are pure mands because the word form is identical",
      "The first is primarily a mand under deprivation/EO; the second is primarily a tact under nonverbal stimulus control with social reinforcement",
      "Both are intraverbals controlled solely by verbal antecedents",
      "The second is an echoic because praise followed the vocalization",
    ],
    [
      "Identical topography does not equate function; controlling variables differ.",
      "Mand control involves MO/specific reinforcement; tact control involves nonverbal SD plus generalized social reinforcement.",
      "Neither utterance is described as controlled by a preceding verbal stimulus of a different form.",
      "Echoics require a verbal auditory model matching the response; praise alone does not define echoic function.",
    ],
  ),
  authored3(
    3112,
    "B",
    "Staff historically delivered a break when a student covered both ears during fire-drill practice. Covering now reliably precedes drills and produces escape. Neutral hallway noise does not evoke covering. Which MO classification BEST fits the pre-drill announcement paired with rising covering?",
    "D",
    [
      "CMO-S (surrogate) because it was paired with food deprivation",
      "CMO-T (transitive) establishing earplugs as reinforcers for a locked cabinet",
      "Unconditioned EO for auditory pain independent of learning history",
      "CMO-R (reflexive): a warning stimulus whose onset increases the value of escape from the worsening condition it signals",
    ],
    [
      "No food-deprivation pairing is described.",
      "CMO-T establishes value of a missing complementary stimulus; the vignette centers on escape from signaled worsening.",
      "The evocative pattern is tied to a learned drill-warning history, not an unconditioned pain EO alone.",
      "A learned warning cue that establishes escape as more valuable and evokes escape behavior is a CMO-R.",
    ],
  ),
  authored3(
    3113,
    "B",
    "In a multiple baseline across settings, a student’s call-outs produce dense peer laughter in the cafeteria but near-zero laughter in the library. After cafeteria staff suppress peer laughter, call-outs rise sharply in the library even though library contingencies never changed. What phenomenon is MOST clearly illustrated?",
    "A",
    [
      "Behavioral contrast: rate change in one component alters responding in an unchanged concurrent component",
      "Renewal solely from returning to the original physical cafeteria",
      "Resurgence of an earlier operant after extinction of a replacement mand",
      "Habituation to library quiet that abolishes attention value",
    ],
    [
      "An increase in an unchanged component after thinning/enrichment changes elsewhere is classic behavioral contrast.",
      "The rise is in the library, not a return to the cafeteria context.",
      "No alternative mand extinction sequence is described.",
      "Habituation would reduce stimulus effectiveness; here a contingency change in another setting precedes the increase.",
    ],
  ),
  authored3(
    3114,
    "B",
    "A BCBA wants a low-rate of rapid pencil tapping during exams. Staff deliver a token only if interresponse times between taps exceed 10 seconds throughout a work block. Tapping slows and becomes spaced. Which schedule arrangement BEST names this procedure?",
    "C",
    [
      "DRH: reinforcement for rates above a high criterion",
      "FR 1 for each tap regardless of spacing",
      "DRL: reinforcement contingent on low rates / sufficiently long IRTs",
      "FT token delivery independent of tapping",
    ],
    [
      "DRH strengthens high rates; the goal and contingency here reduce rate.",
      "FR 1 for taps would maintain or increase tapping, not space it.",
      "Differential reinforcement of low rates reinforces meeting a minimum IRT/low-rate criterion.",
      "Tokens are dependent on IRT criteria, not purely time-based.",
    ],
  ),
  authored3(
    3115,
    "B",
    "Selecting “dog” given a green card was mastered. A highly salient glitter border is then added around incorrect comparisons; accuracy collapses as looking tracks the glitter. Removing glitter restores accuracy. Softening glitter during teaching also prevents the collapse. Which stimulus-control account BEST fits?",
    "B",
    [
      "Masking of a fully intact discrimination by a simultaneous disruptor with no competition for control",
      "Overshadowing: a more salient irrelevant feature competes with control by the relevant sample–comparison relation",
      "Failure of reflexivity because identity matching was never probed",
      "An abolishing operation reducing token value mid-session",
    ],
    [
      "Masking typically leaves underlying control demonstrable under other tests; here the salient feature appears to capture control.",
      "A salient competing feature that draws control away from the trained relation is overshadowing.",
      "Reflexivity probes identity matching; the vignette concerns border salience.",
      "No MO manipulation of tokens is described; accuracy tracks the visual feature.",
    ],
  ),
  authored3(
    3116,
    "B",
    "Under a rich FI 5-min schedule for puzzle completion, a learner begins rocking in stereotyped bursts during the early portion of each interval, peaking at intermediate times unrelated to puzzle contact. Rocking was never explicitly reinforced. Which account is MOST consistent?",
    "A",
    [
      "Schedule-induced (adjunctive) rocking emerging as a byproduct of intermittent reinforcement timing",
      "Rocking as a pure mand for puzzles under an EO for task materials",
      "Escape-maintained rocking because staff remove the puzzle when rocking occurs",
      "Rocking as an SD that occasions puzzle completion through equivalence",
    ],
    [
      "Adjunctive behaviors often appear under intermittent schedules during post-reinforcement/early-interval periods without direct reinforcement.",
      "No specific reinforcement of rocking by puzzle delivery is described.",
      "Contingent puzzle removal is not stated; rocking tracks FI timing structure.",
      "Treating rocking as an SD/equivalence node mislabels a temporally patterned adjunctive operant.",
    ],
  ),
  authored3(
    3117,
    "B",
    "A teenager can recite “ask before borrowing,” yet continues taking peers’ markers when taking produces immediate access and peer protests are delayed. After protests are blocked from delaying access and asking contacts prompt marker lending, taking declines. What does this contrast MOST strongly illustrate?",
    "D",
    [
      "Rule-governed behavior always overrides direct contingency control",
      "Verbal repertoires cannot participate in classroom stimulus control",
      "Contingency-shaped taking is impossible once a rule has been stated",
      "Stated rules may fail when conflicting direct contingencies are richer; rearranging consequences changes behavior",
    ],
    [
      "The rule failed until contingencies changed—opposite of rules always overriding.",
      "Rules can influence behavior; competing reinforcement for taking is the issue.",
      "Taking was maintained by immediate access despite the rule—clear contingency shaping.",
      "When direct reinforcement outcompetes instructional control, contingency change is decisive.",
    ],
  ),
  authored3(
    3118,
    "B",
    "A response-cost system removes two tokens from a board after each shove; tokens otherwise exchange for a preferred break. Shoving decreases sharply within a week with no reprimands added. What BEST names the consequence process for shoving?",
    "C",
    [
      "Positive reinforcement of calm waiting by token accumulation alone",
      "Negative reinforcement via escape from the token board itself",
      "Negative punishment: contingent removal of conditioned reinforcers",
      "Positive punishment through presentation of a reprimand after shoving",
    ],
    [
      "Token accumulation may support alternatives, but the active consequence for shoving is removal.",
      "Escape from the board is not described; tokens are removed contingent on shoving.",
      "Contingent removal of tokens that reduces shoving is negative punishment.",
      "No reprimand is specified; the programmed consequence is loss of tokens.",
    ],
  ),
  authored3(
    3119,
    "B",
    "A clinician trains a learner to press a blue switch for music only when a yellow card is on the table. Presses with the card absent produce no music. Soon nearly all presses occur with the card present. After training, presses still occur when a novel orange card of similar size is present. What BEST describes the orange-card effect?",
    "B",
    [
      "Failure of discrimination because topography varied across trials",
      "Stimulus generalization of SD control along shared physical features",
      "An establishing operation unique to orange hues",
      "Respondent sensitization to card onset independent of music history",
    ],
    [
      "Differential reinforcement under the yellow card indicates a discrimination formed; novel-card presses reflect generalization.",
      "Responding to a novel stimulus sharing features with a trained SD is stimulus generalization.",
      "No MO manipulation tied to orange is described.",
      "The pattern is operant SD generalization, not respondent sensitization.",
    ],
  ),
  authored3(
    3120,
    "B",
    "Aggression historically produced escape. Staff then reinforced a break card on FR 1 while placing aggression on extinction; aggression fell near zero. Months later, during a substitute shortage, the break card contacts extinction. Aggression reappears at high rates though the classroom layout is unchanged. Which process BEST accounts for the reappearance?",
    "A",
    [
      "Resurgence of a previously reinforced response when the more recently reinforced alternative contacts extinction",
      "Renewal driven solely by return to the original physical setting",
      "Spontaneous recovery after a temporal break from the extinction context alone",
      "Habituation to demand materials that abolishes escape value",
    ],
    [
      "Recovery of an earlier reinforced operant when a later alternative is extinguished defines resurgence.",
      "Renewal is context-change reappearance; the vignette emphasizes extinction of the alternative, not a setting shift.",
      "Spontaneous recovery follows time away from extinction without requiring extinction of a replacement response.",
      "Habituation would reduce stimulus effectiveness; a contingency change on the alternative precedes the increase.",
    ],
  ),
  authored3(
    3121,
    "B",
    "A student must complete a nonpreferred sorting task to earn access to drawing, a higher-probability activity. Sorting rates rise only when drawing is contingent on sorting and fall when drawing is free. Which principle BEST accounts for the increase?",
    "D",
    [
      "Matching law undermatching within a single VI schedule",
      "Respondent conditioning of sorting by pairing with autonomic arousal",
      "Negative punishment of idle waiting by removal of peer attention",
      "Premack principle: contingent access to a high-probability behavior reinforces a low-probability behavior",
    ],
    [
      "Concurrent VI allocation is not the arrangement described.",
      "The effective relation is operant contingency between sorting and drawing access.",
      "Peer attention removal is not the programmed consequence.",
      "Making a high-probability activity contingent on a low-probability one is the Premack arrangement.",
    ],
  ),
  authored3(
    3122,
    "B",
    "A therapist delivers a preferred video clip within 1 second after every instance of hand-raising, but also delivers the same clip on a dense time-based schedule whether or not raising occurs. Raising stays near baseline. When noncontingent clips stop and clips follow only raising, rates climb. What BEST explains the earlier failure?",
    "C",
    [
      "One-second delays make reinforcement conceptually impossible",
      "Video clips cannot function as reinforcers for motor responses",
      "Contiguity without a dependency (contingency) is insufficient; noncontingent delivery weakened the response–reinforcer relation",
      "The rise after removing NCR proves respondent conditioning of hand-raising",
    ],
    [
      "Brief delays can still support reinforcement when a clear dependency exists.",
      "Later contingent gains show the clip can reinforce raising.",
      "Reinforcement requires a contingency; adventitious contiguity amid NCR often fails to strengthen the target.",
      "The effective change is operant contingency arrangement, not CS–US elicitation of raising.",
    ],
  ),
  authored3(
    3123,
    "B",
    "During FI 2-min reinforcement for button presses, cumulative records show accelerating response rates toward the end of each interval and a post-reinforcement pause. Which schedule performance pattern is MOST clearly indicated?",
    "A",
    [
      "FI scallop: pause after reinforcement then accelerating responding as the interval ends",
      "VR break-and-run pattern with fixed run length after each reinforcer",
      "DRL IRT distributions tightly clustered just below the criterion",
      "Extinction burst confined to the first second after each reinforcer",
    ],
    [
      "Post-reinforcement pause plus acceleration into the interval end is the classic FI scallop.",
      "Break-and-run is more characteristic of FR schedules, not FI acceleration across the interval.",
      "DRL concerns spacing IRTs, not FI end-of-interval acceleration.",
      "An extinction burst is a temporary increase when reinforcement is withheld, not FI timing microstructure.",
    ],
  ),
  authored3(
    3124,
    "B",
    "A learner avoids a buzzing timer by pressing a switch that prevents the timer from starting; presses occur before any buzz. When prevention is disabled and presses only terminate an already-sounding buzz, presses still occur but after onset. How do these two contingencies DIFFER most usefully?",
    "B",
    [
      "Both are positive reinforcement by presentation of the buzz",
      "The first is avoidance (preventing onset); the second is escape (terminating an ongoing aversive)",
      "Both are extinction because the buzz never contacts the learner",
      "The second is a CMO-S for edible reinforcers",
    ],
    [
      "Buzz presentation would be aversive stimulation, not the reinforcer maintaining presses.",
      "Preventing an aversive’s onset is avoidance; terminating an ongoing aversive is escape—both negative reinforcement forms.",
      "Reinforcement is occurring via prevention or termination; extinction would withhold that consequence.",
      "CMO-S involves surrogate pairing with another MO; not indicated here.",
    ],
  ),
  authored3(
    3125,
    "B",
    "Mastery of a greeting repertoire quickly enables peer conversations, classroom participation, and access to group games that were previously unavailable. Gains cascade across settings without teaching each context separately. Which concept BEST fits the greeting skill’s impact?",
    "D",
    [
      "Behavioral contrast across concurrent cafeteria schedules",
      "An abolishing operation that reduces the value of peer attention",
      "Overshadowing of peer faces by the greeting topography",
      "A behavioral cusp: a change that exposes the learner to new contingencies and rapid further learning",
    ],
    [
      "Contrast concerns rate shifts across schedule components, not cascading access to new learning opportunities.",
      "The vignette describes expanded access to social reinforcers, not reduced attention value.",
      "Overshadowing is a stimulus-control competition effect, not broad repertoire expansion.",
      "Skills that open substantial new environments and contingencies are behavioral cusps.",
    ],
  ),
  authored3(
    3126,
    "B",
    "A conditional discrimination is taught: given a triangle sample, selecting “same” is reinforced; given a circle, selecting “different” is reinforced when comparisons vary. Errors surge when samples are replaced with highly similar polygons that still differ subtly. Which analysis is MOST precise?",
    "C",
    [
      "The learner never formed any discrimination because topography varied",
      "Similar polygons functioned as unconditioned punishers suppressing all selections",
      "Stimulus control was tied to previously discriminable sample features; reduced discriminability weakened conditional control",
      "Samples were establishing operations for edible reinforcers rather than discriminative cues",
    ],
    [
      "Differential reinforcement under distinct samples indicates a discrimination had formed under clearer forms.",
      "Nothing indicates polygons were contingent punishers; errors reflect loss of cue control.",
      "When critical sample features become less discriminable, conditional stimulus control weakens—matching the error surge.",
      "Samples signaled which comparison was correct—discriminative/conditional control—not MOs for edibles.",
    ],
  ),
];

export const EXPANDED3_C: BDSQuestion[] = [
  authored3(
    3201,
    "C",
    "Two observers record self-injury counts of 22 and 17 in the same 15-minute session. The BCBA must report total count IOA. Which calculation and interpretation are MOST appropriate?",
    "A",
    [
      "IOA = (smaller/larger) × 100 = 17/22 ≈ 77%, which may be inadequate for high-stakes decisions",
      "IOA = 22/17 ≈ 129%, indicating excellent agreement",
      "IOA = (22 − 17)/22 = 23% disagreement reported as IOA",
      "Total count IOA cannot be computed unless interval-by-interval data exist",
    ],
    [
      "Total count IOA is smaller/larger × 100; ~77% often falls below preferred thresholds for important targets.",
      "IOA conventions use smaller over larger; values over 100% are not the standard report.",
      "Disagreement percentage is not the IOA metric requested.",
      "Total count IOA is specifically for continuous event counts without requiring intervals.",
    ],
  ),
  authored3(
    3202,
    "C",
    "Observers use partial-interval recording for brief, low-rate eye poking. Mean interval-by-interval IOA is 96%, but nearly all disagreements occur in the few intervals either observer scores as occurrence. Which IOA refinement BEST exposes that problem?",
    "D",
    [
      "Unscored-interval IOA only, because it ignores intervals with any occurrence",
      "Total duration IOA, because interval methods cannot assess agreement on rare events",
      "Trial-by-trial IOA for free-operant poking without trial structure",
      "Scored-interval IOA, which evaluates agreement only on intervals at least one observer marks as occurrence",
    ],
    [
      "Unscored-interval IOA focuses on nonoccurrence intervals—often inflating agreement for rare behaviors.",
      "Duration IOA is a different dimensional measure; the issue is occurrence agreement on rare intervals.",
      "Trial-by-trial IOA applies to discrete trials, not free-operant interval records.",
      "Scored-interval IOA is sensitive when occurrences are rare and disagreements cluster there.",
    ],
  ),
  authored3(
    3203,
    "C",
    "A BCBA graphs correct typing responses per minute on a standard celeration chart and reports a ×2.5 celeration across a week of intervention. What does that report MOST directly convey?",
    "B",
    [
      "Accuracy reached exactly 250% of opportunities",
      "Response rate multiplied by about 2.5 per week along a multiplicative trend",
      "IOA increased by a factor of 2.5 from baseline",
      "Latency was cut to 40% of baseline on every trial",
    ],
    [
      "Celeration concerns rate change over time, not a percent-correct ceiling of 250%.",
      "Celeration describes multiplicative change in rate; ×2.5/week indicates roughly 2.5× rate change per week.",
      "IOA is observer agreement, not celeration.",
      "Latency is a different dimensional quantity than rate celeration.",
    ],
  ),
  authored3(
    3204,
    "C",
    "Staff score worksheet completion via permanent product after sessions. Products look complete, yet spot video shows a peer finished many items for the learner. Which measurement concern is PRIMARY?",
    "C",
    [
      "Poor interobserver agreement on the permanent product scores themselves",
      "Insufficient interresponse-time sensitivity of product measures",
      "Threat to validity: the product does not accurately reflect the learner’s behavior",
      "Observer drift in the operational definition of worksheet lines",
    ],
    [
      "Product scores may agree perfectly while still misattributing who behaved.",
      "IRT is not the dimension permanent product is meant to capture here.",
      "Validity fails when the measure does not represent the intended individual’s behavior.",
      "Definitions may be stable; the core issue is authorship of the product.",
    ],
  ),
  authored3(
    3205,
    "C",
    "When a novel data collector with a clipboard stands beside a learner, on-task percentages jump relative to sessions scored from a discreet camera. Definitions and training are identical. What artifact is MOST likely?",
    "A",
    [
      "Observer reactivity: behavior changes because observation is discriminable",
      "Measurement decay from discontinuous interval length",
      "Treatment integrity drift in the independent variable",
      "Ceiling effects inherent to momentary time sampling",
    ],
    [
      "Discriminable observation altering the target is observer reactivity.",
      "Interval length is unchanged across conditions in the vignette.",
      "IV integrity concerns intervention implementation, not the observation cue effect.",
      "MTS can miss events, but the jump tied to a visible observer points to reactivity.",
    ],
  ),
  authored3(
    3206,
    "C",
    "A team wants to know how long tantrums last from onset to calm. Observers start a timer at the first scream and stop when calm criteria are met for 30 continuous seconds. Which dimensional quantity are they measuring?",
    "B",
    [
      "Latency from demand presentation to first scream",
      "Duration of each tantrum episode",
      "Interresponse time between successive screams",
      "Count/rate of screams per minute only",
    ],
    [
      "Latency would start at an antecedent (e.g., demand) and end at behavior onset.",
      "Timing from onset to offset indexes episode duration.",
      "IRT measures time between consecutive responses, not episode length.",
      "Count/rate ignores how long episodes last.",
    ],
  ),
  authored3(
    3207,
    "C",
    "Whole-interval recording is used for on-task behavior in 10-second intervals. Compared with continuous timing, percentages systematically underestimate true on-task. Why is that bias EXPECTED?",
    "D",
    [
      "Whole-interval methods always overestimate continuous duration",
      "Observers score an interval if behavior occurs at any moment",
      "Momentary sampling at the end of intervals inflates occurrence",
      "The interval is scored only if behavior occurs throughout; brief off-task moments zero the whole interval",
    ],
    [
      "Whole-interval recording tends to underestimate duration/occurrence of the target.",
      "Scoring any occurrence is partial-interval logic, which tends to overestimate.",
      "That describes momentary time sampling, not whole-interval rules.",
      "Whole-interval requires continuous occurrence; any break yields a nonoccurrence score—systematic underestimation.",
    ],
  ),
  authored3(
    3208,
    "C",
    "Partial-interval recording for stereotypy in 15-second intervals yields much higher percentages than continuous duration measures of the same sessions. Which statement BEST explains the discrepancy?",
    "C",
    [
      "Partial-interval methods require behavior throughout the interval",
      "Partial-interval IOA cannot be computed for stereotypy",
      "Any occurrence in an interval scores the whole interval, inflating estimated presence relative to true duration",
      "Partial-interval recording measures latency rather than occurrence",
    ],
    [
      "Continuous occurrence is the whole-interval rule.",
      "IOA can be computed for interval methods; that is not the bias explanation.",
      "Partial-interval overestimates duration/presence when brief events mark entire intervals.",
      "Partial-interval indexes occurrence within intervals, not latency.",
    ],
  ),
  authored3(
    3209,
    "C",
    "A BCBA compares two observers’ codes for discrete-trial correct/incorrect on 40 trials: they agree on 34 trials. What is the MOST appropriate IOA report for these data?",
    "A",
    [
      "Trial-by-trial IOA = 34/40 × 100 = 85%",
      "Total count IOA using smaller/larger of total corrects only",
      "Scored-interval IOA because trials are free-operant intervals",
      "Mean duration IOA across the session",
    ],
    [
      "Discrete trials with binary codes are suited to trial-by-trial (point-by-point) IOA.",
      "Total count IOA ignores trial-by-trial disagreements and is for event totals.",
      "Scored-interval IOA applies to interval recording of free-operant behavior.",
      "Duration IOA is for timing measures, not trial accuracy codes.",
    ],
  ),
  authored3(
    3210,
    "C",
    "On an equal-interval line graph, intervention data show little change in mean level but a clear shift from highly variable baseline to tightly clustered intervention points. Which visual feature changed MOST?",
    "B",
    [
      "Trend slope from steep ascending to steep descending",
      "Variability / bounce decreased while level remained similar",
      "Celeration on a multiply scale only",
      "IOA percentage plotted as the primary dependent variable",
    ],
    [
      "No slope reversal is described; the vignette highlights bounce.",
      "Reduced scatter around a similar mean is a change in variability.",
      "Equal-interval graphs do not report SCC-style celeration as the primary description here.",
      "The DV is the target behavior’s graphed values, not IOA.",
    ],
  ),
  authored3(
    3211,
    "C",
    "Observers record the seconds from “Start your work” to the first pencil mark. Across sessions, that value decreases from 45 s to 8 s while problem completion rates are not yet graphed. Which measure is being emphasized?",
    "D",
    [
      "Duration of work engagement until break",
      "IRT between successive pencil marks",
      "Percent of intervals on-task",
      "Latency to task initiation",
    ],
    [
      "Duration would time how long engagement lasts, not time to first mark.",
      "IRT is time between responses, not from instruction to first response.",
      "Interval on-task is a discontinuous estimate of engagement, not start latency.",
      "Time from antecedent cue to behavior onset is latency.",
    ],
  ),
  authored3(
    3212,
    "C",
    "A cumulative record of button presses rises steeply, then becomes flat for several minutes, then rises steeply again. Reinforcers are marked with pips. What does a flat segment MOST directly indicate?",
    "C",
    [
      "Negative scores accumulated during that period",
      "The observer reset the y-axis to zero mid-session",
      "Little or no responding occurred during that time",
      "Rate was highest during the flat segment",
    ],
    [
      "Cumulative records do not decrease for nonoccurrence; they hold steady.",
      "Resetting is a graphing choice not implied by a flat run of the record.",
      "Slope reflects rate; a flat cumulative path means near-zero presses.",
      "Highest rates produce the steepest ascending slopes, not flats.",
    ],
  ),
  authored3(
    3213,
    "C",
    "Two observers’ interval records for aggression yield high unscored-interval IOA but low scored-interval IOA. Behavior is rare. What interpretation is MOST appropriate?",
    "B",
    [
      "Agreement is uniformly excellent because unscored-interval IOA is high",
      "Observers agree on nonoccurrence intervals but disagree when aggression is scored by either—problematic for rare behavior",
      "Total count IOA must be 100% whenever unscored-interval IOA is high",
      "Scored-interval IOA is invalid for low-rate behaviors and should be ignored",
    ],
    [
      "High unscored-interval IOA can mask disagreement on the rare occurrence intervals that matter most.",
      "The pattern shows good nonoccurrence agreement and poor occurrence agreement—critical for rare events.",
      "Unscored-interval and total count IOA are different metrics; one does not force the other to 100%.",
      "Scored-interval IOA is especially informative for rare behaviors; it should not be ignored.",
    ],
  ),
  authored3(
    3214,
    "C",
    "Momentary time sampling every 30 seconds is used for a high-rate, rapidly fluctuating stereotypy. Continuous duration later shows much higher engagement than MTS percentages. Which limitation is MOST relevant?",
    "A",
    [
      "MTS can miss occurrences between observation moments, underestimating rapidly fluctuating behavior",
      "MTS always overestimates duration relative to continuous measures",
      "MTS requires behavior throughout each 30-second interval",
      "MTS cannot be used unless IOA is calculated as total duration",
    ],
    [
      "Brief samples at moments can miss between-sample engagement—underestimation risk for fast-changing behavior.",
      "MTS bias direction depends on parameters; it does not always overestimate.",
      "Continuous occurrence within intervals is whole-interval logic.",
      "IOA method is independent of whether MTS is permissible.",
    ],
  ),
  authored3(
    3215,
    "C",
    "After three months, a veteran observer gradually scores “aggression” for lighter taps that newer observers still code as nonoccurrence, though the written definition is unchanged. IOA with a newly trained second observer declines. What problem is MOST likely?",
    "D",
    [
      "Observer reactivity by the learner to the clipboard",
      "Treatment integrity failure on the BIP steps",
      "Invalid permanent-product measurement of aggression",
      "Observer drift: gradual unintended change in how the definition is applied",
    ],
    [
      "The vignette centers on coding shift, not learner change due to being watched.",
      "Integrity concerns IV delivery, not DV coding drift.",
      "Aggression is being coded live, not via permanent product.",
      "Slow change in applying a stable written definition is observer drift.",
    ],
  ),
  authored3(
    3216,
    "C",
    "Two data collectors produce nearly identical frequency totals session after session, but a video criterion record shows both systematically omit brief instances the definition includes. Which statement is MOST accurate?",
    "C",
    [
      "High reliability guarantees high accuracy",
      "The measure is accurate but unreliable",
      "The measure is reliable (consistent) but inaccurate relative to the true events",
      "IOA is impossible whenever a criterion record exists",
    ],
    [
      "Observers can agree while sharing the same error—reliability without accuracy.",
      "Agreement with shared omissions is reliability, not accuracy.",
      "Consistency between observers with shared misses is reliability without accuracy.",
      "Criterion records are used to evaluate accuracy; IOA remains computable among observers.",
    ],
  ),
  authored3(
    3217,
    "C",
    "A BCBA asks caregivers to rate intervention acceptability, perceived helpfulness, and willingness to continue after 4 weeks. These ratings are collected separately from frequency data. What type of information is being gathered?",
    "B",
    [
      "Interobserver agreement on the primary dependent variable",
      "Social validity of goals, procedures, and/or outcomes from stakeholder perspectives",
      "Treatment integrity of discrete-trial prompting steps",
      "Exact count-per-interval IOA",
    ],
    [
      "Caregiver ratings are not dual-observer coding of the target behavior.",
      "Stakeholder judgments of acceptability/importance are social validity measures.",
      "Integrity checklists score implementation, not acceptability ratings.",
      "IOA metrics are agreement calculations, not satisfaction ratings.",
    ],
  ),
  authored3(
    3218,
    "C",
    "Staff score whether each BIP step occurred using a yes/no checklist while a second observer simultaneously codes learner aggression. Checklist agreement is 70%; aggression IOA is 95%. Which conclusion is MOST defensible?",
    "A",
    [
      "Treatment integrity measurement is weak even though aggression IOA is strong; improve integrity training/monitoring",
      "Aggression IOA of 95% proves the BIP was implemented with fidelity",
      "Integrity checklists and aggression IOA are interchangeable metrics",
      "70% integrity agreement means aggression data are invalid automatically",
    ],
    [
      "Integrity and DV agreement are distinct; low integrity IOA warrants better IV measurement/training.",
      "Strong DV IOA does not certify that intervention steps were delivered as designed.",
      "They measure different variables and are not interchangeable.",
      "Integrity agreement problems do not automatically invalidate a well-measured DV, but they threaten interpretation of effects.",
    ],
  ),
  authored3(
    3219,
    "C",
    "A target occurs at near-zero rates in baseline and remains near zero in intervention; another target is already at 100% of intervals before teaching. Which measurement concern is MOST relevant when interpreting “no change”?",
    "D",
    [
      "Observer reactivity unique to cumulative records",
      "Scored-interval IOA cannot be computed at extreme rates",
      "Celeration is undefined on equal-interval graphs",
      "Floor and ceiling effects can obscure detection of further change",
    ],
    [
      "Reactivity is not the primary issue described by extreme baseline levels.",
      "IOA can still be computed; extreme rates create different interpretive challenges.",
      "Equal-interval graphs can still show level/trend; celeration is an SCC concept.",
      "Values already at extremes leave little room to show improvement or worsening—floor/ceiling effects.",
    ],
  ),
  authored3(
    3220,
    "C",
    "Event recording of head hits is feasible because hits are discrete, brief, and have clear onsets. Sessions vary from 10 to 40 minutes. Which reporting approach BEST supports comparison across sessions?",
    "C",
    [
      "Report raw totals only, ignoring session length differences",
      "Convert all data to whole-interval percentages of hits",
      "Report rate (hits per minute) or equate session lengths before comparing totals",
      "Use latency from session start as the sole measure of head hitting",
    ],
    [
      "Unequal durations make raw totals misleading for comparison.",
      "Whole-interval is a discontinuous estimate, not required when events are countable.",
      "Rate standardizes for time, or equal durations allow fair total comparisons.",
      "Latency does not capture how often hits occur during the session.",
    ],
  ),
  authored3(
    3221,
    "C",
    "Mean count-per-interval IOA is calculated across 10 intervals with per-interval agreements of 100%, 50%, 100%, 0%, 100%, 100%, 50%, 100%, 100%, and 100%. Which value results?",
    "B",
    [
      "100%, because most intervals were perfect",
      "80% (average of the 10 per-interval IOA percentages)",
      "0%, because any imperfect interval zeros the mean",
      "Total count IOA of smaller/larger session totals only",
    ],
    [
      "Mean count-per-interval averages interval values; it is not the mode.",
      "Averaging the listed percentages yields 0.8 × 100 = 80%.",
      "Imperfect intervals reduce the mean; they do not force it to zero.",
      "The vignette asks for mean count-per-interval, not session total count IOA.",
    ],
  ),
  authored3(
    3222,
    "C",
    "An operational definition of “elopement” states only “leaves the area.” Observers disagree on doorway thresholds, playground boundaries, and brief steps outside a carpet square. Which improvement BEST addresses the disagreement?",
    "A",
    [
      "Specify measurable boundaries, onset/offset criteria, and examples/nonexamples for leaving the defined area",
      "Switch to permanent product of elopement because products remove definition needs",
      "Rely solely on unscored-interval IOA to fix ambiguous definitions",
      "Graph disagreement percentages instead of refining the definition",
    ],
    [
      "Clear boundaries and onset/offset rules improve consistency and validity of the measure.",
      "Permanent products still require definitions of what constitutes the product event.",
      "IOA formulas do not repair ambiguous definitions.",
      "Graphing disagreement does not create a clearer behavioral definition.",
    ],
  ),
];

export const EXPANDED3_F: BDSQuestion[] = [
  authored3(
    3301,
    "F",
    "A clinic presents an array of leisure items, allows the learner to select one, removes that item, and re-presents the remaining items until the array is exhausted; ranks are based on selection order. Which preference assessment is this?",
    "B",
    [
      "Free-operant preference assessment with unrestricted access",
      "Multiple-stimulus without replacement (MSWO)",
      "Paired-stimulus forced choice across all dyads only",
      "Progressive-ratio breakpoint assessment of reinforcer efficacy",
    ],
    [
      "Free-operant allows concurrent free engagement without successive removal-re-presentation trials.",
      "Selecting, removing, and re-presenting remainders until depletion is MSWO.",
      "Paired-stimulus presents two items per trial, not a shrinking multiple array.",
      "PR assessments manipulate schedule requirements; they do not rank by selection order in a shrinking array.",
    ],
  ),
  authored3(
    3302,
    "F",
    "An MSW (with replacement) repeatedly returns the same toy to the array after selection. One item dominates nearly every trial, preventing ranking of lower items. What is the MOST appropriate adjustment?",
    "C",
    [
      "Conclude no preferences exist among the remaining items",
      "Switch immediately to an alone-condition FA of toy play",
      "Use MSWO (without replacement) or paired-stimulus methods that force sampling across items",
      "Increase array size while keeping replacement to intensify dominance",
    ],
    [
      "Dominance under replacement often masks relative ranks rather than proving indifference.",
      "FA of play does not solve preference hierarchy problems.",
      "Without-replacement or paired methods compel engagement with multiple items to differentiate ranks.",
      "Larger arrays with replacement can worsen single-item monopolization.",
    ],
  ),
  authored3(
    3303,
    "F",
    "In a paired-stimulus assessment, the learner selects the item on the right on 19 of 20 trials regardless of which object is placed right. Rankings appear orderly but collapse when sides are counterbalanced. What threat is MOST likely?",
    "A",
    [
      "Position bias systematically distorting stimulus preference rankings",
      "Absolute reinforcer efficacy proven by side preference",
      "Multiple-stimulus overselection identical to MSWO",
      "Undermatching in concurrent VI preference",
    ],
    [
      "Consistent side selection despite item swaps is classic position bias.",
      "Side preference indicates position control, not item reinforcer value.",
      "This is a paired-stimulus format issue, not MSWO overselection.",
      "Matching law concurrent schedules are not the assessment procedure described.",
    ],
  ),
  authored3(
    3304,
    "F",
    "High-preference cartoons fail to increase a filing response when delivered contingently, yet a moderate-preference sticker produces clear increases under the same schedule. Preference ranks were stable. What is the BEST next interpretive step?",
    "D",
    [
      "Discard all preference assessments as invalid forever",
      "Treat cartoons as the functional reinforcer because preference rank was higher",
      "Conclude filing is multiply maintained by escape and attention",
      "Treat preference and reinforcer assessments as related but distinct; rely on contingent efficacy data for intervention selection",
    ],
    [
      "A preference–reinforcer mismatch on one item does not void the assessment approach.",
      "Higher preference rank did not predict reinforcement function for filing.",
      "No FA data on filing’s problem-behavior function are provided.",
      "Preference predicts likelihood; reinforcer assessments confirm function for a target response.",
    ],
  ),
  authored3(
    3305,
    "F",
    "Indirect tools suggest attention; ABC narrative data suggest escape; a standard FA shows differentially high rates in escape. The team still wants an attention BIP because “interviews feel convincing.” Which synthesis is MOST defensible?",
    "A",
    [
      "Weight the FA differentiation most heavily; design escape-based treatment while monitoring for multiply maintained patterns",
      "Prioritize interviews whenever caregivers are emotionally confident",
      "Average the three methods into an “attention/escape 50-50” function without further analysis",
      "Discard the FA because it contradicted the interview",
    ],
    [
      "Experimental differentiation is the strongest functional evidence among the three when safely obtained.",
      "Confidence is not a validity metric for indirect tools.",
      "Mechanical averaging of conflicting methods is not sound functional synthesis.",
      "Contradiction is a reason to trust careful FA more, not discard it.",
    ],
  ),
  authored3(
    3306,
    "F",
    "During a functional analysis, rates of hand-biting are high in the alone/ignore condition and low in attention, escape, and play. What function is MOST consistent with this pattern?",
    "C",
    [
      "Social positive reinforcement by contingent attention",
      "Social negative reinforcement by demand removal",
      "Automatic (nonsocial) reinforcement maintained by sensory products of biting",
      "Tangible reinforcement by contingent toy delivery",
    ],
    [
      "Attention-condition elevation would support social positive reinforcement.",
      "Escape-condition elevation would support demand removal as the reinforcer.",
      "Differentially high alone/ignore rates with low social-condition rates implicate automatic reinforcement.",
      "Tangible elevation would appear in a tangible test condition, not alone.",
    ],
  ),
  authored3(
    3307,
    "F",
    "In an FA attention condition, problem behavior produces brief social comments and physical contact; in play, attention is delivered freely for appropriate engagement and problem behavior is ignored. Problem behavior is high only in attention. What does this differentiation MOST strongly support?",
    "B",
    [
      "Escape from tasks as the maintaining reinforcer",
      "Social positive reinforcement (attention) as a maintaining contingency",
      "Automatic reinforcement because play includes leisure items",
      "Undifferentiated responding requiring no further interpretation",
    ],
    [
      "Escape would elevate in a demand/escape test, not selectively in attention.",
      "High attention vs low play (with free attention for appropriate behavior) supports attention-maintained problem behavior.",
      "Leisure items in play do not redefine the attention-condition elevation as automatic.",
      "Clear condition differentiation is the opposite of an undifferentiated pattern.",
    ],
  ),
  authored3(
    3308,
    "F",
    "Demand-condition rates of aggression are high when tasks are presented and aggression produces a break; rates are low in play and attention. Medical screening is clear. Which treatment direction is MOST indicated by the FA?",
    "D",
    [
      "Noncontingent dense attention as the primary functional treatment",
      "Response interruption and redirection for automatic sensory biting only",
      "Ignore all aggression everywhere because it is maintained by attention",
      "Escape extinction / demand fading with a functionally matched break mand",
    ],
    [
      "Attention NCR matches attention functions, not the escape differentiation shown.",
      "Automatic treatments target alone-condition patterns; this FA implicates escape.",
      "The FA indicates escape, not attention, as the primary reinforcer.",
      "Escape-maintained aggression is addressed by withholding escape for aggression and teaching a break request with careful demand management.",
    ],
  ),
  authored3(
    3309,
    "F",
    "A tangible FA condition delivers a brief preferred item contingent on problem behavior after deprivation; control conditions do not. Problem behavior is differentially elevated only in tangible. What maintaining contingency is indicated?",
    "A",
    [
      "Social positive reinforcement via contingent access to preferred items/activities",
      "Automatic reinforcement identical to an alone-condition pattern",
      "Escape from instructional demands as the sole reinforcer",
      "Rule-governed compliance with tangible delivery instructions",
    ],
    [
      "Contingent item access elevating problem behavior defines a tangible/social positive function.",
      "Alone-condition elevation would support automatic reinforcement.",
      "Escape elevation would appear in demand tests.",
      "FA differentiation reflects contingency control, not rule compliance about the assessment.",
    ],
  ),
  authored3(
    3310,
    "F",
    "Across repeated FA sessions, problem behavior is comparably elevated in attention, escape, and tangible, and remains elevated in play. Alone rates are also high. What interpretation and next step are MOST appropriate?",
    "C",
    [
      "Clear attention function only; write an attention BIP immediately",
      "Conclude the behavior has no function and discontinue assessment",
      "Undifferentiated / multiply controlled or automatic patterns possible; refine with extended alone, pairwise tests, or modified analyses before treatment",
      "Average all conditions into a single “moderate” function score",
    ],
    [
      "Comparable elevation across social tests is not a clear single attention function.",
      "Undifferentiation calls for refined analysis, not abandonment of functional thinking.",
      "Lack of clear differentiation warrants methodological refinements to isolate maintaining variables.",
      "Averaging condition rates is not a substitute for experimental isolation of function.",
    ],
  ),
  authored3(
    3311,
    "F",
    "Caregivers complete rating scales suggesting escape; ABC data are inconclusive; a full multielement FA is declined due to safety and setting constraints. The BCBA runs brief contingency probes and a trial-based FA in the classroom. Which statement BEST justifies this approach?",
    "B",
    [
      "Indirect scales alone are always sufficient when time is limited",
      "When a standard FA is not feasible, structured experimental alternatives can still test hypothesized contingencies more rigorously than interviews alone",
      "Trial-based FA replaces the need for any operational definitions",
      "Brief probes are identical in strength to extended alone-condition analyses in every case",
    ],
    [
      "Indirect tools remain weaker than experimental tests when those tests can be done safely.",
      "Brief/trial-based FA methods are designed for constrained contexts while still manipulating contingencies.",
      "All FA variants still require clear definitions and measurement.",
      "Brief methods are useful but not universally equivalent to extended analyses in all cases.",
    ],
  ),
  authored3(
    3312,
    "F",
    "A competing-stimulus assessment identifies items that, when freely available, are associated with the lowest rates of automatically maintained hand-mouthing. How should these results MOST directly inform intervention?",
    "D",
    [
      "Use the lowest-competition items as contingent reinforcers for mouthing",
      "Interpret the assessment as a standard MSWO preference hierarchy only",
      "Conclude mouthing is attention-maintained because items were present",
      "Prioritize continuous or dense access to high-competition stimuli that displace mouthing as part of treatment",
    ],
    [
      "Competing stimuli are selected to compete with/displace the automatic response, not reinforce it.",
      "CSA evaluates competition with problem behavior, not merely preference ranking.",
      "Item presence during CSA does not redefine an automatic function as attention.",
      "Stimuli that suppress automatic behavior via competition are candidates for enriched environments/NCR components.",
    ],
  ),
  authored3(
    3313,
    "F",
    "A progressive-ratio reinforcer assessment increases response requirements until breaking points are reached for three preferred snacks. Snack A yields the highest breakpoint. What does that finding MOST directly indicate?",
    "A",
    [
      "Under escalating work requirements, Snack A sustained more responding—suggesting relatively greater reinforcer efficacy in that context",
      "Snack A is automatically reinforcing problem behavior",
      "Preference assessment ranks are invalid whenever PR is used",
      "Snack A must be delivered on an FT schedule to function",
    ],
    [
      "Higher breakpoints indicate the consequence supported more responding as price increased—relative efficacy.",
      "PR tests reinforcer value for a task response; it does not assign problem-behavior function.",
      "PR complements preference data; it does not void preference methods.",
      "Efficacy under PR does not require FT delivery in intervention.",
    ],
  ),
  authored3(
    3314,
    "F",
    "Single-stimulus preference presentations show approach to nearly every item, yielding a flat hierarchy. Paired-stimulus testing later differentiates clear high- and low-preference items. What BEST explains the improvement?",
    "C",
    [
      "Single-stimulus methods always measure reinforcer efficacy directly",
      "Approach to all items proves absence of preferences",
      "Forced-choice comparisons can reveal relative preference when absolute approach is indiscriminately high",
      "Paired-stimulus assessments eliminate all position bias by definition",
    ],
    [
      "Approach in single-stimulus formats indexes preference likelihood, not contingent efficacy.",
      "Ceiling approach often means poor differentiation, not true indifference.",
      "Choice between two items can rank relative preference when yes/no approach saturates.",
      "Position bias remains a risk in paired-stimulus formats and must be controlled.",
    ],
  ),
  authored3(
    3315,
    "F",
    "A latency-based FA records time from condition onset to the first instance of problem behavior rather than session rates. Escape trials show very short latencies; play trials show long latencies or none. What is the MOST appropriate interpretation?",
    "B",
    [
      "Latency measures cannot inform function under any conditions",
      "Shorter latencies in escape versus play support an escape function similarly to rate-based differentiation",
      "Long latencies in play prove attention maintenance",
      "Latency-based FA is identical to preference assessment breakpoints",
    ],
    [
      "Latency-based FA is an established variation for differentiating conditions.",
      "Differentially short latency to problem behavior in a test condition supports that contingency, analogous to rate elevation.",
      "Play latencies speak to control, not attention function.",
      "Breakpoints concern reinforcer assessment under progressive ratios, not FA latency.",
    ],
  ),
  authored3(
    3316,
    "F",
    "Precursor behaviors reliably precede dangerous aggression. The team reinforces precursors in test conditions and terminates sessions at precursors rather than allowing full aggression. Differentiation still emerges across conditions. What is the PRIMARY advantage of this approach?",
    "D",
    [
      "It converts all functions to automatic reinforcement",
      "It eliminates the need for operational definitions of aggression",
      "It proves precursors are unrelated to aggression’s function",
      "It can identify maintaining contingencies while reducing exposure to severe aggression",
    ],
    [
      "Precursor FA still tests social and automatic contingencies; it does not redefine functions as automatic.",
      "Clear definitions of precursors and severe behavior remain essential.",
      "Using precursors assumes a relation useful for safer testing, not unrelatedness.",
      "Precursor analyses aim to map function with less risk when severe topographies are dangerous.",
    ],
  ),
  authored3(
    3317,
    "F",
    "Open-ended interviews and record review generate a hypothesis that loud peer noise establishes escape as valuable and that aggression produces removal from the cafeteria. Which assessment step BEST tests that hypothesis experimentally?",
    "A",
    [
      "Manipulate noise/demand and escape contingencies in controlled FA or structural/functional tests matched to the hypothesized variables",
      "Stop assessment and write a BIP based only on the interview narrative",
      "Conduct an MSWO of cafeteria foods exclusively",
      "Compute total count IOA on aggression without testing contingencies",
    ],
    [
      "Hypothesis-driven experimental tests evaluate whether the suspected variables functionally control behavior.",
      "Interviews alone are weaker than contingency tests when tests are feasible and safe.",
      "Food preference does not test the escape-from-noise hypothesis.",
      "IOA evaluates measurement agreement, not functional control.",
    ],
  ),
  authored3(
    3318,
    "F",
    "A free-operant preference assessment presents all leisure items simultaneously for 5 minutes without removing items after engagement and ranks by percent of intervals interacted. Which description is MOST accurate?",
    "C",
    [
      "MSWO with replacement after each selection",
      "Paired-stimulus forced choice across all dyads",
      "Free-operant preference assessment with unrestricted concurrent access",
      "Progressive-ratio breakpoint assessment",
    ],
    [
      "MSWO removes selected items and re-presents remainders in discrete trials.",
      "Paired-stimulus presents two items per trial, not free group access.",
      "Unrestricted concurrent access timed for engagement is free-operant preference assessment.",
      "PR assessments manipulate schedule requirements to test reinforcer efficacy.",
    ],
  ),
  authored3(
    3319,
    "F",
    "Descriptive ABC data show aggression often preceded by demands and followed by breaks, but the same pattern sometimes occurs with attention. The BCBA notes that correlation in the natural environment cannot isolate which consequence is necessary. What limitation is being highlighted?",
    "B",
    [
      "ABC data are useless and should never be collected",
      "Descriptive assessment can suggest correlations but confounds prevent definitive functional isolation without experimental manipulation",
      "Only preference assessments can identify escape functions",
      "IOA cannot be collected during ABC recording",
    ],
    [
      "ABC data remain useful for hypothesis generation despite limitations.",
      "Naturalistic correlations are vulnerable to confounds; FA/experimental tests isolate contingencies.",
      "Escape functions are identified via functional analysis contingencies, not preference hierarchies.",
      "IOA can and should be collected on ABC codes when feasible.",
    ],
  ),
  authored3(
    3320,
    "F",
    "A concurrent-operant reinforcer assessment offers two tasks: Task A produces Cartoon X and Task B produces Cartoon Y on equal schedules. The learner allocates almost all responding to Task A. What does this MOST directly show?",
    "D",
    [
      "Cartoon Y is a conditioned punisher",
      "Problem behavior’s FA function is attention",
      "Preference ranks from MSWO are invalid",
      "Relative reinforcer efficacy under concurrent choice: Cartoon X supports more responding than Cartoon Y",
    ],
    [
      "Low allocation does not define punishment; Y may simply be less effective.",
      "Reinforcer assessment for task allocation does not determine problem-behavior function.",
      "Concurrent-operant results complement preference data rather than void them.",
      "Differential allocation under equal schedules indexes relative reinforcing efficacy.",
    ],
  ),
  authored3(
    3321,
    "F",
    "Skill-based assessment shows a learner can echo words and tact common items but rarely mands under deprivation when items are present. Which programming implication is MOST precise?",
    "A",
    [
      "Teach mands under appropriate EOs with specific reinforcement rather than assuming tact/echoic skills will transfer automatically",
      "Discontinue all verbal training because echoics prove mands exist",
      "Treat the deficit as an FA-indicated escape function of problem behavior",
      "Use only free-operant preference assessment to teach mands",
    ],
    [
      "Verbal operants are functionally independent; mands require EO control and specific reinforcement.",
      "Echoics do not guarantee mand function under motivation.",
      "The vignette is a skill/verbal assessment finding, not a problem-behavior FA result.",
      "Preference assessment identifies reinforcers; it does not by itself establish mand stimulus control.",
    ],
  ),
  authored3(
    3322,
    "F",
    "A synthesized contingency interview suggests problem behavior is maintained by escape to tangibles (break plus preferred items). A subsequent IISCA-style test of that combined contingency shows clear differentiation from control. Which statement is MOST accurate?",
    "C",
    [
      "Synthesized tests are identical to standard alone-condition automatic analyses",
      "Differentiation under a synthesized contingency proves each component would maintain behavior in isolation",
      "Synthesized analyses can identify ecologically relevant combined contingencies but may not isolate each reinforcer’s independent contribution",
      "Interview synthesis alone is stronger evidence than any differentiated test",
    ],
    [
      "Synthesized social contingencies differ from alone tests of automatic reinforcement.",
      "Combined-contingency effects do not automatically partition unique control by each element.",
      "IISCA/synthesized approaches prioritize ecological combinations; component isolation may require further analyses.",
      "Experimental differentiation outweighs interview narrative alone.",
    ],
  ),
  authored3(
    3323,
    "F",
    "Before any FA, a BCBA reviews incident reports, medical notes, and prior plans, then conducts structured caregiver and teacher interviews to identify contexts, precursors, and hypothesized reinforcers. What BEST names this phase?",
    "B",
    [
      "Experimental functional analysis multielement testing",
      "Indirect / preliminary assessment informing hypotheses for descriptive or experimental analysis",
      "MSWO preference ranking of interview topics",
      "Treatment integrity measurement of the future BIP",
    ],
    [
      "No contingency manipulation has occurred yet; that defines later experimental FA.",
      "Record review and interviews are indirect methods used to shape testable hypotheses.",
      "MSWO ranks stimuli, not interview content.",
      "Integrity measurement occurs during/after intervention implementation.",
    ],
  ),
  authored3(
    3324,
    "F",
    "After FA indicates attention, the team implements noncontingent attention and teaches a functional communication response for attention. Aggression drops in clinic but caregivers report no change at home where attention remains contingent on aggression. What assessment/implementation implication is MOST critical?",
    "A",
    [
      "Generalization and treatment integrity across settings must be assessed; clinic gains do not guarantee home contingency change",
      "The original FA must have been wrong because home rates did not change",
      "Social validity ratings replace the need for home data",
      "Preference assessments should replace functional communication training",
    ],
    [
      "If home contingencies still reinforce aggression, clinic effects may not transfer—assess and align implementation across settings.",
      "Home persistence under unchanged contingencies does not invalidate a clear clinic FA.",
      "Social validity matters but does not substitute for measuring home behavior and integrity.",
      "Preference assessment does not address attention-maintained aggression treatment transfer.",
    ],
  ),
];
