/**
 * Mock Exam 3 — authored items, Domains E (Ethics) and G (Behavior-change procedures).
 * Independent study only. Not affiliated with the BACB.
 */
import type { BDSQuestion } from "@/lib/content-types";
import { authored3 } from "@/content/mockExam/exams/bcbaPractice3/authoredHelper";

export const EXPANDED3_E: BDSQuestion[] = [
  authored3(
    3401,
    "E",
    "A BCBA's neighbor asks for informal advice about a preschooler who bites peers. Over coffee, the BCBA sketches a full escape-extinction and DRA plan, texts measurement sheets, and tells the neighbor to 'just start tomorrow' without assessment, consent documentation, or any professional service agreement. Which action BEST corrects the ethical problem?",
    "A",
    [
      "Stop providing informal clinical direction outside a defined professional relationship; explain limits, offer appropriate referral pathways, and do not design or supervise interventions without assessment, consent, and organizational accountability.",
      "Continue coaching because neighborhood goodwill never creates a client relationship.",
      "Charge a cash fee under the table so the advice becomes an official case without records.",
      "Have the neighbor post the BCBA's plan in a parent Facebook group for crowd feedback.",
    ],
    [
      "Providing behavior-analytic recommendations that function as treatment creates professional obligations; informal 'advice' still requires competence, consent, and clear role boundaries.",
      "Clinical direction about restrictive procedures can establish a de facto relationship with duties of care.",
      "Cash-only undocumented services worsen integrity and accountability problems.",
      "Public posting adds confidentiality and misapplication risks.",
    ],
  ),
  authored3(
    3402,
    "E",
    "During a multidisciplinary staffing, a speech-language pathologist recommends a communication approach outside the BCBA's training. The BCBA publicly ridicules the recommendation as 'pseudoscience,' tells the team to ignore the SLP, and later emails families that only ABA opinions matter. Collaboration has collapsed. What should the BCBA do?",
    "B",
    [
      "Double down publicly so families do not 'get confused by other disciplines.'",
      "Repair the interaction: communicate respectfully within competence, collaborate or coordinate care, and present interdisciplinary differences honestly without disparaging colleagues or overclaiming exclusive authority.",
      "File a licensing complaint against the SLP solely for disagreeing in a meeting.",
      "Remove all communication goals from the behavior plan to avoid overlap.",
    ],
    [
      "Dismissiveness and turf wars harm clients and violate expectations for respectful collaboration.",
      "Ethics emphasize professional respect, accurate representation of scope, and client-centered interdisciplinary coordination.",
      "Disagreement alone is not grounds for retaliatory complaints.",
      "Dropping needed goals to avoid collaboration neglects client welfare.",
    ],
  ),
  authored3(
    3403,
    "E",
    "A clinic's marketing flyer, drafted for the BCBA's signature, claims the BCBA is a 'Board-certified pediatric neurologist collaborator' and promises 'insurance-proof cure of autism symptoms in 90 days.' The BCBA holds only BCBA certification and has no medical license. Which public-statement response is MOST ethical?",
    "C",
    [
      "Sign the flyer because marketing exaggeration is industry standard.",
      "Keep the cure promise but swap 'neurologist' for 'neuro-informed coach.'",
      "Refuse false credentials and outcome guarantees; authorize only truthful, nonmisleading statements about qualifications and services.",
      "Post the flyer only on encrypted staff channels so outsiders never see it.",
    ],
    [
      "Industry norms do not authorize misrepresentation.",
      "Softening one falsehood while retaining a cure guarantee still misleads.",
      "Public communications must accurately reflect credentials and avoid unwarranted guarantees.",
      "Internal circulation of false claims still endorses dishonesty and can leak.",
    ],
  ),
  authored3(
    3404,
    "E",
    "A graduate student asks to use identifiable session videos from the BCBA's current caseload for a thesis defense open to the public campus community. Guardians signed only a clinic media release for internal staff training years earlier. The student offers co-authorship if the BCBA skips a new consent process. What should the BCBA do?",
    "D",
    [
      "Provide the raw videos immediately to support student progress.",
      "Blur faces after the public defense if anyone objects.",
      "Trade co-authorship for reuse of old releases without re-consent.",
      "Decline use under the old release; require current, specific informed consent for the new purpose and audience, with de-identification or refusal if guardians decline.",
    ],
    [
      "Prior internal-training consent does not authorize public academic presentation of identifiable media.",
      "Consent must precede disclosure, not follow complaints.",
      "Authorship incentives do not waive consent duties.",
      "Purpose-specific, current consent and minimization of identifiable disclosure protect confidentiality.",
    ],
  ),
  authored3(
    3405,
    "E",
    "An RBT on the BCBA's team reports that another BCBA supervisor repeatedly makes sexual comments, blocks career opportunities after rejection, and warns that reporting will 'end your hours.' The reporting RBT asks the caseload BCBA for help and fears retaliation. What is the MOST appropriate next step for the caseload BCBA?",
    "A",
    [
      "Take the report seriously: support the RBT in using organizational and, as applicable, external complaint channels; avoid retaliatory involvement; document facts; and do not minimize or bury the allegation to protect billing.",
      "Tell the RBT that sexual harassment among BCBAs is 'a personality clash' and to ignore it.",
      "Move the RBT to unpaid observation only until the accused BCBA retires.",
      "Confront the accused BCBA in a crowded break room with client names attached to examples.",
    ],
    [
      "Harassment and retaliation threats require responsible reporting support and protection of supervisees/staff welfare.",
      "Minimizing harassment abandons a duty to address harmful workplace conduct affecting service quality and people.",
      "Punitive unpaid status can itself be retaliatory and does not address the allegation.",
      "Public confrontation with client details risks confidentiality and unsafe escalation.",
    ],
  ),
  authored3(
    3406,
    "E",
    "A family facing temporary nonpayment still needs medically necessary behavior services. Leadership tells the BCBA to stop all contact immediately, refuse crisis-protocol handoff, and withhold the behavior plan from the new provider 'until the balance is cleared.' Progress notes are paid through last week. What should the BCBA prioritize?",
    "B",
    [
      "Follow the stop-contact order exactly and ignore transition needs.",
      "Avoid abandonment: provide clinically appropriate notice, transition/crisis information, and necessary records to an authorized new provider consistent with law and policy, while billing disputes are handled through proper administrative channels—not by withholding safety-critical continuity.",
      "Delete the behavior plan so the debt creates leverage.",
      "Continue unlimited free services indefinitely without documenting the coverage change.",
    ],
    [
      "Abrupt cessation without transition can constitute abandonment.",
      "Client welfare requires reasonable continuity steps and lawful record transfer even when payment conflicts exist.",
      "Destroying or withholding clinical essentials as leverage is unethical.",
      "Lack of documentation about service changes creates new integrity problems.",
    ],
  ),
  authored3(
    3407,
    "E",
    "A BCBA fluent only in English serves a family that communicates primarily in another language. Leadership says using the client's 10-year-old sibling as interpreter 'saves money.' Complex consent for a restrictive procedure is needed today. Which approach BEST meets ethical communication duties?",
    "C",
    [
      "Proceed with the sibling interpreter for all consent discussions.",
      "Skip interpreter services and have guardians initial English forms they cannot read.",
      "Arrange qualified interpretation appropriate to the decision, ensure guardians understand risks/benefits/alternatives, and document how comprehension was supported—do not rely on a minor sibling for complex clinical consent.",
      "Delay forever without interim safety planning because interpretation logistics are inconvenient.",
    ],
    [
      "Minor siblings are inappropriate for complex consent interpretation and create coercion/confidentiality risks.",
      "Unread signatures do not constitute informed consent.",
      "Meaningful informed consent requires comprehensible communication, typically via qualified interpretation—not child interpreters.",
      "Inconvenience does not justify neglecting both consent and safety planning.",
    ],
  ),
  authored3(
    3408,
    "E",
    "After a night of heavy drinking, a BCBA arrives for a morning school consultation with slurred speech and impaired judgment. An RBT offers to 'run the meeting while you nap in the car' and still bill BCBA protocol-modification time. What should the BCBA do?",
    "D",
    [
      "Lead the meeting anyway to avoid canceling billable services.",
      "Sleep in the car while the RBT bills under the BCBA's credentials.",
      "Drink coffee in the parking lot and pretend the impairment is allergies.",
      "Remove oneself from service delivery while impaired, arrange safe coverage or rescheduling, and do not bill for competent BCBA services not actually rendered.",
    ],
    [
      "Impaired practice endangers clients and violates competence/responsibility standards.",
      "Credential substitution and false billing compound the ethical breach.",
      "Masking impairment does not restore fitness for duty.",
      "Stepping back while impaired and ensuring honest coverage/billing protect clients and integrity.",
    ],
  ),
  authored3(
    3409,
    "E",
    "A BCBA discovers that clinic staff share a single EHR login 'for speed,' including the BCBA's credentials, so RBTs can enter notes under the BCBA's name after hours. Leadership calls it efficient teamwork. Which response BEST protects documentation integrity and confidentiality?",
    "B",
    [
      "Keep shared logins and add a sticky note with the password on the monitor.",
      "Stop credential sharing, require unique authenticated access, correct misattributed entries through proper amendment procedures, and escalate the compliance failure.",
      "Share the login only with senior RBTs who promise not to tell auditors.",
      "Export all charts to a personal USB drive so the BCBA can 'watch the data.'",
    ],
    [
      "Password stickies increase unauthorized access risk.",
      "Unique credentials, accurate authorship, and compliance escalation are required for record integrity and PHI protection.",
      "Selective sharing still falsifies identity and audit trails.",
      "Unsecured personal exports create additional confidentiality violations.",
    ],
  ),
  authored3(
    3410,
    "E",
    "A city council candidate asks the BCBA to speak at a fundraiser using a current client's first name, school, and aggression graphs to illustrate 'what my ABA agenda will fix,' offering campaign-committee payment. Guardians have not consented to political use of PHI. What should the BCBA do?",
    "C",
    [
      "Present the identifiable case because elections are a public service.",
      "Accept payment and anonymize only the last name while showing the school logo.",
      "Decline identifiable or paid political use of client information; protect confidentiality and avoid exploiting the professional relationship for campaign advantage without proper authorization—and generally avoid such use even then when it risks harm or coercion.",
      "Hand the raw graphs to the campaign manager to present without the BCBA present.",
    ],
    [
      "Political utility does not override confidentiality.",
      "Partial de-identification that still identifies the child is insufficient.",
      "Client data must not be leveraged for political fundraising without strict ethical/legal authorization; declining protects confidentiality and avoids exploitation.",
      "Proxy presentation still discloses protected information.",
    ],
  ),
  authored3(
    3411,
    "E",
    "Parents give the BCBA an expensive smartwatch 'to thank you for the authorization letter' that increased weekly hours. The letter was clinically justified, but the gift arrives the same week as a pending reassessment that could change hours again. Agency policy caps gifts at a nominal amount. Which handling is BEST?",
    "D",
    [
      "Accept the watch quietly and increase hours further to show gratitude.",
      "Accept it if the family agrees not to tell the agency.",
      "Auction the watch among staff and keep proceeds without disclosure.",
      "Decline or return the gift inconsistent with policy/conflict rules; document the offer; keep clinical recommendations independent of personal benefit.",
    ],
    [
      "Gifts timed to clinical advocacy can impair objectivity even when prior recommendations were sound.",
      "Secrecy intensifies conflict-of-interest concerns.",
      "Redistributing an improper gift does not erase the conflict.",
      "Declining/returning, documenting, and preserving independence align with ethical gift and conflict standards.",
    ],
  ),
  authored3(
    3412,
    "E",
    "A BCBA's caseload and unpaid supervisory assignments exceed what can be monitored with meaningful observation, feedback, and protocol oversight. Multiple RBTs have gone weeks without contacts. Leadership still assigns two more complex cases. What should the BCBA do FIRST?",
    "A",
    [
      "Refuse or renegotiate assignments that exceed safe supervisory capacity; document concerns; protect existing clients by restoring adequate supervision before accepting additional high-risk responsibility.",
      "Accept all cases and hope weekly email check-ins count as observation.",
      "Sign supervision logs in advance for the month to satisfy audits.",
      "Delegate all clinical decision-making permanently to the newest RBT.",
    ],
    [
      "Ethics require supervisory volume compatible with competent oversight; overextension without correction harms clients.",
      "Email alone often fails to meet meaningful supervision needs for protocol integrity.",
      "Prospective false logging is falsification.",
      "Unqualified delegation abandons supervisory responsibility.",
    ],
  ),
  authored3(
    3413,
    "E",
    "A behavior plan includes a restrictive manual restraint procedure approved only for imminent severe self-injury. Staff begin using it for loud vocal stereotypy in the hallway because it 'works faster than redirection.' Guardians were never told about this expanded use. The BCBA learns during a graph review. What is the BEST immediate ethical response?",
    "B",
    [
      "Praise staff efficiency and expand restraint criteria in the plan quietly.",
      "Stop unauthorized expansion of restraint, retrain to approved conditions, notify guardians/appropriate parties, document, and review less restrictive alternatives and consent parameters.",
      "Add restraint for stereotypy retroactively in yesterday's notes.",
      "Tell staff to restrain only when cameras are off.",
    ],
    [
      "Speed of suppression does not justify unconsented expansion of restrictive procedures.",
      "Restrictive procedures require fidelity to authorized conditions, transparency, and least-restrictive practice.",
      "Retroactive falsification of authorization is dishonest.",
      "Covert restraint worsens ethical and safety violations.",
    ],
  ),
  authored3(
    3414,
    "E",
    "An operations manager instructs the BCBA to bill a full delivered session for a date when the family canceled before any clinical contact occurred, saying 'the slot was held.' No make-up service happened. Which billing decision is MOST ethical?",
    "C",
    [
      "Bill as delivered to protect revenue targets.",
      "Bill half units with a fabricated progress note.",
      "Bill only services actually rendered under accurate codes and documentation; refuse to represent cancellations as delivered treatment.",
      "Bill under a sibling's authorization number to use unused units.",
    ],
    [
      "Held slots are not automatically delivered clinical services.",
      "Partial false billing with fabricated notes remains misrepresentation.",
      "Accurate billing and documentation of what occurred are required.",
      "Using another client's authorization is fraudulent.",
    ],
  ),
  authored3(
    3415,
    "E",
    "A BCBA moonlights for a second agency that directly competes for the same school contract. Without disclosure, the BCBA steers the school to drop Agency A mid-year and hire Agency B, where the BCBA will gain a promotion and bonus. Families experience abrupt therapist changes. Which course BEST addresses the conflict?",
    "D",
    [
      "Continue steering because dual employment is always allowed without disclosure.",
      "Disclose only after the contract switches.",
      "Offer families gift cards funded by Agency B to ease the transition optics.",
      "Disclose conflicts, remove self-dealing influence from procurement decisions, and prioritize client continuity and honest recommendations over personal advancement.",
    ],
    [
      "Undisclosed competing interests that steer institutional decisions are unethical.",
      "Late disclosure after harm does not cure the conflicted process.",
      "Bribe-like gifts do not fix conflicted steering.",
      "Transparency, recusal from conflicted influence, and client-centered continuity are required.",
    ],
  ),
  authored3(
    3416,
    "E",
    "A fieldwork trainee supervised by the BCBA begins a romantic relationship with an RBT assigned to the same learner. Confidential case details are discussed on dates, and objectivity in feedback is visibly impaired. The trainee asks the BCBA to 'just not write it down.' What should the BCBA do?",
    "A",
    [
      "Address the multiple relationship: reassign roles as needed to protect the client and evaluation integrity, set clear professional boundaries, document appropriately, and refuse to conceal conflicts that affect services.",
      "Ignore the relationship if session times stay filled.",
      "Promote the trainee immediately so evaluative authority disappears on paper only.",
      "Require the couple to share one login and co-author all notes.",
    ],
    [
      "Romantic multiple relationships within a supervisory/service team can impair objectivity and confidentiality and must be managed, not hidden.",
      "Filled hours do not erase conflict and confidentiality risk.",
      "Paper promotions without resolving the conflict are cosmetic.",
      "Shared credentials worsen integrity problems.",
    ],
  ),
  authored3(
    3417,
    "E",
    "Online, a competing BCBA posts inaccurate claims that the clinic 'fabricates IOA.' The caseload BCBA wants to reply with screenshots of a specific child's graphs and family emails to 'prove them wrong' in a public thread. Which response BEST balances honesty and confidentiality?",
    "C",
    [
      "Post the child's graphs and emails publicly for transparency.",
      "Post the family's home address so commenters can 'verify independently.'",
      "Do not disclose client PHI in public disputes; correct falsehoods only with nonidentifying, truthful information through appropriate channels, and pursue professional complaint processes if warranted.",
      "Hire bots to flood the competitor's profile with insults.",
    ],
    [
      "Public PHI dumps are confidentiality breaches even when motivated by reputation defense.",
      "Sharing addresses escalates harm.",
      "Defending professional reputation must not violate client confidentiality; use proper channels and nonidentifying facts.",
      "Harassment campaigns are unprofessional and unethical.",
    ],
  ),
  authored3(
    3418,
    "E",
    "After an emergency hold used during dangerous self-injury at school, leadership tells the BCBA not to notify guardians because 'it will create paperwork.' District policy and the consent packet require prompt guardian notification of crisis procedures. The learner is currently safe. What should the BCBA do?",
    "D",
    [
      "Omit the event from all records to reduce paperwork.",
      "Notify only if guardians ask a direct question next month.",
      "Tell the RBT to decide alone whether anyone hears.",
      "Notify guardians per consent and policy, document the incident accurately, and refuse instructions to conceal crisis procedures from decision-makers.",
    ],
    [
      "Omitting crisis events falsifies the clinical record.",
      "Delayed notification only if asked violates agreed notification duties.",
      "Crisis communication is not an RBT-only discretion issue when the BCBA is responsible.",
      "Transparency with guardians and accurate documentation are required after restrictive emergency procedures.",
    ],
  ),
  authored3(
    3419,
    "E",
    "Guardians request copies of recent graphs and operational definitions used to justify a reduction in hours. The BCBA worries they will 'misread the data' and asks the office to stall indefinitely while still using those data with the payer. Which approach is MOST ethical?",
    "A",
    [
      "Provide access to records the guardians are entitled to receive, explain findings in understandable terms, and do not withhold clinical information to control a funding narrative.",
      "Stall until the authorization year ends, then claim the files were archived off-site forever.",
      "Release only weeks that look favorable and shred the rest.",
      "Charge an arbitrary 'interpretation fee' so high that the request is abandoned.",
    ],
    [
      "Clients/guardians generally have rights to relevant clinical information; explanatory support is appropriate, concealment is not.",
      "Indefinite stalling to manipulate payer processes is dishonest.",
      "Selective destruction/release falsifies the clinical picture.",
      "Fee barriers designed to block legitimate access are coercive.",
    ],
  ),
  authored3(
    3420,
    "E",
    "A startup offers the BCBA equity if the BCBA funnels currently served families to the startup's app-based parent training, including families who are progressing in the BCBA's existing caregiver-coaching protocol. Disclosure is discouraged 'until Series B.' What should the BCBA do?",
    "B",
    [
      "Quietly refer all families to maximize equity value.",
      "Refuse equity-tied steering of current clients; avoid undisclosed financial conflicts that bias recommendations; provide options only when clinically appropriate with transparent, noncoercive information.",
      "Refer only non-English-speaking families to reduce detection risk.",
      "Have an RBT make the referrals while the BCBA retains the shares.",
    ],
    [
      "Hidden equity incentives distort clinical recommendations.",
      "Client welfare and conflict disclosure/avoidance prohibit profit-driven steering of existing cases.",
      "Targeting a language group for concealment is discriminatory and still conflicted.",
      "Using a supervisee as a front does not remove the BCBA's conflict.",
    ],
  ),
  authored3(
    3421,
    "E",
    "A court order lawfully requires limited disclosure of specific session dates and attendance for a custody matter. Separately, one parent verbally demands the BCBA email the entire psychotherapy notes of a sibling treated by another provider that were misfiled in the chart. Which disclosure plan is MOST appropriate?",
    "C",
    [
      "Email the entire chart, including the sibling's notes, to both parents and the judge's personal email.",
      "Ignore the court order because ABA ethics always override law.",
      "Comply with the lawful court order's scope through proper channels; do not expand disclosure to unrelated third-party records beyond authorization; seek guidance when scope is unclear.",
      "Post a summary of the custody dispute on the clinic blog for transparency.",
    ],
    [
      "Over-disclosure of third-party sensitive records and insecure transmission violate confidentiality.",
      "Legal obligations cannot be dismissed with a blanket ethics override narrative.",
      "Minimum necessary compliance with lawful process, without unauthorized expansion, balances legal and ethical duties.",
      "Public blogging of custody matters breaches confidentiality.",
    ],
  ),
  authored3(
    3422,
    "E",
    "A caregiver asks the BCBA how to crush and hide prescription sedatives in a learner's food 'so school days are easier,' and wants this written into the ABA plan without medical involvement. The BCBA is not a prescribing clinician. What is the MOST ethical response?",
    "D",
    [
      "Write covert medication administration into the behavior plan as a 'setting event strategy.'",
      "Provide dosing advice based on internet forums.",
      "Agree if the caregiver promises not to tell the physician.",
      "Refuse to design or endorse covert medication practices outside medical authority; redirect to appropriate medical professionals; document the request and maintain boundaries of competence.",
    ],
    [
      "Covert medication in an ABA plan exceeds competence and can be dangerous.",
      "Internet-based dosing advice is outside BCBA scope and unsafe.",
      "Secrecy from physicians intensifies harm risk.",
      "Scope limits require refusal of medical practice and appropriate redirection.",
    ],
  ),
  authored3(
    3423,
    "E",
    "A BCBA realizes a preferred assessment protocol systematically under-identifies skill needs for clients from a cultural community represented on the caseload. Leadership likes the protocol because it yields shorter authorizations. Families have not been told about the limitation. What should the BCBA do?",
    "A",
    [
      "Disclose assessment limitations, select or adapt culturally responsive and clinically adequate assessment practices, and refuse to prioritize authorization length over accurate identification of client needs.",
      "Keep using the weak protocol exclusively to preserve short authorizations.",
      "Tell only families who complain in writing.",
      "Alter raw scores upward secretly so graphs look fair without changing methods.",
    ],
    [
      "Ethical assessment requires tools and processes suited to the client; hiding limitations and under-identifying needs for funding optics is unethical.",
      "Authorization convenience does not justify inadequate assessment.",
      "Selective disclosure still leaves many clients harmed.",
      "Secret score alteration is data falsification.",
    ],
  ),
  authored3(
    3424,
    "E",
    "While reviewing a trainee's portfolio, the BCBA finds fabricated client initials and invented IOA percentages used to meet a documentation checklist. The trainee says everyone pads portfolios and asks for a passing supervisory signature today. Which action BEST upholds ethics in training and documentation?",
    "B",
    [
      "Sign off immediately to keep the trainee on payroll.",
      "Refuse to endorse fabricated documentation, require correction with truthful materials, document the integrity issue, and follow organizational/training-program reporting requirements.",
      "Replace the invented initials with real client names to make the portfolio 'more authentic.'",
      "Post the trainee's portfolio fraud on social media as a teaching example.",
    ],
    [
      "Supervisory endorsement of known fabrication is itself an integrity violation.",
      "Accurate training records and reporting of falsification protect future clients and the profession.",
      "Substituting real names without authorization can breach confidentiality and still rests on a false IOA framework.",
      "Public shaming is not an appropriate professional reporting pathway and may create new harms.",
    ],
  ),
];

export const EXPANDED3_G: BDSQuestion[] = [
  authored3(
    3501,
    "G",
    "Handwashing is task-analyzed into six steps. The instructor completes all steps except the final towel dry, prompts and reinforces independent towel drying to mastery, then works backward so the learner performs the last two steps, then the last three, until the full chain is independent. Which chaining method is PRIMARY?",
    "C",
    [
      "Forward chaining starting at soap dispensing only.",
      "Total-task presentation with no link-by-link mastery criterion.",
      "Backward chaining, teaching the terminal link first and progressively adding preceding links.",
      "Lag reinforcement for novel towel-fold topographies.",
    ],
    [
      "The vignette starts at the end of the chain, not the first link.",
      "Total-task would have the learner attempt the whole chain each trial without the described upstream build.",
      "Establishing the final link first and adding earlier links is backward chaining.",
      "Lag schedules target variability, not chain-link sequence teaching.",
    ],
  ),
  authored3(
    3502,
    "G",
    "A learner initially only approximates a two-word mand ('uh buh'). Across sessions, the BCBA differentially reinforces closer forms—first any voiced request, then clearer vowels, then full 'want book'—while placing earlier approximations on extinction. Independent 'want book' emerges. Which procedure is PRIMARY?",
    "A",
    [
      "Shaping by successive approximations toward the terminal mand topography.",
      "Exclusionary time-out for each unclear approximation.",
      "Noncontingent delivery of books on a fixed-time schedule only.",
      "Interdependent group contingency for the reading circle.",
    ],
    [
      "Differentially reinforcing progressive approximations while extinguishing earlier forms is shaping.",
      "Time-out is not the mechanism described.",
      "NCR alone does not differentially shape topography.",
      "No group payoff structure is described.",
    ],
  ),
  authored3(
    3503,
    "G",
    "Attention-maintained yelling decreases when staff withhold attention for yelling and immediately provide brief social attention contingent on a taught hand-raise request, with prompting to ensure the alternative contacts reinforcement. Which differential reinforcement procedure is BEST named?",
    "D",
    [
      "DRL for yelling rate only, with attention freely available for yelling.",
      "DRH requiring faster yelling.",
      "Full physical restraint as the primary consequence for every yell.",
      "DRA/FCT: reinforcing a functionally equivalent alternative (hand raise) while extinguishing yelling.",
    ],
    [
      "DRL would reinforce lower rates of yelling itself, not an alternative mand.",
      "DRH would increase yelling rate.",
      "Restraint is not described and would be a restrictive add-on, not DRA.",
      "Reinforcing an alternative communicative response while extinguishing the problem behavior is DRA/FCT.",
    ],
  ),
  authored3(
    3504,
    "G",
    "For automatically maintained skin picking, the BCBA delivers a preferred edible if and only if a full 2-minute interval elapses with zero picking. Any pick resets the interval. No alternative pick-incompatible response is required. Which procedure matches this contingency?",
    "B",
    [
      "DRI requiring continuous fist clenching as the sole reinforcer contingency.",
      "Interval DRO resetting upon occurrence of skin picking.",
      "DRA reinforcing picking with edibles.",
      "Negative punishment via response cost of tokens for each edible.",
    ],
    [
      "No incompatible response requirement is described.",
      "Reinforcement for the absence of a target behavior across an interval, with reset on occurrence, is resetting interval DRO.",
      "Reinforcing picking would worsen the problem.",
      "The vignette specifies edible delivery for zero picking, not token fines.",
    ],
  ),
  authored3(
    3505,
    "G",
    "A learner's chair-tipping is incompatible with keeping four chair legs on the floor. The BCBA reinforces feet-flat/legs-down sitting with tokens and withholds tokens when tipping occurs. Chair tipping declines as stable sitting rises. Which procedure is PRIMARY?",
    "C",
    [
      "NCR delivering tokens every 30 seconds regardless of posture.",
      "Overcorrection requiring repeated tip-and-restore practice as first-line punishment.",
      "DRI: reinforcing a physically incompatible sitting topography.",
      "Lag schedule for novel tipping angles.",
    ],
    [
      "Tokens are contingent on incompatible posture, not time-based free delivery.",
      "No overcorrection contingency is described as primary.",
      "Reinforcing a response that cannot occur with tipping is DRI.",
      "Lag schedules would diversify tipping, opposite the goal.",
    ],
  ),
  authored3(
    3506,
    "G",
    "A teen's rapid question-asking (30+/hour) disrupts class but some questioning is appropriate. The BCBA reinforces asking only if rate stays at or below six per hour (spaced), and questions above the limit produce no teacher answer. Rate falls to criterion without eliminating questions. Which procedure is this?",
    "A",
    [
      "DRL to reduce—but not eliminate—question-asking to a lower acceptable rate.",
      "DRO requiring zero questions for the entire school day only.",
      "Escape extinction for all academic work.",
      "Forward chaining of a silence routine.",
    ],
    [
      "Differential reinforcement of low rates targets reduced frequency while allowing some occurrences.",
      "Full-day zero-question DRO would aim at elimination, not a low rate.",
      "Demand escape contingencies are not described.",
      "Chaining silence is not the rate contingency described.",
    ],
  ),
  authored3(
    3507,
    "G",
    "Escape-maintained worksheet refusal has been maintained by task removal. The team keeps the worksheet present until a minimum independent start occurs (escape extinction) while teaching and reinforcing a break card under limited, signaled conditions. Problem behavior spikes then declines as break-card use rises. Which package element is ESSENTIAL to the extinction component?",
    "D",
    [
      "Delivering escape contingent on every refusal as before.",
      "Removing all break teaching so only extinction remains forever.",
      "Punishing refusals with contingent exercise laps as the only change.",
      "Withholding the functional reinforcer (escape) following refusal while the demand context remains in place, typically paired with a reinforced alternative.",
    ],
    [
      "Continued escape contingent on refusal maintains the behavior.",
      "Extinction alone without a communicative alternative is often less desirable and is not the full package described.",
      "Exercise punishment is not the described essential extinction mechanism.",
      "Escape extinction means refusal no longer produces removal of the demand; DRA/FCT for breaks is commonly combined.",
    ],
  ),
  authored3(
    3508,
    "G",
    "Tangible-maintained grabbing decreases when preferred snacks are delivered on a dense fixed-time schedule independent of grabbing, while grabbing no longer produces snack access. Later, the schedule is thinned. Which antecedent/consequence approach is PRIMARY in the dense phase?",
    "B",
    [
      "Contingent shock paired with each grab.",
      "NCR (time-based reinforcer delivery) reducing the EO for grabbing, with extinction of the grabbing-snack contingency.",
      "DRH for faster grabbing.",
      "Dependent hero contingency for the whole grade.",
    ],
    [
      "No contingent aversive is described.",
      "Noncontingent, time-based access to the functional reinforcer is NCR; combining with extinction of grabbing is common.",
      "DRH would increase grabbing.",
      "No group hero payoff is described.",
    ],
  ),
  authored3(
    3509,
    "G",
    "After teaching matching spoken words to pictures and pictures to printed words with multiple exemplars, a learner spontaneously matches spoken words to printed words and sorts novel synonyms without direct teaching of those links. Which outcome BEST describes the derived performance?",
    "A",
    [
      "Stimulus equivalence / derived relational responding emerging from trained conditional discriminations.",
      "Respondent extinction of picture looking.",
      "Exclusionary time-out for matching errors only.",
      "Premack reinforcement using printed words as low-p behavior.",
    ],
    [
      "Untrained relations emerging from trained match-to-sample networks indicate equivalence/derived relations.",
      "Respondent extinction does not explain derived symbolic matching.",
      "Time-out is not the teaching mechanism described.",
      "Premack concerns activity contingencies, not derived matching.",
    ],
  ),
  authored3(
    3510,
    "G",
    "Toothbrushing is taught with an initial full physical prompt, then partial physical, then gesture, then independence, with mastery criteria at each level before fading. Errors are rare compared with a prior least-to-most approach. Which prompt hierarchy strategy is PRIMARY?",
    "C",
    [
      "Progressive time delay without changing prompt topography.",
      "Least-to-most beginning with independence only.",
      "Most-to-least prompting, starting with more intrusive prompts and fading to less intrusive forms.",
      "Simultaneous full physical prompting maintained permanently.",
    ],
    [
      "The vignette changes prompt topography intensity, not only delay.",
      "Least-to-most starts with less help, opposite the described sequence.",
      "Beginning with full physical and stepping down is most-to-least prompting.",
      "Permanent full prompting prevents independence.",
    ],
  ),
  authored3(
    3511,
    "G",
    "For a mastered listener-responding target that recently became prompt-dependent, the BCBA waits for independent responding first, then provides a gestural prompt only if needed, then light physical only if the gesture fails—escalating within the trial as required. Which approach matches this plan?",
    "B",
    [
      "Most-to-least starting with full physical on every trial.",
      "Least-to-most prompting, allowing independence before increasing prompt intrusiveness as needed.",
      "Stimulus fading of toothbrush color only.",
      "DRO for any listener response topography.",
    ],
    [
      "Full physical first is most-to-least, not the described order.",
      "Opportunity for independent responding before escalating prompts is least-to-most.",
      "Material fading is not described.",
      "DRO does not describe a prompt hierarchy.",
    ],
  ),
  authored3(
    3512,
    "G",
    "To teach discrimination of the letter B, materials begin with an exaggerated bold B versus a tiny distractor, then distractors gradually become more similar in size and font until fine discriminations are required. Reinforcement follows correct selections throughout. Which procedure is PRIMARY?",
    "D",
    [
      "Escape extinction for academic refusal only.",
      "Response cost of recess for each error without stimulus changes.",
      "Backward chaining of pencil grasp.",
      "Stimulus shaping/fading that progressively alters stimulus features toward the terminal discrimination.",
    ],
    [
      "Escape extinction is not the discrimination-transfer mechanism described.",
      "Punishing errors without programmed stimulus change is not stimulus shaping.",
      "Chaining grasp is unrelated to letter discrimination fading.",
      "Gradual change of stimulus dimensions toward the target discrimination is stimulus shaping/fading.",
    ],
  ),
  authored3(
    3513,
    "G",
    "At clinic, aggression under extinction drops. At home, where caregivers still occasionally deliver tangible items after aggression, aggression increases above prior home baseline. Clinic extinction remains in effect. Which phenomenon BEST accounts for the home increase?",
    "A",
    [
      "Behavioral contrast: responding increases in the unchanged component when reinforcement conditions worsen in another component.",
      "Stimulus equivalence between home and clinic.",
      "Forward chaining of aggression topographies.",
      "DRL successfully lowering home aggression.",
    ],
    [
      "Worsened reinforcement in one context with an increase in another is behavioral contrast.",
      "Equivalence concerns derived stimulus relations, not this contingency pattern.",
      "Chaining does not explain the cross-setting rate increase pattern.",
      "Home aggression increased, so DRL success does not fit.",
    ],
  ),
  authored3(
    3514,
    "G",
    "A learner self-records whether on-task behavior occurred at each momentary tone, graphs the data, and sets a daily goal with a negotiated preferred activity if the goal is met. Teacher prompts for recording fade. On-task percentages rise. Which package is PRIMARY?",
    "C",
    [
      "Exclusionary time-out for each off-task glance.",
      "NCR preferred activity on a clock regardless of goals.",
      "Self-management combining self-monitoring, goal setting, and contingent self-delivered/arranged reinforcement.",
      "Dependent group contingency where one peer earns for the class.",
    ],
    [
      "No time-out contingency is described as primary.",
      "The activity is goal-contingent, not purely time-based free delivery.",
      "Recording one's own behavior, setting goals, and arranging consequences is self-management.",
      "No hero peer structure is described.",
    ],
  ),
  authored3(
    3515,
    "G",
    "In a classroom token system, each student who independently completes a warm-up earns a token redeemable for a small backup. One student's failure does not affect others' earnings. Warm-up completion rises classwide. Which group contingency type is this?",
    "B",
    [
      "Interdependent: the whole class shares one team criterion.",
      "Independent group contingency: each student's own performance determines that student's consequence.",
      "Dependent hero: only one peer's performance earns for all.",
      "Habit reversal with competing response training only.",
    ],
    [
      "No shared team criterion is required.",
      "Individual criteria and individual consequences define an independent group contingency.",
      "No single hero determines the group's outcome.",
      "Habit reversal is not a group payoff structure.",
    ],
  ),
  authored3(
    3516,
    "G",
    "A class earns five extra minutes of music only if every student scores at least 80% on a quiet-work checklist. One student below criterion withholds the bonus for all. Peers begin prompting one another, and checklist scores rise. Which contingency is PRIMARY?",
    "D",
    [
      "Independent group contingency with purely individual payoffs.",
      "NCR music every period regardless of scores.",
      "DRA for yelling during quiet work.",
      "Interdependent group contingency requiring all members to meet the criterion for the shared reinforcer.",
    ],
    [
      "Outcomes are shared, not purely individual.",
      "Music is contingent on group performance, not free FT delivery.",
      "Yelling is not the reinforced alternative described.",
      "All-members criterion for a shared reinforcer is interdependent.",
    ],
  ),
  authored3(
    3517,
    "G",
    "A token economy works until backup reinforcers become delayed by weeks, menu items lose preference value, and tokens are awarded noncontingently 'to keep peace.' Token earning collapses. Which repair BEST restores procedure integrity?",
    "C",
    [
      "Increase response-cost fines only and remove all backups permanently.",
      "Keep noncontingent tokens but print them on nicer paper.",
      "Re-establish contingent token delivery, conduct preference assessments to refresh backups, and ensure reasonably immediate exchange opportunities.",
      "Replace tokens with contingent restraint for errors.",
    ],
    [
      "Punitive-only repairs without functional backups often fail and raise ethical concerns.",
      "Cosmetic token changes do not restore contingency or reinforcer value.",
      "Tokens function when contingent, backed by valued reinforcers, and exchangeable on a workable schedule.",
      "Restraint is not a token-economy repair and is overly restrictive here.",
    ],
  ),
  authored3(
    3518,
    "G",
    "When attention extinction begins for loud interruptions, interruptions briefly become louder and more frequent before declining. Staff almost reinstate attention during the spike. The BCBA anticipates this pattern and coaches integrity. Which process BEST names the temporary increase?",
    "A",
    [
      "Extinction burst—temporary increase in rate/intensity when reinforcement is withheld.",
      "Spontaneous recovery of a respondent startle only.",
      "Stimulus generalization gradient steepening.",
      "Matching-law shift toward a richer concurrent alternative that was not available.",
    ],
    [
      "A temporary worsening when extinction starts is an extinction burst.",
      "The vignette describes operant extinction dynamics, not a pure respondent startle account.",
      "Generalization gradients are not the described rate spike under extinction.",
      "No concurrent alternative enrichment is described as the cause of the spike.",
    ],
  ),
  authored3(
    3519,
    "G",
    "Property destruction to gain preferred toys is treated by teaching a card exchange for toy access, withholding toys after destruction, and prompting card use during establishing operations. Destruction falls as card exchanges rise across settings with multiple toy exemplars. Which procedure package is PRIMARY?",
    "B",
    [
      "Overcorrection as the sole intervention without a communication response.",
      "Functional communication training (FCT/DRA) for a mand to access the functional reinforcer, with extinction of destruction.",
      "DRL targeting higher destruction rates.",
      "Forward chaining of destruction topographies.",
    ],
    [
      "Restitution alone is not described; a communicative alternative is central.",
      "Teaching a communicative mand that produces the functional reinforcer while problem behavior no longer does is FCT.",
      "DRL would still reinforce destruction at lower rates, not replace it with a card mand.",
      "Chaining destruction opposes the treatment goal.",
    ],
  ),
  authored3(
    3520,
    "G",
    "Staff sample whether hand-flapping is occurring at the exact second a timer sounds every 2 minutes. If flapping is absent at the sample, the learner earns a token; if present, no token. Continuous absence across the interval is not required. Which procedure is this?",
    "D",
    [
      "Whole-interval DRO requiring zero flapping throughout each 2 minutes.",
      "DRH for faster flapping at sample moments.",
      "Backward chaining of timer setting.",
      "Momentary DRO: reinforcement based on absence of the target at the sampled instant.",
    ],
    [
      "Whole-interval DRO would require absence across the entire interval.",
      "DRH would reinforce increased flapping.",
      "Chaining timer use is not the reinforcement rule described.",
      "Momentary DRO checks only at the sampling instant.",
    ],
  ),
  authored3(
    3521,
    "G",
    "Escape-maintained aggression during long worksheets is reduced by first presenting very brief worksheet demands with dense reinforcement for compliance, then gradually increasing worksheet duration across successful sessions while maintaining high reinforcement density early in the fade. Which antecedent procedure is PRIMARY?",
    "A",
    [
      "Demand fading (graduated exposure to longer/harder task requirements) paired with reinforcement for compliance.",
      "Exclusionary time-out for every correct worksheet response.",
      "Lag reinforcement for novel aggression forms.",
      "Full extinction of all break requests permanently from day one without demand changes.",
    ],
    [
      "Systematically increasing demand requirements after success is demand fading.",
      "Time-out for correct responses would punish desired behavior.",
      "Lag schedules on aggression would increase variability of problem behavior.",
      "The vignette emphasizes graduated demands, not abrupt permanent extinction of all breaks alone.",
    ],
  ),
  authored3(
    3522,
    "G",
    "Automatically maintained vocal stereotypy that interferes with instruction is briefly interrupted with a prompt to complete an appropriate vocal or academic response, then redirected to that competing response, with praise for compliance. Stereotypy decreases during instructional windows. Which procedure BEST matches this description?",
    "C",
    [
      "NCR delivering free stereotypy periods on FT 10 seconds during teaching.",
      "Positive practice overcorrection lasting 20 minutes per instance as first-line treatment without less restrictive trials.",
      "Response interruption and redirection (RIRD) toward appropriate competing responses.",
      "Contingency contracting about weekend outings only.",
    ],
    [
      "Dense free access to stereotypy during teaching would not match interruption/redirection.",
      "Lengthy overcorrection is not the brief interrupt-and-redirect package described and raises least-restrictive concerns if used as default.",
      "Brief interruption plus redirection to appropriate responding characterizes RIRD.",
      "A weekend contract alone does not describe in-the-moment interruption/redirection.",
    ],
  ),
  authored3(
    3523,
    "G",
    "Caregivers must implement a three-step guided-compliance sequence for instruction-following. The BCBA uses instructions, modeling, rehearsal with the caregiver, and immediate feedback until integrity criteria are met, then conducts booster sessions. Caregiver integrity rises. Which training package is PRIMARY?",
    "B",
    [
      "Respondent pairing of the protocol PDF with preferred music only.",
      "Behavioral skills training (BST): instruction, modeling, rehearsal, and feedback.",
      "Lag schedules for novel caregiver errors.",
      "Dependent group contingency for the neighborhood.",
    ],
    [
      "Pairing a PDF with music does not build implementation skills.",
      "BST is defined by instruction, model, practice, and feedback components.",
      "Reinforcing error variability opposes integrity training.",
      "No neighborhood group payoff is described.",
    ],
  ),
  authored3(
    3524,
    "G",
    "A learner complies with easy 'touch nose / clap hands / high five' instructions at high rates. Immediately before a low-probability clean-up instruction, the BCBA presents a rapid sequence of those easy requests with reinforcement, then delivers clean-up. Clean-up compliance increases relative to clean-up-only trials. Which antecedent strategy is PRIMARY?",
    "D",
    [
      "Momentary DRO for clean-up refusals.",
      "Stimulus equivalence training for cleaning vocabulary only.",
      "Response cost of tokens before each easy request.",
      "High-probability request sequence (behavioral momentum) preceding the low-p demand.",
    ],
    [
      "DRO is not the pre-demand easy-request sequence described.",
      "Equivalence training alone does not capture the momentum sequence.",
      "Fining before easy requests undermines the strategy.",
      "A burst of high-p requests before a low-p target is a high-p / momentum procedure.",
    ],
  ),
  authored3(
    3525,
    "G",
    "Following severe aggression, a team proposes that the learner repeatedly restore the room and then continuously practice gentle object placement for several minutes (restitutional plus positive-practice overcorrection). No FA is complete, reinforcement-based options are untried, and the learner shows strong distress. What should the BCBA recommend regarding procedure selection?",
    "A",
    [
      "Do not adopt effortful overcorrection as first-line; complete functional assessment, prioritize less restrictive function-based interventions, and require consent, monitoring, and justification before any consequential practice of this type.",
      "Implement the longest overcorrection duration available on day one.",
      "Add covert water mist during restoration without guardian knowledge.",
      "Label overcorrection as 'practice' and skip all consent processes.",
    ],
    [
      "Effortful consequential procedures require strong justification and preferential use of less restrictive alternatives.",
      "Maximum intensity without assessment violates least-restrictive practice.",
      "Covert aversives compound ethical and clinical violations.",
      "Relabeling does not remove consent and assessment duties.",
    ],
  ),
  authored3(
    3526,
    "G",
    "To build rapid accurate letter-sound responding after acquisition accuracy is already high, the BCBA runs short timed practice sprints with immediate corrective feedback, aims for rate criteria, and schedules retention probes several days later. Rates rise while accuracy remains high. Which emphasis BEST names this phase?",
    "C",
    [
      "Functional analysis of letter sounds using tangible and escape conditions.",
      "Full extinction of all correct letter-sound responses.",
      "Fluency building: increasing speed of accurate responding with retention checks after acquisition.",
      "Most-to-least physical prompting for every fluent response permanently.",
    ],
    [
      "Timed practice after acquisition is not an FA.",
      "Extinguishing correct responses opposes skill building.",
      "Fluency work targets high rates of accurate responding and retention beyond acquisition alone.",
      "Permanent physical prompting conflicts with fluent independent performance.",
    ],
  ),
];
