/**
 * Authored Mock Exam 3 expanded items — Domains A, D, H, I.
 * Completely new vignettes vs Mock 1 and Mock 2.
 * Independent study only. Not affiliated with the BACB.
 */
import type { BDSQuestion } from "@/lib/content-types";
import { authored3 } from "@/content/mockExam/exams/bcbaPractice3/authoredHelper";

export const EXPANDED3_A: BDSQuestion[] = [
  authored3(
    3001,
    "A",
    "A district coach tells a BCBA that a student's sudden increase in on-task behavior after a seating change 'just happened' and that looking for environmental causes is optional because 'some kids turn a corner for no reason.' The BCBA argues that even unexplained-looking shifts should be treated as potentially lawful products of history and current context. Which foundational assumption BEST anchors the BCBA's reply?",
    "B",
    [
      "Mentalism—inner willpower is the preferred ultimate cause whenever a seating change coincides with improvement.",
      "Determinism—behavior is assumed to be lawful and orderly, so investigators seek environmental and historical variables rather than treating change as causeless.",
      "Structuralism—classify seating arrangements by furniture brand and stop analyzing performance.",
      "Fatalism—outcomes are fixed at birth, so rearranging seats cannot matter and data collection is pointless.",
    ],
    [
      "Mentalistic willpower accounts displace contingency analysis; they do not support the BCBA's stance.",
      "Determinism commits the science to searching for orderly relations between behavior and environment even when a change initially looks unexplained.",
      "Structural classification of furniture does not address lawfulness of behavior change.",
      "Fatalism denies environmental influence and contradicts applied analysis.",
    ],
  ),
  authored3(
    3002,
    "A",
    "During grand rounds, a physician asks why the BCBA insists on systematically manipulating demand density and measuring aggression rather than accepting a one-time anecdote that 'hard work days cause meltdowns.' The BCBA replies that belief alone is insufficient; the relation must be tested under conditions that can confirm or disconfirm it. Which scientific attitude MOST justifies that reply?",
    "D",
    [
      "Circular reasoning—define hard work as causal because aggression occurred on a hard day.",
      "Nativism—treat all aggression spikes as predetermined maturational events immune to contingency tests.",
      "Methodological behaviorism redefined as refusing all verbal reports forever.",
      "Experimentation—actively arrange and evaluate conditions to identify functional relations rather than resting on uncontrolled anecdotes.",
    ],
    [
      "Circular endorsement of the anecdote is what experimentation is meant to replace.",
      "Nativism sidesteps contingency evaluation rather than supporting it.",
      "The issue is testing a hypothesized relation, not a blanket ban on verbal reports.",
      "Experimentation is the attitude of arranging conditions and collecting data to evaluate causal claims instead of accepting untested stories.",
    ],
  ),
  authored3(
    3003,
    "A",
    "A case conference produces three accounts of reduced vocal stereotypy after headphones were introduced: (1) headphones reduced auditory EO intensity for stereotypy; (2) the learner developed a new 'inner calm trait'; (3) the headphones activated an unmeasured 'neurological reset circuit' plus two unnamed motivational subsystems. Session data fit account (1) without leftover variance requiring the extras. Which attitude MOST favors preferring account (1)?",
    "A",
    [
      "Parsimony—prefer the simplest adequate explanation that accounts for the data without stacking unverified constructs.",
      "Philosophic doubt redefined as rejecting any environmental account on principle.",
      "Dualism—keep inner traits as mandatory co-causes even when contingency accounts suffice.",
      "Pragmatism redefined as whichever story impresses the largest committee.",
    ],
    [
      "Parsimony favors explanatory sufficiency with the fewest assumptions when a contingency account already fits.",
      "Philosophic doubt questions certainty; it does not require rejecting well-supported environmental accounts.",
      "Dualism adds unnecessary causal realms when a leaner account works.",
      "Clinical pragmatism concerns useful prediction and control under data, not committee theater.",
    ],
  ),
  authored3(
    3004,
    "A",
    "A vendor claims its app 'guarantees' skill mastery after seven days based on a single agency's uncontrolled before–after charts. A BCBA refuses to certify the claim for district-wide adoption and instead lists rival explanations (staffing boost, easier targets) and asks for cleaner replications. A board member calls the BCBA 'obstructionist.' Which scientific attitude MOST supports the refusal?",
    "C",
    [
      "Empiricism redefined as accepting any graph that uses colorful software.",
      "Selectionism that treats marketing slogans as phylogenetic facts.",
      "Philosophic doubt—hold conclusions tentatively, entertain rival accounts, and require adequate evidence before generalizing or certifying certainty.",
      "Circular reasoning—treat the purchase contract as proof of efficacy.",
    ],
    [
      "Software aesthetics are not a substitute for controlled evidence.",
      "Selectionism concerns variation and differential consequences, not slogan acceptance.",
      "Philosophic doubt resists overclaiming from weak demonstrations and keeps knowledge provisional—especially under commercial pressure.",
      "Purchase history is not experimental evidence.",
    ],
  ),
  authored3(
    3005,
    "A",
    "A parent asks whether behavior analysis 'ignores thoughts and feelings.' The BCBA answers that private events can be discussed as behavior influenced by environmental history, but public contingency changes remain the primary focus for prediction and control when they covary with outcomes. Which philosophical stance BEST matches that answer?",
    "B",
    [
      "Methodological behaviorism that permanently bans any mention of private events in clinical conversation.",
      "Radical behaviorism—private events are behavior under environmental influence, while applied accountability stays anchored in observable contingency relations.",
      "Mentalism that treats unmeasured readiness as the sole cause and discards environmental analysis.",
      "Structuralism that ranks topographies by visual appeal without reference to function or history.",
    ],
    [
      "Radical behaviorism does not require silencing private-event talk; methodological exclusion is a different stance.",
      "Radical behaviorism includes private events as behavior while keeping prediction and control tied to environmental contingencies.",
      "Mentalistic readiness accounts are what the BCBA is declining to privilege.",
      "Structural classification without function/history is not the stance described.",
    ],
  ),
  authored3(
    3006,
    "A",
    "After a peer-tutoring contingency is added, a middle schooler's homework completion rises. One staff member credits a sudden 'growth mindset awakening.' Another staff member points to differential reinforcement of completion and reduced escape for incomplete work. Which orientation BEST supports the second staff member?",
    "A",
    [
      "Selectionism—responses that contact differential consequences are more likely to recur in that context.",
      "Vitalism—an inner life force independently chooses homework completion.",
      "Essentialism—homework completion reflects a fixed character type immune to contingencies.",
      "Teleology—future goals pull present behavior without environmental mediation.",
    ],
    [
      "Selectionism explains repertoire change through variation and differential consequences in context.",
      "Vitalistic inner forces bypass contingency analysis.",
      "Fixed character accounts deny contingency sensitivity shown in the vignette.",
      "Purpose-as-pull without environmental mediation is not a behavior-analytic account.",
    ],
  ),
  authored3(
    3007,
    "A",
    "A trainee proposes measuring only whether a client's smile 'looks happy' after sessions and skipping rate/duration of targeted problem behavior because 'happiness is what matters.' The supervisor agrees happiness ratings can be socially valid adjuncts but insists primary clinical claims still require systematic observation of the defined target responses. Which scientific attitude MOST justifies the supervisor's insistence?",
    "D",
    [
      "Fatalism—measurement cannot influence practice, so either metric is fine.",
      "Mentalism—inner happiness is the only legitimate dependent variable in ABA.",
      "Circular reasoning—define success as whatever makes the graph pretty.",
      "Empiricism—ground effectiveness claims in systematic observation and measurement of the behaviors of interest, not impression alone.",
    ],
    [
      "Fatalism contradicts data-based practice.",
      "Subjective happiness may matter socially but does not replace measurement of targeted operants for clinical claims.",
      "Aesthetic graphs are not evidence standards.",
      "Empiricism requires systematic observation of defined responses when claiming intervention effects.",
    ],
  ),
  authored3(
    3008,
    "A",
    "A consultant attributes a client's aggression solely to an 'oppositional personality core' that cannot be changed and therefore declines to examine antecedents, consequences, or skill deficits. The BCBA objects that this framing treats an inferred inner essence as cause while abandoning manipulable environmental variables. The objection MOST directly targets which explanatory error?",
    "C",
    [
      "Excessive empiricism that demands too much direct observation.",
      "Overuse of single-case designs in applied settings.",
      "Mentalism—explaining behavior by appeal to unobserved inner entities or traits while neglecting environmental contingencies.",
      "Parsimony taken too far by preferring simpler contingency accounts.",
    ],
    [
      "The problem is not too much observation; it is displacing contingency analysis.",
      "Design choice is not the philosophical error described.",
      "Mentalistic trait explanations shortcut environmental analysis and block prediction and control through contingency change.",
      "Preferring adequate contingency accounts is appropriate, not the error being critiqued.",
    ],
  ),
  authored3(
    3009,
    "A",
    "Two explanations of a successful toilet-training package are offered: Explanation X predicts when accidents will recur if scheduled sits are thinned too quickly and guides how to change the schedule; Explanation Y uses impressive jargon but yields no actionable predictions for the next week's programming. Stakeholders like Explanation Y's wording. Which criterion BEST favors Explanation X for applied work?",
    "B",
    [
      "Literary elegance—prefer the explanation with more specialized vocabulary.",
      "Pragmatism—prefer accounts that improve prediction and control of behavior under the conditions of interest.",
      "Authority—prefer whichever explanation a vendor printed first.",
      "Consensus—prefer the explanation that wins a hallway popularity vote.",
    ],
    [
      "Jargon density is not a validity criterion.",
      "In behavior analysis, pragmatism judges explanations by their usefulness for prediction and control—Explanation X guides programming; Y does not.",
      "Publication order is not evidence of usefulness.",
      "Popularity is not a substitute for practical analytic utility.",
    ],
  ),
];

export const EXPANDED3_D: BDSQuestion[] = [
  authored3(
    3011,
    "D",
    "A BCBA evaluates a tolerance-for-denial program using a multiple-probe design across three preferred items. Continuous baseline is impractical because denial probes themselves evoke escalation. After stable probes, intervention begins with Item 1; Items 2 and 3 stay in infrequent probes and remain low until their staggered introductions, when each rises. Leadership asks whether the design can still support experimental control. What is the MOST accurate appraisal?",
    "A",
    [
      "Staggered improvements coincident with successive introductions, with untreated probes remaining low, can support experimental control when continuous measurement would itself distort the baseline.",
      "Multiple-probe designs are never interpretable in applied work and must be discarded.",
      "Experimental control requires simultaneous intervention across all items on day one.",
      "Any use of probes automatically converts the study into a group randomized trial.",
    ],
    [
      "Multiple-probe logic is a recognized SCD strategy when continuous baselines are impractical; staggered change with stable untreated probes supports control.",
      "Probe designs can be interpretable when carefully arranged; blanket dismissal is incorrect.",
      "Simultaneous introduction across all tiers would destroy stagger logic.",
      "Probes remain within single-case logic; they do not create a group RCT.",
    ],
  ),
  authored3(
    3012,
    "D",
    "An alternating-treatments comparison of two break-request topographies shows Condition Green slightly ahead, but therapists report that after several Green→Blue sequences the learner continues emitting Green forms into Blue sessions for the first few trials. Graphs still plot each session under its scheduled label. What threat MOST undermines clean comparison?",
    "C",
    [
      "Insufficient number of phase lines for a reversal design.",
      "Multiple-baseline stagger that was never intended in an ATD.",
      "Carryover/sequence effects—responding under one condition persists into the next, blurring functional independence of the rapidly alternated treatments.",
      "Proof that alternating-treatments designs cannot include communication responses.",
    ],
    [
      "ATDs are not judged by reversal phase-line counts.",
      "MBD stagger is a different design logic; the vignette's problem is carryover.",
      "Carryover/multitreatment interference threatens ATD interpretability when prior-condition responding contaminates subsequent sessions.",
      "Communication targets can be compared in ATDs when conditions remain discriminable and uncontaminated.",
    ],
  ),
  authored3(
    3013,
    "D",
    "A team runs a component analysis of a three-part mealtime package (visual schedule, escape extinction, and differential reinforcement). After the full package suppresses disruption, components are withdrawn one at a time in successive phases while others remain. Disruption returns only when escape extinction is removed. What conclusion is MOST justified?",
    "B",
    [
      "All three components are equally necessary because they were introduced together originally.",
      "Escape extinction appears to be a critical component under these conditions because disruption covaries specifically with its presence versus absence.",
      "Component analyses forbid any conclusion unless a group design is added.",
      "Visual schedules are proven inert in all future clients based on this one series.",
    ],
    [
      "Initial packaging does not prove equal necessity; dissociation phases test contribution.",
      "Selective recovery when one component is removed supports identifying that component as critical in this analysis.",
      "SCD component analyses can yield useful within-subject conclusions without a group trial.",
      "One client's series does not establish universal inertness of a component for all learners.",
    ],
  ),
  authored3(
    3014,
    "D",
    "A parametric evaluation compares DRA reinforcer durations of 10 s, 30 s, and 90 s across rapidly alternated sessions with clear discriminative stimuli. Disruption is lowest and stable in 30 s sessions; 10 s yields incomplete suppression; 90 s yields suppression but long off-task pauses that reduce instructional trials. Stakeholders want a single 'maximum is always best' rule. What does the parametric series MOST support?",
    "D",
    [
      "That parametric designs are unethical whenever food or breaks are used.",
      "That only the longest magnitude can ever be selected in applied work.",
      "That parametric analyses require abandoning single-case logic for ANOVA.",
      "That intermediate magnitude (30 s) best balances behavior reduction with instructional efficiency under these conditions—selection should follow the function of the parameter, not a 'more is always better' slogan.",
    ],
    [
      "Parametric work with reinforcers can be ethical and informative with proper consent/safety.",
      "Longest magnitude underperformed on efficiency; maximality is not automatic best practice.",
      "Parametric SCD comparisons do not require converting to group ANOVA.",
      "Parametric analysis identifies effective ranges; here 30 s optimizes competing clinical outcomes better than extremes.",
    ],
  ),
  authored3(
    3015,
    "D",
    "In a multiple-baseline across three topographies of self-injury, intervening on forehead hitting is followed by reductions in untreated hand biting and head banging before those tiers receive intervention. Medical status is stable; no school-wide contingency change is identified. The agency wants to claim three independent demonstrations of control. What is the MOST serious interpretive issue?",
    "A",
    [
      "Response covariation/generalization across topographies may produce concurrent change in untreated tiers, weakening the staggered demonstration of independent experimental control.",
      "Multiple-baseline designs forbid more than one topography per client.",
      "Any improvement proves the intervention is ineffective on the treated topography.",
      "Across-behavior MBDs require deleting untreated series once any peer topography improves.",
    ],
    [
      "When untreated behaviors change with treatment of a related topography, MBD persuasion that each tier independently tracks its own introduction is threatened by covariation.",
      "Across-behavior MBDs are common; the flaw is covariation, not topography count.",
      "Untreated-tier change threatens attribution structure; it does not by itself prove the treated tier failed.",
      "Untreated tiers should remain for comparison; deleting them removes control series.",
    ],
  ),
  authored3(
    3016,
    "D",
    "A changing-criterion design for independent toothbrushing steps advances from 2 to 4 to 6 steps. To strengthen demonstration, the BCBA briefly reverses the criterion from 6 back to 4; performance drops toward the lower criterion, then rises again when 6 is reinstated. A reviewer calls the mini-reversal 'contamination.' What analytic role does the mini-reversal MOST serve?",
    "C",
    [
      "It converts the study into an uninterpretable AB design.",
      "It proves changing-criterion designs are invalid whenever criteria decrease.",
      "It strengthens experimental control by showing performance tracks criterion direction—including a temporary return to a prior criterion—not merely maturation or practice.",
      "It requires discarding all prior ascending steps as scientifically meaningless.",
    ],
    [
      "A deliberate mini-reversal within changing-criterion logic is a control tactic, not an AB collapse.",
      "Brief criterion decreases are an accepted strategy to show covariation with the criterion.",
      "Tracking a downward then upward criterion shift bolsters the claim that the criterion contingency controls performance.",
      "Prior ascending correspondence remains informative; the mini-reversal adds, rather than erases, control evidence.",
    ],
  ),
  authored3(
    3017,
    "D",
    "A clinic uses a nonconcurrent multiple-baseline across three clients referred months apart for the same feeding refusal package. Each client's baseline is collected to stability before that client's intervention; introductions are staggered in calendar time because clients did not overlap. A funder demands a concurrent classroom MBD and calls the nonconcurrent series 'worthless.' What is the MOST balanced appraisal?",
    "B",
    [
      "Nonconcurrent MBDs are identical in threat profile to concurrent MBDs and never require caveats.",
      "Nonconcurrent MBDs can still demonstrate staggered control within each series but leave more history/cohort threats than concurrent designs; they are weaker yet not automatically worthless when concurrent tiers are unavailable.",
      "Only concurrent MBDs counted in any applied decision-making context.",
      "Nonconcurrent designs magically eliminate all maturation threats.",
    ],
    [
      "Nonconcurrent arrangements typically face greater history threats; they are not threat-identical to concurrent MBDs.",
      "Honest appraisal: useful when concurrent tiers are impossible, with clearer limits on ruling out time-related confounds—still potentially informative, not scrap.",
      "Applied decisions often use the best feasible design; concurrent is preferred, not the sole admissible evidence.",
      "Nonconcurrent logic does not erase maturation/history concerns.",
    ],
  ),
  authored3(
    3018,
    "D",
    "Baseline for classroom calling-out is stable. An intervention package produces a clear level drop. During a planned, consented withdrawal, calling-out does not recover despite verified return to baseline contingencies; reinstatement keeps rates low. Staff want to advertise 'permanent cure proving designs need no replication.' Which conclusion is MOST justified?",
    "D",
    [
      "Failure to recover always proves the original baseline was fake and invalidates the study.",
      "Irreversibility automatically upgrades an ABAB attempt into a perfect group experiment.",
      "Lack of recovery means experimental control was demonstrated more strongly than a clear reversal would have.",
      "Incomplete recovery limits reversal-based demonstration; control may still be pursued via other tactics (e.g., multiple baseline, criteria changes), and irreversibility should not be marketed as making further analysis unnecessary.",
    ],
    [
      "Nonrecovery has several explanations; it does not by itself prove baseline fraud.",
      "Design family does not convert to a group experiment via nonrecovery.",
      "Clear recovery typically strengthens reversal logic; nonrecovery weakens that particular demonstration.",
      "When behavior does not reverse, ABAB persuasion is limited—seek alternative demonstrations and avoid overclaiming 'permanent cure.'",
    ],
  ),
  authored3(
    3019,
    "D",
    "A BCBA overlays a brief alternating-treatments comparison of two prompt topographies onto the intervention phase of a multiple-baseline across routines after each routine has already shown package-level improvement. Discriminative cues for prompt type are weak, and therapists often blend prompts. The team later claims both 'MBD control for the package' and 'ATD winner for prompts' from the same messy sessions. What is the PRIMARY problem?",
    "A",
    [
      "Combining design elements without integrity and discriminability can confound attribution—package-level MBD control does not automatically validate a contaminated embedded ATD comparison.",
      "Multiple-baseline designs legally forbid any later parametric or comparative questions.",
      "Alternating treatments cannot be graphed on the same calendar as a multiple baseline under any conditions.",
      "Embedded comparisons are valid whenever two colors appear on a legend.",
    ],
    [
      "Combination designs can be useful, but weak discriminability and blended implementation undermine the ATD claim even if earlier MBD stagger for the package looked orderly.",
      "MBDs do not forbid later analyses; the issue is contamination of the comparison.",
      "Designs can share a timeline when carefully arranged; the flaw is integrity/discriminability.",
      "Color legends do not create experimental control.",
    ],
  ),
  authored3(
    3020,
    "D",
    "Visual analysis of a DRA phase shows a gradually descending trend in aggression with high variability and substantial overlap with the preceding baseline's range, despite a slightly lower phase mean. The agency wants to report a 'clear functional relation' for an insurer. What visual-analysis conclusion is MOST defensible?",
    "C",
    [
      "Any lower phase mean proves experimental control regardless of overlap, trend, or variability.",
      "High variability is irrelevant if the software can draw a phase line.",
      "Modest mean differences with marked overlap and unclear separation do not constitute a clear demonstration of experimental control; stronger differentiation or design enhancements are needed before confident causal claims.",
      "Overlap statistics are banned in single-case work, so the insurer claim is automatically valid.",
    ],
    [
      "Means alone without considering overlap, trend, and variability overstate control.",
      "Phase lines organize data; they do not create functional relations.",
      "Conservative visual analysis requires clear level/trend separation and reduced overlap for strong control claims—especially in high-stakes reporting.",
      "Overlap is central to SCD visual analysis; it is not banned.",
    ],
  ),
  authored3(
    3021,
    "D",
    "Three classrooms will eventually receive the same transition protocol, but Classroom C cannot begin baseline for six weeks due to staffing. The BCBA starts baselines in A and B now and will begin C's baseline later, still staggering intervention after each tier's own stable baseline. A critic says delayed tiers invalidate all multiple-baseline logic. What is the MOST accurate response?",
    "B",
    [
      "Delayed multiple-baseline tiers are forbidden and render the entire evaluation unscientific.",
      "Delayed baselines can be acceptable when each tier still shows stability before its own intervention and introductions remain staggered, though additional time-related threats should be acknowledged.",
      "Intervention must start in all classrooms before any baseline is collected.",
      "Delaying Classroom C converts the design into a reversal automatically.",
    ],
    [
      "Delayed MBDs are a recognized variant when tiers cannot start together; they are not automatically void.",
      "Control still hinges on within-tier stability and stagger; delays add caveats but can remain interpretable.",
      "Baseline-before-intervention sequencing remains essential.",
      "Calendar delay does not create reversal logic by itself.",
    ],
  ),
  authored3(
    3022,
    "D",
    "An ABAB evaluation appears orderly, but IOA for the dependent variable averages 62% with frequent disagreements about whether responses met the operational definition. Integrity for the IV is high. Leadership likes the graph's shape and wants to publish causal claims. Which validity concern is MOST critical?",
    "D",
    [
      "High IV integrity alone guarantees dependable DV measurement.",
      "IOA below conventional standards is irrelevant if phases look pretty.",
      "Disagreements about the DV prove the IV was misapplied.",
      "Weak IOA threatens confidence that the plotted DV is a trustworthy measure—experimental control claims rest on reliable observation as well as orderly phase patterns.",
    ],
    [
      "IV integrity does not rescue an unreliable dependent measure.",
      "Aesthetic phase separation cannot compensate for poor measurement agreement.",
      "DV disagreement is a measurement problem; it does not by itself equal IV integrity failure.",
      "Reliable measurement is foundational; poor IOA undermines interpretation of apparent functional relations.",
    ],
  ),
  authored3(
    3023,
    "D",
    "A BCBA demonstrates strong within-subject control for a leisure-item DRA in one highly structured clinic room. Stakeholders demand a statement that the same effect is therefore proven for all homes, schools, and ages in the county. What distinction should guide the BCBA's wording?",
    "A",
    [
      "Internal validity concerns whether the IV caused the change in this evaluation; external validity concerns generality across clients, settings, and conditions—and requires additional evidence beyond one controlled series.",
      "Internal and external validity are identical, so one clinic series settles county-wide generality.",
      "External validity is established automatically by using a phase line.",
      "Internal validity is irrelevant to applied graphs used for funding.",
    ],
    [
      "Separating demonstrated control here from untested generality elsewhere prevents overclaiming.",
      "One controlled demonstration does not equal broad external validity.",
      "Phase lines do not create generality.",
      "Internal validity remains central when claiming the IV produced the effect.",
    ],
  ),
  authored3(
    3024,
    "D",
    "During an ATD comparing Package L and Package M, sessions are supposed to be counterbalanced. Audit logs show Package L always ran in the first half of the day when the learner was fresh and Package M always ran after lengthy demand blocks. Graphs favor Package L. What confound is MOST critical?",
    "C",
    [
      "Observer drift that only affects weekend sessions not in the dataset.",
      "Proof that counterbalancing is unnecessary in ATDs.",
      "Time-of-day/fatigue confounding systematically favors one package independent of its procedures.",
      "Multiple-baseline stagger embedded unintentionally across packages.",
    ],
    [
      "The vignette specifies a within-day ordering confound, not weekend observer drift.",
      "Counterbalancing exists precisely to reduce such sequence/time confounds.",
      "Systematic assignment of one condition to high-fatigue periods threatens attribution to the package procedures themselves.",
      "This is an ATD ordering confound, not MBD stagger.",
    ],
  ),
  authored3(
    3025,
    "D",
    "A school team collects only two baseline sessions for severe property destruction before launching a complex intervention because an administrator wants a graph 'for Friday's meeting.' Data are variable with no stability. After intervention, rates fall, and the administrator claims definitive experimental control. What is the MOST serious design weakness?",
    "B",
    [
      "Two baseline points always maximize internal validity in SCD work.",
      "Inadequate baseline length/stability prevents confident prediction of continued baseline performance, so post-intervention decreases cannot be firmly attributed to the IV versus ongoing variability or trends.",
      "Baseline is optional whenever meetings are scheduled.",
      "Any decrease after a phase line equals a completed reversal demonstration.",
    ],
    [
      "Very brief, unstable baselines weaken, rather than maximize, control demonstrations.",
      "Stable baselines establish the forecast against which intervention effects are judged; skipping that step under meeting pressure undermines causal claims.",
      "Administrative deadlines do not waive baseline logic.",
      "AB-style decreases without adequate baseline prediction remain weak; they are not reversal-equivalent.",
    ],
  ),
];

export const EXPANDED3_H: BDSQuestion[] = [
  authored3(
    3031,
    "H",
    "A preference assessment shows consistent selection of tablet access over edibles and toys. The current DRA for task completion still uses edible reinforcers chosen from an old list; integrity is high, but task completion remains low and tablet access continues to follow problem behavior at home. Which selection/revision priority is MOST defensible?",
    "B",
    [
      "Keep edibles indefinitely because they were listed in last year's plan binder.",
      "Align programmed reinforcers with current preference data and block competing tablet reinforcement for problem behavior so the DRA contacts a high-value maintaining consequence.",
      "Abandon reinforcement and switch to reprimands because preference assessments are only for leisure.",
      "Use the lowest-preference items to 'build character' during work tasks.",
    ],
    [
      "Outdated reinforcer lists often fail when preferences shift.",
      "Domain H selection ties consequences to current preference/value and addresses competing reinforcement schedules that undermine DRA.",
      "Preference data inform reinforcer selection; they do not justify abandoning positive programming.",
      "Low-preference consequences are poor DRA choices when effective alternatives exist.",
    ],
  ),
  authored3(
    3032,
    "H",
    "Functional analysis indicates attention maintains loud vocal protests. Staff propose continuous noncontingent attention (NCR) on a dense FT schedule that would eliminate nearly all instructional trials. An alternative is FCT for attention plus thinning. Instructional time is a family priority. Which selection BEST balances function match with contextual goals?",
    "D",
    [
      "Choose the densest NCR possible even if instruction stops entirely, because denser is always better.",
      "Ignore function and pick whichever binder protocol has the newest cover.",
      "Use only extinction without teaching a replacement request because teaching takes time.",
      "Prefer FCT (and planned thinning) that matches attention function while preserving instructional opportunities, using NCR only as a carefully dosed adjunct if needed—not as a schedule that abolishes teaching.",
    ],
    [
      "Maximal NCR that eliminates instruction conflicts with stated educational priorities.",
      "Binder novelty is not a function-based selection criterion.",
      "Extinction without a replacement can increase risk and skips skill building.",
      "Function-matched communication with feasible instructional dosage better serves clinical and social validity goals than instruction-abolishing NCR.",
    ],
  ),
  authored3(
    3033,
    "H",
    "Before difficult hygiene routines, a learner complies with a brief series of easy, high-probability requests, after which the hygiene demand is presented and compliance rises. A new clinician wants to scrap the sequence because it is 'not the function-based treatment.' FA had shown escape maintenance; demand fading and FCT are already in the plan. How should the high-p sequence be viewed?",
    "A",
    [
      "As a compatible antecedent strategy that can improve compliance probability and may be combined with function-based consequences—not as a rival that must replace FCT/demand fading.",
      "As proof that escape-maintained behavior cannot exist if high-p works at all.",
      "As a restrictive punishment procedure requiring crisis-committee approval before any easy requests.",
      "As a reason to discontinue all consequence-based programming permanently.",
    ],
    [
      "High-p request sequences are antecedent interventions often used alongside function-based plans, not mutually exclusive replacements.",
      "High-p success does not erase FA-identified escape function.",
      "Easy instructional requests are not punishment procedures.",
      "Antecedent aids do not justify abandoning consequence programming.",
    ],
  ),
  authored3(
    3034,
    "H",
    "A token economy for vocational steps uses tokens that are rarely exchanged, backup reinforcers that are delayed until weekly staff meetings, and exchange prices so high that learners seldom contact backups. On-task data are flat. Leadership likes the 'economy' optics. What parameter revision is MOST indicated?",
    "C",
    [
      "Keep unreachable prices to teach frustration tolerance as the primary skill.",
      "Remove all backup reinforcers and keep tokens as purely symbolic stickers.",
      "Adjust token earn rates, exchange schedules, and backup magnitude/immediacy so tokens reliably contact valued backups under achievable prices—then evaluate effects.",
      "Add response cost for blinking to increase 'structure' without checking reinforcer contact.",
    ],
    [
      "Chronic failure to contact backups undermines the economy's reinforcing function.",
      "Tokens without backup contact are unlikely to sustain vocational behavior.",
      "Token systems work when conditioned reinforcers maintain value through effective exchange parameters.",
      "Arbitrary response cost adds restrictiveness without fixing reinforcer contact.",
    ],
  ),
  authored3(
    3035,
    "H",
    "A classroom considers an interdependent group contingency (whole group earns a picnic if peer-supported transitions meet criterion). Two students have limited peer skills and may be blamed if the criterion fails. Teachers want simplicity. Which selection consideration is MOST critical before adopting the interdependent plan?",
    "B",
    [
      "Interdependent contingencies are always unethical in schools and must never be used.",
      "Assess risk of peer scapegoating and skill prerequisites; consider independent or dependent alternatives, teach peer supports, and ensure the criterion is achievable without compromising dignity.",
      "Pick interdependent schedules solely because they require the least teacher data.",
      "Use group punishment of the entire class whenever one student errs, without a reinforcement component.",
    ],
    [
      "Interdependent plans can be appropriate with safeguards; blanket bans are unnecessary.",
      "Social validity and side-effect risks (blame, exclusion) are central selection issues for interdependent group contingencies.",
      "Teacher convenience alone is insufficient when dignity risks are foreseeable.",
      "Punishment-only group procedures fail least-restrictive and reinforcement-priority expectations.",
    ],
  ),
  authored3(
    3036,
    "H",
    "An adolescent can accurately self-record on-task behavior when cued and shows preference for controlling a personal checklist over adult-delivered tokens. Staffing for dense adult reinforcement is limited in the general-education setting. Which intervention emphasis BEST fits selection priorities?",
    "A",
    [
      "Program a self-management package (self-monitoring, self-evaluation, and recruited reinforcement) with training to mastery and periodic accuracy checks, matching the learner's preference and the setting's staffing constraints.",
      "Reject self-management because only therapist-delivered tokens count as ABA.",
      "Use the most staff-intensive 1:1 token delivery possible despite setting constraints and learner preference.",
      "Avoid teaching self-recording lest the learner become 'too independent' for services.",
    ],
    [
      "Self-management can be function- and context-appropriate when skills and preferences support it and fidelity supports are planned.",
      "ABA includes self-management as a legitimate technology.",
      "Ignoring constraints and preference undermines contextual fit.",
      "Independence goals align with socially valid outcomes rather than threatening them.",
    ],
  ),
  authored3(
    3037,
    "H",
    "A learner emits high-rate motor stereotypy that interferes with vocational scanning. Competing-stimulus assessment shows certain leisure items suppress stereotypy when available noncontingently. Staff propose response interruption and redirection (RIRD) as the first and only procedure, which the learner finds highly aversive. What selection sequence is MOST consistent with least-restrictive practice?",
    "D",
    [
      "Begin with the most aversive RIRD intensity available to suppress stereotypy quickly for optics.",
      "Skip assessment-informed competing stimuli because interruption looks more 'clinical.'",
      "Use RIRD continuously in all settings without evaluating milder supports.",
      "Prioritize competing stimuli / enrichment and skill-based alternatives shown to reduce stereotypy; consider RIRD only if less intrusive strategies fail or risk requires it, with assent/consent review.",
    ],
    [
      "Maximal aversiveness first conflicts with least-restrictive sequencing.",
      "Assessment-informed stimuli are precisely the milder option to try.",
      "Continuous RIRD without trying milder supports skips least-restrictive logic.",
      "Use effective, less intrusive assessment-guided strategies before escalating to more aversive interruption procedures.",
    ],
  ),
  authored3(
    3038,
    "H",
    "Caregivers and a teen agree to a written behavioral contract: complete two chore routines → weekend community outing. Tasks are specific, the reinforcer is valued, and both parties sign. After one week, caregivers add unstated extra chores before the outing 'because progress is good.' The teen protests. What implementation correction is MOST appropriate?",
    "C",
    [
      "Unilaterally add chores indefinitely because contracts never bind caregivers.",
      "Discard contracting forever after one dispute.",
      "Honor the written contingency as negotiated—deliver the outing when stated criteria are met; renegotiate additional tasks only through an updated, agreed contract.",
      "Replace the outing with response cost for protesting the midstream change.",
    ],
    [
      "Contracts bind both parties; unilateral criterion inflation undermines trust and contingency clarity.",
      "One dispute is a reason to repair fidelity to the contract, not abandon the technology.",
      "Contract integrity requires delivering agreed consequences for agreed performances and using renegotiation for changes.",
      "Punishing protest about unfair midstream changes worsens social validity.",
    ],
  ),
  authored3(
    3039,
    "H",
    "A learner reliably works for access to drawing (high-probability activity) but not for math worksheets. The BCBA proposes sequencing: complete a small math requirement → immediate drawing access (Premack). A therapist argues Premack is outdated and wants edible bribes unrelated to preference data. Which selection rationale BEST supports Premack here?",
    "B",
    [
      "Premack arrangements are unethical whenever academics are involved.",
      "High-probability activities can reinforce lower-probability academic responses when access is contingent—using a preferred activity already shown to be probable for this learner.",
      "Premack requires abandoning all functional assessment information.",
      "Edible bribes must always outrank activity reinforcers regardless of preference.",
    ],
    [
      "Premack is a standard reinforcement arrangement and can be appropriate for academic tasks.",
      "Contingent access to a high-probability activity is a defensible reinforcer selection when preference/probability data support it.",
      "Premack complements, rather than replaces, function-based understanding of problem behavior if present.",
      "Preference data should guide reinforcer form; edibles are not universally superior.",
    ],
  ),
  authored3(
    3040,
    "H",
    "Extinction for attention-maintained screaming is introduced with FCT. On day two, screaming intensity and duration spike above baseline, and staff threaten to abandon the plan. No safety risk beyond elevated vocal protest is present. What is the MOST appropriate selection/implementation guidance?",
    "A",
    [
      "Anticipate extinction bursts—maintain agreed safety criteria, continue reinforcing the alternative response, avoid inadvertently reinforcing the burst, and review data before abandoning a well-matched plan.",
      "Treat any temporary increase as proof extinction can never work and stop FCT immediately.",
      "Add physical punishment on day two because bursts mean positive programming failed forever.",
      "Ignore the written crisis/safety plan because bursts are 'just drama.'",
    ],
    [
      "Extinction bursts are expected side effects; planned persistence with FCT and safety rules is appropriate when risk remains acceptable.",
      "A burst alone does not falsify a function-matched plan.",
      "Escalating to punishment skips least-restrictive troubleshooting.",
      "Safety planning remains essential during extinction-based interventions.",
    ],
  ),
  authored3(
    3041,
    "H",
    "Clinic mastery shows fluent manding for help, but home and community probes show the learner still resorts to problem behavior when novel listeners or noisy stores are present. Caregivers rate the clinic program highly. Which programming emphasis BEST addresses the gap?",
    "C",
    [
      "Declare generalization automatic because caregivers like the clinic.",
      "Train only in the identical clinic booth forever and never probe other environments.",
      "Program generalization—vary listeners, settings, and distraction levels; teach caregivers as primary implementers; and verify performance in community contexts before treating clinic fluency as sufficient.",
      "Assume social validity ratings replace stimulus-control transfer needs.",
    ],
    [
      "Acceptability does not guarantee transfer.",
      "Clinic-only training is a classic train-and-hope pattern for community skills.",
      "Deliberate generalization programming and natural-environment verification are required for community-critical communication.",
      "Social validity matters but does not ensure stimulus control across contexts.",
    ],
  ),
  authored3(
    3042,
    "H",
    "A telehealth parent-coaching plan targets bedtime compliance. Video fidelity checks show parents skip planned guided compliance steps when siblings interrupt, and bedtime data worsen. The vendor urges adding a restrictive 'room lock' protocol via phone recommendation without in-home safety assessment. What is the MOST defensible move?",
    "D",
    [
      "Recommend locked egress immediately because telehealth precludes any coaching remediation.",
      "Ignore fidelity problems and raise mastery criteria on parent graphs alone.",
      "Discharge the family for sibling interruptions.",
      "Remediate coaching fidelity (BST via telehealth, simplify steps, plan for sibling interruptions) and complete appropriate safety/consent review before considering more restrictive environmental procedures.",
    ],
    [
      "Telehealth does not justify skipping less restrictive coaching fixes for restrictive locks.",
      "Outcome criteria without fidelity misdirect the intervention.",
      "Sibling interruptions call for plan adaptation, not automatic discharge.",
      "Integrity remediation and proper authorization precede restrictive escalation—especially remotely.",
    ],
  ),
  authored3(
    3043,
    "H",
    "A client's aggression decreases when a new medication is started during the same week a DRA plan begins. Graphs are labeled as DRA success only. The prescribing physician asks the BCBA whether behavioral conclusions should mention the medication change. What reporting/selection stance is MOST appropriate?",
    "B",
    [
      "Omit the medication from all discussion because behavior plans must appear solely responsible for funding.",
      "Acknowledge concurrent medication as a potential confound when interpreting DRA effects; coordinate with the medical team and avoid attributing change solely to DRA until designs or logic can separate influences.",
      "Stop all behavioral measurement whenever medication starts.",
      "Claim medication is irrelevant to aggression if a phase line for DRA exists.",
    ],
    [
      "Funding optics do not justify omitting known confounds.",
      "Honest interpretation requires noting concurrent medical changes that may influence behavior and coordinating care.",
      "Measurement remains essential; stopping data worsens interpretation.",
      "Phase lines do not erase pharmacological confounds.",
    ],
  ),
  authored3(
    3044,
    "H",
    "For a student with strong peer interest, a peer-mediated plan teaches classmates to prompt and reinforce social initiations during recess. Adult-mediated prompting works in clinic but has failed to maintain at recess due to staffing. Peers assent to participate with training. Which selection rationale is MOST sound?",
    "A",
    [
      "Peer mediation can improve contextual fit and maintenance in recess when peers are trained, supported, and willing—addressing a setting where adult density is insufficient.",
      "Peers must never implement any prompts because only BCBAs may speak to clients.",
      "Peer plans should replace functional assessment entirely.",
      "Choose peer mediation only to reduce documentation of adult responsibilities without training peers.",
    ],
    [
      "Peer-mediated intervention is a recognized approach for social contexts when designed and supervised appropriately.",
      "Trained peers can participate in support roles under program design; the vignette does not assign assessment/plan authority to peers.",
      "Function/context analysis still informs what peers should reinforce.",
      "Untrained peer use for convenience abandons integrity and dignity safeguards.",
    ],
  ),
  authored3(
    3045,
    "H",
    "A toddler's caregivers want language growth during daily routines. The learner satiates quickly in table DTT and shows more mands during snack preparation. Staffing allows either dense DTT or incidental teaching in routines. Which selection BEST matches learner response patterns and family goals?",
    "C",
    [
      "Mandate exclusive DTT because incidental teaching is not behavior analysis.",
      "Use only unstructured exposure with no planned prompting or reinforcement.",
      "Prioritize incidental/milieu teaching in motivating routines (e.g., snack prep) with planned prompts and contingent reinforcement, using table DTT selectively if needed for specific targets.",
      "Ignore caregiver goals and choose whichever method fills the most billable table hours.",
    ],
    [
      "Incidental teaching is a well-established ABA approach.",
      "Complete lack of programmed contingencies undercuts skill building.",
      "Matching teaching format to motivating contexts and family priorities improves fit when DTT satiation is evident.",
      "Billing convenience is not a clinical selection criterion over learner response and goals.",
    ],
  ),
  authored3(
    3046,
    "H",
    "A delay-tolerance program gradually increases wait time for a requested item after a calm request. Data show success at 30 s, but staff jump to 10 min after one good day because a supervisor wants 'faster results' for a tour. Problem behavior returns. What parameter decision is MOST data-based?",
    "B",
    [
      "Keep jumping criteria after single successful sessions to impress visitors.",
      "Advance wait criteria gradually based on meeting predetermined performance rules; resume a previously successful shorter delay and retune the thinning schedule rather than taking large unsupported jumps.",
      "Abandon delay tolerance permanently after one setback.",
      "Replace waiting goals with continuous free access forever without teaching tolerance.",
    ],
    [
      "Tour optics do not justify criterion jumps that break the thinning plan.",
      "Schedule thinning should follow performance criteria; large jumps commonly occasion relapse.",
      "A setback after an oversized jump is a reason to repair the schedule, not scrap the goal.",
      "Some contexts require tolerance skills; continuous free access may not meet caregiver goals.",
    ],
  ),
  authored3(
    3047,
    "H",
    "A treatment package (visual supports + DRA + scheduled breaks) reduced transition problem behavior. Leadership wants to cut all components at once at discharge to 'test toughness.' The family will continue services in a new school with partial staffing. What maintenance selection is MOST appropriate?",
    "D",
    [
      "Withdraw all supports simultaneously without programming maintenance or caregiver/school training.",
      "Keep the densest clinic package forever with no plan to thin or transfer.",
      "Hide effective components from the new school to avoid 'dependency' narratives.",
      "Systematically thin and simplify to the leanest effective supports, train receiving implementers, and probe maintenance under new-school conditions before full discharge.",
    ],
    [
      "Abrupt full withdrawal for a toughness test risks relapse and abandons maintenance programming.",
      "Never thinning or transferring is often unsustainable and not required for success.",
      "Withholding effective supports from receiving environments harms continuity of care.",
      "Maintenance and generalization programming—with orderly thinning and implementer training—supports durable outcomes.",
    ],
  ),
  authored3(
    3048,
    "H",
    "A BCBA must choose between a lengthy packaged social curriculum with weak individualization and a shorter, function-informed plan targeting the two social situations that occasion the client's aggression (game losing and waiting turns). Time and assent for long drills are limited. Which selection is MOST defensible?",
    "A",
    [
      "Select the individualized, function-informed targets tied to the evocative situations, rather than a lengthy generic package that consumes assent and time without addressing those contingencies.",
      "Choose the longest curriculum available so binders look comprehensive to auditors.",
      "Avoid addressing game losing because packaged curricula omit it.",
      "Prioritize curriculum brand recognition over the client's identified establishing operations.",
    ],
    [
      "Domain H favors precise, function- and context-matched targets when broad packages poorly fit needs and assent limits.",
      "Length and optics are not clinical efficacy criteria.",
      "Omitting known evocative contexts leaves critical risks unaddressed.",
      "Brand recognition does not outrank individualized assessment.",
    ],
  ),
  authored3(
    3049,
    "H",
    "Staff want to use overcorrection for messy locker clean-up after a single incident, without trying prompting, organized materials, or differential reinforcement of timely clean-up. The learner has no history of dangerous behavior during clean-up. What is the MOST appropriate least-restrictive selection response?",
    "C",
    [
      "Approve overcorrection immediately as the default cleanliness curriculum.",
      "Use overcorrection because it is always more 'educational' than reinforcement.",
      "Implement less restrictive skill-building and reinforcement strategies first; reserve more aversive overcorrection for situations where milder strategies fail or risk justifies it, with proper consent.",
      "Ignore clean-up goals entirely to avoid any prompting.",
    ],
    [
      "Defaulting to overcorrection skips least-restrictive sequencing.",
      "Aversiveness does not equal superior education when milder tactics are untried.",
      "Least-restrictive practice tries effective positive/skill-based approaches before punitive or effortful corrective packages.",
      "Goals can be taught with appropriate prompts and reinforcement; avoidance of all teaching is unnecessary.",
    ],
  ),
  authored3(
    3050,
    "H",
    "A competing-stimulus assessment identifies headphones plus a fidget that reduce hand mouthing during independent work. Teachers can implement these with high fidelity. A consultant instead pushes a complex multi-step interruption protocol teachers say they cannot run during reading groups. Hand mouthing primarily interferes during those groups. Which selection priority should win?",
    "B",
    [
      "Adopt the complex protocol because consultant seniority outranks fidelity feasibility.",
      "Prefer the assessment-supported competing stimuli teachers can implement with integrity during the actual routines where hand mouthing interferes.",
      "Select neither and wait for a perfect intervention that needs no teacher time.",
      "Use the complex protocol only on paper for audits while teachers do nothing in reading groups.",
    ],
    [
      "Seniority does not override contextual fit and integrity.",
      "Effective interventions are those matched to assessment and implementable in the performance setting—competing stimuli win on both counts here.",
      "Waiting for zero-effort perfection abandons current needs.",
      "Paper-only plans without implementation fail clients and misrepresent services.",
    ],
  ),
];

export const EXPANDED3_I: BDSQuestion[] = [
  authored3(
    3061,
    "I",
    "A BCBA's supervisory caseload grows to the point that scheduled observations are repeatedly canceled, feedback is months delayed, and several RBTs escalate protocol errors. Leadership frames the cancellations as a badge of being 'in demand.' What supervisory response is MOST aligned with caseload and competence obligations?",
    "C",
    [
      "Continue accepting cases without limit because demand proves adequate supervision is occurring.",
      "Cancel documentation of missed observations so audits look clean.",
      "Recognize supervisory volume as compromising effective oversight—reduce caseload or obtain additional qualified supervisors, restore timely observation/feedback, and document the capacity problem up the chain.",
      "Replace all observation with annual congratulatory emails to save time.",
    ],
    [
      "Demand is not evidence that supervision quality meets standards.",
      "Falsifying or omitting missed contacts worsens documentation integrity.",
      "Supervisors must maintain workloads that allow effective observation, feedback, and client protection—and remediate when capacity fails.",
      "Email praise cannot replace performance-based supervision contacts.",
    ],
  ),
  authored3(
    3062,
    "I",
    "During feedback, a supervisor repeatedly mocks a trainee's accent and says the trainee's 'culture doesn't value precision,' after which the trainee stops asking clarifying questions and fidelity drops. Client programs are affected. What supervisory correction is MOST appropriate?",
    "A",
    [
      "Stop demeaning cultural/linguistic comments; deliver respectful, criterion-referenced feedback focused on observable performance; and repair the supervisory climate so questions and skill building can resume.",
      "Increase public mockery to toughen the trainee for the field.",
      "Interpret silence as proof the trainee needs no further supervision contacts.",
      "Transfer all of the trainee's cases to unpaid peers without addressing the hostile feedback pattern.",
    ],
    [
      "Culturally respectful, behavior-specific feedback is required; harassment undermines learning and client welfare.",
      "Mockery is not an evidence-based training strategy.",
      "Withdrawal from questioning is a warning sign, not mastery.",
      "Peer dumping without fixing supervisory conduct abandons responsibility.",
    ],
  ),
  authored3(
    3063,
    "I",
    "A clinic wants to scale training by having a few senior RBTs teach newcomers. The BCBA designs pyramidal training: the BCBA trains senior RBTs to mastery on BST delivery, then observes them training newcomers with fidelity checklists. An administrator instead wants seniors to 'just show new hires once' with no checks. Which structure should the BCBA insist on?",
    "D",
    [
      "One unobserved demonstration with no rehearsal or fidelity criteria.",
      "Pyramidal training without any BCBA oversight of the senior trainers.",
      "Newcomer self-study only, skipping senior RBTs entirely when scaling is desired.",
      "Competency-based pyramidal training—train the trainers to mastery, verify their BST fidelity with newcomers, and maintain supervisory accountability for outcomes.",
    ],
    [
      "Show-once training without rehearsal/feedback is weak for critical skills.",
      "Pyramid models still require supervisory oversight of trainer fidelity.",
      "Self-study alone rarely builds implementation fluency at scale.",
      "Effective pyramidal systems preserve BST logic and verification at each tier under BCBA accountability.",
    ],
  ),
  authored3(
    3064,
    "I",
    "A supervisee's graphed prompt-fade integrity is reviewed only in quarterly meetings, long after errors have practiced into habit. Clients plateau. Which performance-monitoring change is MOST likely to improve supervisee skills and client outcomes?",
    "B",
    [
      "Keep quarterly-only review because frequent monitoring might discourage staff.",
      "Increase timely observation and graphed feedback closer to performance—review integrity data frequently enough to catch and correct errors before they stabilize.",
      "Stop collecting integrity data to reduce supervisee anxiety.",
      "Post private corrective details on a public staff social media page for transparency.",
    ],
    [
      "Delayed quarterly feedback weakens contingency contact with session behavior.",
      "Frequent, timely progress monitoring and feedback are core supervision practices for performance improvement.",
      "Dropping measurement removes the basis for targeted feedback.",
      "Public shaming violates professionalism and harms the supervisory relationship.",
    ],
  ),
  authored3(
    3065,
    "I",
    "After repeated BST cycles, an RBT still fails critical safety steps during crisis drills. Clients on that caseload include individuals with elopement risk. The RBT is popular with families. What supervisory action is MOST appropriate?",
    "C",
    [
      "Ignore safety failures because popularity predicts clinical competence.",
      "Assign the most dangerous cases to accelerate learning by exposure alone.",
      "Restrict or remove independent performance of failed safety-critical duties until mastery is demonstrated; intensify training; document; and reassign cases as needed to protect clients.",
      "Falsify drill scores so schedules remain uninterrupted.",
    ],
    [
      "Popularity is not a safety competency.",
      "Exposure without mastery increases risk rather than remediating it.",
      "Supervisors must protect clients by limiting practice to demonstrated competencies and documenting remediation—especially for safety skills.",
      "Falsification endangers clients and violates documentation standards.",
    ],
  ),
  authored3(
    3066,
    "I",
    "A school asks a BCBA whose competence is early-learner vocal mand training to supervise a complex adolescent feeding-aversion case involving medical coordination the BCBA has never managed. No mentoring consult is arranged. What is the MOST responsible supervisory stance?",
    "A",
    [
      "Decline or obtain appropriate consultation/competence development before supervising that case; do not practice or supervise beyond competence in ways that risk clients.",
      "Accept immediately because BCBA certification implies universal competence in all populations and procedures.",
      "Have an untrained RBT lead medical–behavioral coordination while the BCBA remains silent.",
      "Supervise only the billing codes and avoid reading clinical details to limit liability.",
    ],
    [
      "Scope and competence limits require referral, co-supervision, or skill acquisition before accepting cases outside expertise.",
      "Credentialing is not infinite competence across all specialties.",
      "Delegating complex coordination to untrained staff worsens risk.",
      "Billing-only 'supervision' is supervisory abandonment.",
    ],
  ),
  authored3(
    3067,
    "I",
    "An administrator demands that a BCBA email the full staff list detailing one trainee's confidential performance problems 'as motivation for everyone.' The trainee has not consented to broad disclosure. What should the BCBA do?",
    "D",
    [
      "Send the email as requested to maximize public embarrassment and motivation.",
      "Post the trainee's evaluation scores on the clinic waiting-room board.",
      "Discuss the trainee's private mental-health details in the all-staff email for context.",
      "Refuse broad disclosure of confidential supervisee performance information; provide feedback privately (and to necessary supervisors only) consistent with policy and professionalism.",
    ],
    [
      "Public embarrassment is not an appropriate or ethical motivation strategy.",
      "Waiting-room posting violates confidentiality and dignity.",
      "Unnecessary sensitive disclosures compound the violation.",
      "Supervisee performance information should be handled confidentially with need-to-know limits.",
    ],
  ),
  authored3(
    3068,
    "I",
    "Tele-supervision is used for a rural RBT. Connections frequently freeze during the only observation windows, and the BCBA cannot see prompting hands or client safety during transitions. The company still logs full observation credit. What adjustment is MOST appropriate?",
    "B",
    [
      "Keep logging full observation credit whenever a call was attempted, even if video failed.",
      "Ensure observation quality is sufficient to evaluate performance—reschedule, use reliable technology, arrange periodic in-person observation when needed, and record only contacts that actually permit adequate observation.",
      "Abandon all observation requirements for rural services permanently.",
      "Ask the RBT to narrate competence without any visual observation forever.",
    ],
    [
      "Attempted calls that fail to show performance should not be documented as completed observations.",
      "Supervision must actually allow evaluation of service delivery; technology and modality must support that function.",
      "Geography does not waive observation obligations.",
      "Self-narration cannot replace observing critical implementation elements.",
    ],
  ),
  authored3(
    3069,
    "I",
    "A clinic delivers only large-group didactic supervision meetings and never individualizes observation or feedback. Several trainees have unique skill deficits invisible in group lecture. Which supervision mix is MOST appropriate?",
    "A",
    [
      "Combine group sessions for shared content with individualized observation and performance feedback tailored to each supervisee's assessed needs and cases.",
      "Use group lecture exclusively because it is efficient for payroll.",
      "Avoid observing individuals to prevent discomfort.",
      "Substitute motivational posters for case-specific feedback.",
    ],
    [
      "Effective systems blend efficient group teaching with individualized performance-based supervision.",
      "Efficiency alone cannot meet individualized competency needs.",
      "Discomfort does not remove observation duties.",
      "Posters do not shape protocol skills.",
    ],
  ),
  authored3(
    3070,
    "I",
    "A BCBA wants to evaluate whether their own supervision is effective. Currently they track only hours logged, not whether supervisee integrity or client outcomes improve after feedback. What measurement focus BEST evaluates supervisory practices?",
    "C",
    [
      "Hours logged alone as a sufficient outcome of excellent supervision.",
      "Supervisee friendliness ratings without reference to fidelity or client data.",
      "Monitor supervisee performance (e.g., integrity, skill probes) and relevant client outcomes in relation to supervisory interventions—not contact minutes alone.",
      "Count the number of motivational quotes emailed each month.",
    ],
    [
      "Contact time is necessary but not sufficient evidence of supervisory effectiveness.",
      "Rapport matters but cannot replace performance and outcome indicators.",
      "Supervision is judged by changes in supervisee competence and client benefit linked to supervisory procedures.",
      "Quote volume is not a performance metric.",
    ],
  ),
  authored3(
    3071,
    "I",
    "A fieldwork trainee discloses severe burnout and asks to skip observations this month while still counting full unrestricted hours for activities not performed. Clients would be left without planned program updates. What supervisory response BEST balances trainee support and obligations?",
    "B",
    [
      "Approve falsified hours and skipped observations to be supportive.",
      "Support the trainee's health (refer to appropriate resources, adjust workload if feasible) while maintaining honest documentation, required oversight for client welfare, and accurate hour attestation only for activities completed.",
      "Publicly shame the trainee for burnout in group supervision.",
      "Require the trainee to hide distress and continue unsafe caseloads without accommodation discussion.",
    ],
    [
      "Supportiveness does not include false documentation or abandoning observation duties.",
      "Ethical supervision can include humane workload/support measures without misrepresentation or client neglect.",
      "Shaming worsens distress and climate.",
      "Forcing concealment and unsafe loads is neither supportive nor responsible.",
    ],
  ),
  authored3(
    3072,
    "I",
    "An owner instructs an RBT to bill a CPT code for a session that did not occur and to mark supervision as completed. The RBT reports this to the supervising BCBA and fears retaliation. What is the MOST appropriate supervisory action?",
    "D",
    [
      "Tell the RBT to comply quietly because owners define ethical billing.",
      "Help falsify the note to protect the company's revenue this quarter.",
      "Ignore the report to avoid conflict and hope audits never happen.",
      "Instruct the RBT not to falsify records; correct or prevent the false entries; protect the reporter from retaliation to the extent possible; and escalate through appropriate organizational and, if required, external channels.",
    ],
    [
      "Owner directives do not legalize fraudulent billing or false supervision logs.",
      "Supervisors must not participate in falsification.",
      "Ignoring known fraud abandons ethical and supervisory duties.",
      "Supervisors address documentation integrity, support honest reporting, and escalate appropriately.",
    ],
  ),
  authored3(
    3073,
    "I",
    "A BCBA supervises services in a classroom where an OT and SLP also work with the same student. The RBT receives conflicting instructions. The BCBA has not conferred with the other professionals. What supervisory practice is MOST appropriate?",
    "A",
    [
      "Coordinate with collaborating professionals to align goals and procedures within scope, clarify the RBT's instructions, and document the integrated plan so supervisees are not left resolving interdisciplinary conflicts alone.",
      "Order the RBT to ignore all non-ABA professionals permanently.",
      "Have the RBT invent a compromise protocol without BCBA or collaborator input.",
      "Avoid communication with other disciplines to protect 'ABA purity.'",
    ],
    [
      "Interdisciplinary coordination is part of responsible case oversight and supervisee clarity.",
      "Blanket noncollaboration can harm clients and confuse staff.",
      "Unsupervised improvised compromises abandon supervisory control.",
      "Isolationism is not a professional supervision standard.",
    ],
  ),
  authored3(
    3074,
    "I",
    "An RBT's certification anniversary is approaching. The BCBA realizes required supervision percentages were met some months but that several competency areas (e.g., crisis supports) were never reassessed after a protocol overhaul. Schedules are busy. What should the BCBA prioritize?",
    "C",
    [
      "Skip competency reassessment because anniversary dates automatically reset skill mastery.",
      "Sign renewal-related verifications without reviewing current performance to save time.",
      "Reassess critical competencies under the updated protocols, provide training where gaps appear, and ensure supervision documentation accurately reflects current performance before attesting to readiness.",
      "Transfer attestation to the RBT's roommate who is not a supervisor.",
    ],
    [
      "Calendar anniversaries do not restore competence after procedure changes.",
      "Attestation without current knowledge is dishonest.",
      "Ongoing competency verification after material protocol changes is a core supervisory duty tied to client safety.",
      "Attestation cannot be delegated to unqualified persons.",
    ],
  ),
  authored3(
    3075,
    "I",
    "A supervisor's feedback always sandwiches critical corrections between lengthy unrelated praise, leaving trainees unsure which pinpoints to change. Integrity on the critiqued steps remains low. What feedback adjustment is MOST consistent with performance-based supervision?",
    "B",
    [
      "Keep vague sandwiching so trainees never feel discomfort.",
      "Deliver clear, behavior-specific praise for correct steps and equally clear, timely corrective feedback tied to observable criteria—without burying the pinpoint in unrelated fluff that obscures what to change.",
      "Use only sarcasm so trainees 'figure out' the expectations.",
      "Avoid naming the incorrect step to protect confidence, even when clients are affected.",
    ],
    [
      "Comfort-preserving vagueness fails to shape accurate performance.",
      "Effective feedback is specific, contingent, and understandable; excessive unrelated sandwiching can dilute the corrective signal.",
      "Sarcasm is not professional performance feedback.",
      "Withholding the pinpoint prevents correction while clients bear the cost.",
    ],
  ),
  authored3(
    3076,
    "I",
    "A BCBA models a complex stimulus-control transfer perfectly once, then sends the trainee into live sessions without rehearsal or feedback. Errors recur. The BCBA insists modeling alone is 'gold-standard BST.' What component is MOST critically missing?",
    "A",
    [
      "Rehearsal/practice with performance-based feedback (and repeated probing) until the trainee meets mastery—modeling alone is incomplete BST.",
      "Longer emails describing the model without any practice.",
      "Removing the modeled exemplar so trainees invent steps themselves under client risk.",
      "Counting the model as unrestricted fieldwork hours for the trainee without the trainee performing.",
    ],
    [
      "BST includes instructions, modeling, rehearsal, and feedback; omitting rehearsal/feedback leaves skills unmastered.",
      "More description without practice does not complete BST.",
      "Removing models increases errors under client-risk conditions.",
      "Watching a model is not the same as performing supervised activities.",
    ],
  ),
  authored3(
    3077,
    "I",
    "Supervision logs list dates and durations but never content, cases discussed, skills practiced, or feedback given. During an audit readiness review, trainees cannot recall what was supervised in many 'contacts.' What documentation improvement is MOST needed?",
    "D",
    [
      "Keep duration-only logs because content notes create liability.",
      "Backfill invented detailed narratives for months of empty logs before the audit.",
      "Stop logging supervision entirely to reduce paperwork.",
      "Record accurate, contemporaneous content—observations performed, skills targeted, feedback/outcomes, and follow-up plans—sufficient to verify that supervision actually occurred as claimed.",
    ],
    [
      "Content documentation supports accountability; blank duration logs are weak evidence of supervision quality.",
      "Fabricating retrospective detail is dishonest.",
      "Eliminating logs worsens compliance and continuity.",
      "Meaningful supervision records capture what occurred, not merely that a clock was running.",
    ],
  ),
  authored3(
    3078,
    "I",
    "A vendor offers the supervising BCBA personal bonuses for each family a trainee steers toward the vendor's supplemental product. The BCBA asks trainees to recommend the product during sessions without disclosing the bonus. What conflict-of-interest response is MOST appropriate?",
    "C",
    [
      "Accept the bonuses and keep trainees unaware so recommendations sound more authentic.",
      "Require trainees to meet product-sales quotas as a competency gate.",
      "Refuse arrangements that compromise objectivity; do not use supervisees to steer families for personal gain; disclose and eliminate conflicts according to policy/ethics; and base recommendations on client needs and evidence.",
      "Increase bonuses for trainees who hide the arrangement from caregivers.",
    ],
    [
      "Concealed personal gain undermines informed caregiver decision-making and supervisory integrity.",
      "Sales quotas are not clinical competencies.",
      "Supervisors must avoid exploiting supervisees and families through undisclosed conflicts and keep recommendations client-centered.",
      "Recruiting trainees into concealment worsens the ethical breach.",
    ],
  ),
  authored3(
    3079,
    "I",
    "A supervisee reports observing another RBT use an unauthorized prone restraint and falsify the session note. The supervisee fears being labeled 'difficult.' The supervising BCBA has not yet acted. What supervisory response is MOST appropriate?",
    "B",
    [
      "Tell the supervisee to stay quiet because reporting harms team morale.",
      "Take the report seriously—ensure client safety immediately, investigate per policy, correct documentation and practice, protect the reporter from retaliation, and escalate as required; reinforce that reporting safety/ethics concerns is expected professional behavior.",
      "Punish the reporting supervisee for creating paperwork.",
      "Destroy related camera footage to simplify the file before any review.",
    ],
    [
      "Silencing safety reports endangers clients and punishes integrity.",
      "Supervisors must act on credible safety and documentation concerns, protect good-faith reporters, and uphold truthful records.",
      "Retaliation against reporters is inappropriate and chilling.",
      "Destroying evidence obstructs accountability and worsens risk.",
    ],
  ),
];
