/**
 * Mock Exam 2 — expanded authored items, Domains E (Ethics) and G (Behavior-change procedures).
 * Independent study only. Not affiliated with the BACB.
 */
import type { BDSQuestion } from "@/lib/content-types";
import { authored2 } from "@/content/mockExam/exams/bcbaPractice2/expandedAuthoredHelper";

export const EXPANDED2_E: BDSQuestion[] = [
  authored2(
    2401,
    "E",
    "A BCBA licensed and authorized only in State A begins thrice-weekly telehealth caregiver coaching for a learner who recently moved to State B. Operations staff say 'telehealth is telehealth' and want sessions billed under the original authorization. The BCBA has not verified State B practice rules, temporary permits, or payer telehealth location requirements. What should the BCBA do FIRST?",
    "C",
    [
      "Continue sessions unchanged because the original consent form listed 'home-based services' generally.",
      "Increase session length to front-load progress before any regulator notices the address change.",
      "Pause or restructure services until lawful practice authorization, payer rules, and informed consent for the new service location are verified and documented.",
      "Ask the RBT in State A to appear on camera so the case 'looks local' while the BCBA coaches from elsewhere.",
    ],
    [
      "Prior consent for a different arrangement does not automatically authorize cross-jurisdiction practice.",
      "Accelerating billable contact does not cure unauthorized practice risk.",
      "Responsible practice requires confirming jurisdiction, payer, and consent conditions before continuing remote services in a new state.",
      "Misrepresenting who is providing or where services occur compounds integrity and regulatory violations.",
    ],
  ),
  authored2(
    2402,
    "E",
    "A caregiver offers to renovate the BCBA's kitchen at a steep discount if the BCBA 'keeps the hours high' and writes a glowing letter supporting an insurance appeal. The BCBA has unpaid personal renovation quotes pending. Which response BEST manages the conflict?",
    "A",
    [
      "Decline the renovation barter and any linkage between clinical recommendations and personal financial benefit; document the offer and keep clinical decisions independent.",
      "Accept the discount only if the letter is written after renovations finish.",
      "Accept free labor but refuse the letter to 'split the difference.'",
      "Have the RBT accept the renovation offer so the BCBA's name stays off the arrangement.",
    ],
    [
      "Bartering and personal benefit tied to clinical advocacy create conflicts that can impair objectivity and exploit the professional relationship.",
      "Delaying the letter still trades clinical influence for personal gain.",
      "Partial acceptance of the conflict still compromises independence.",
      "Routing the arrangement through a supervisee does not remove the BCBA's conflict or responsibility.",
    ],
  ),
  authored2(
    2403,
    "E",
    "Clinic leadership wants the BCBA to enroll current clients in an internal 'outcome study,' randomly assigning half to a novel punishment package. No IRB or equivalent review exists, guardians received only a marketing flyer, and declining research would not change access to standard care—yet staff imply nonparticipants are 'less committed families.' What is the MOST ethical research stance?",
    "D",
    [
      "Enroll everyone immediately because internal QI never requires consent.",
      "Randomize first and seek consent only from families assigned to punishment.",
      "Threaten discharge for families who decline so sample size stays adequate.",
      "Do not implement the study under these conditions; require appropriate review, truly voluntary informed consent, clear separation from clinical access, and scientifically and ethically justified procedures.",
    ],
    [
      "Labeling something QI does not erase consent and review duties for experimental, higher-risk manipulations.",
      "Consent must precede assignment; restricting consent to one arm is coercive and incomplete.",
      "Linking clinical access to research participation is coercive.",
      "Human-subjects protections, voluntary consent, and ethical justification are required before experimental assignment to restrictive procedures.",
    ],
  ),
  authored2(
    2404,
    "E",
    "An attorney asks a newly certified BCBA—with no forensic training—to provide courtroom opinions on parental fitness and to 'stretch' graph interpretations to favor one custody party who referred several lucrative cases. The BCBA's involvement to date was classroom consultation only. Which action is MOST appropriate?",
    "B",
    [
      "Offer sweeping parental-fitness conclusions to protect the referral pipeline.",
      "Limit opinions to data and scope actually within competence; decline advocacy-driven distortions and forensic conclusions outside training and the professional relationship.",
      "Edit graphs to emphasize only favorable weeks if the attorney promises confidentiality.",
      "Have an RBT testify to clinical opinions under the BCBA's credentials.",
    ],
    [
      "Referral volume does not justify exceeding competence or becoming a biased advocate.",
      "Ethics require honesty, scope limits, and refusal to misrepresent data or offer opinions beyond competence and role.",
      "Selective distortion for litigation is falsification regardless of promised secrecy.",
      "Credential substitution and having unqualified staff offer clinical opinions is misrepresentation.",
    ],
  ),
  authored2(
    2405,
    "E",
    "After a difficult IEPs season, a client's adult sibling—who also coordinates transportation—texts the BCBA late at night with romantic invitations and proposes meeting off the clock 'as friends who already share so much.' The BCBA finds the attention flattering but recognizes evaluative and confidentiality entanglements. What should the BCBA do?",
    "C",
    [
      "Begin dating quietly and transfer the case only if a breakup occurs.",
      "Continue clinical work while using a personal dating app profile that lists the client's school.",
      "Decline the romantic relationship, clarify professional boundaries in a documented professionally appropriate manner, and arrange reassignment if objectivity or client welfare could be impaired.",
      "Ask the sibling to keep romance secret from guardians so services can continue uninterrupted.",
    ],
    [
      "Romantic involvement with someone closely tied to the client creates multiple-relationship and exploitation risks.",
      "Publicly linking a dating profile to the client's school adds confidentiality harm.",
      "Avoiding sexual/romantic multiple relationships and protecting objectivity—via boundary clarification and reassignment when needed—aligns with ethical practice.",
      "Secrecy intensifies risk and undermines informed involvement of decision-makers.",
    ],
  ),
  authored2(
    2406,
    "E",
    "During a home session, an RBT privately tells the BCBA that a caregiver struck the learner hard enough to leave marks after a toileting accident, then asked staff 'not to write that down.' The learner is currently safe in the session room. Mandated-reporting laws in the jurisdiction cover suspected abuse. What is the BCBA's BEST next step?",
    "A",
    [
      "Follow mandated-reporting and organizational protective procedures promptly, document facts objectively, and do not conceal the allegation because a caregiver requested silence.",
      "Wait two weeks to see whether marks fade before deciding.",
      "Rewrite the session note to omit injuries so the therapeutic relationship survives.",
      "Confront the caregiver on social media to create public accountability.",
    ],
    [
      "Suspected abuse triggers legal and ethical duties to report through required channels; caregiver requests cannot override protection of the learner.",
      "Delay that serves avoidance can leave a child unprotected and may violate reporting timelines.",
      "Omitting material safety information falsifies the record and endangers the client.",
      "Public exposure is not a substitute for lawful reporting and may create new harms.",
    ],
  ),
  authored2(
    2407,
    "E",
    "A competing agency offers the BCBA a cash 'referral bounty' for each currently served family steered to their waitlist, plus gift cards if the BCBA downplays the current clinic's transition supports. Several families are mid-protocol and vulnerable to disruption. Which course BEST meets ethical obligations?",
    "D",
    [
      "Accept bounty payments if families are not told about the money.",
      "Steer only Medicaid families because 'they need options most.'",
      "Downplay transition risks so transfers happen faster and bounty thresholds are met.",
      "Refuse kickbacks, avoid steering based on personal profit, and provide honest, client-centered information about options and transition risks when transfers are clinically appropriate.",
    ],
    [
      "Hidden payment for referrals is a conflict and can exploit clients.",
      "Targeting a payer group for personal profit is discriminatory and still a kickback scheme.",
      "Minimizing risks for financial gain violates honesty and client-first duties.",
      "Client welfare and truthful guidance—not personal bounties—must drive recommendations about service changes.",
    ],
  ),
  authored2(
    2408,
    "E",
    "Payroll reveals that an RBT's certification lapsed three weeks ago, yet the person continued delivering protocol under the BCBA's cases and the agency kept billing mid-tier technician codes. The BCBA was never told. Leadership asks the BCBA to 'just sign corrected notes' implying continuous credentialing. What should the BCBA do?",
    "B",
    [
      "Sign the corrected notes to protect the team's jobs.",
      "Refuse to falsify credential status or notes, halt unauthorized practice under the BCBA's supervision, ensure only qualified personnel deliver services, and escalate billing/credential compliance through proper channels.",
      "Allow the person to continue if a certification exam is scheduled next month.",
      "Transfer documentation authorship to the learner's parent to avoid BCBA liability.",
    ],
    [
      "Falsifying records to hide a lapse compounds fraud and supervision failures.",
      "Supervisors must stop unauthorized practice, protect clients, and refuse dishonest documentation while pursuing compliance corrections.",
      "A future exam date does not restore present credentials or justify continued misrepresentation.",
      "Parents cannot assume clinical documentation roles to conceal agency noncompliance.",
    ],
  ),
  authored2(
    2409,
    "E",
    "For a conference poster, a BCBA removes last names but includes rare diagnosis combinations, exact school district, weekday service hours, and a photo of the learner's highly distinctive bedroom mural visible through a window. Guardians approved 'de-identified research sharing' years ago without seeing this poster. Re-identification by community members is realistic. Which action is MOST consistent with confidentiality?",
    "C",
    [
      "Present as planned because last names were removed.",
      "Present and offer attendees the family's address for 'collaboration.'",
      "Withdraw or substantially revise the poster to eliminate reasonably re-identifying details and media; obtain current, specific consent for any remaining sharable content.",
      "Post the full poster on LinkedIn first to test whether strangers recognize the child.",
    ],
    [
      "Removing names alone is insufficient when other identifiers make re-identification likely.",
      "Sharing addresses expands the breach.",
      "True protection requires minimizing re-identification risk and securing appropriate current authorization for public materials.",
      "Public testing of identifiability itself discloses protected information.",
    ],
  ),
  authored2(
    2410,
    "E",
    "The caseload BCBA is hospitalized unexpectedly after a serious accident. An on-call clinician covers emergencies for 48 hours, but no one has sent caregivers transition information, access instructions for crisis protocols, or interim contacts. The covering BCBA can view records today. What is the MOST responsible immediate priority?",
    "A",
    [
      "Establish interim clinical coverage clarity, notify caregivers of temporary contacts and how to access crisis procedures, and document continuity steps while longer-term reassignment is arranged.",
      "Leave messages unread until the hospitalized BCBA returns, however long that takes.",
      "Email entire chart PDFs to all caregivers' personal accounts for 'transparency.'",
      "Cancel all programming permanently without notice to simplify coverage.",
    ],
    [
      "Preventing abandonment during sudden unavailability requires timely caregiver notice, interim contacts, and accessible safety plans.",
      "Silence during a coverage gap risks abandonment and unsafe responding.",
      "Bulk unsecured chart transmission creates confidentiality violations.",
      "Permanent cancellation without process is abandonment, not continuity.",
    ],
  ),
  authored2(
    2411,
    "E",
    "An intake coordinator asks the BCBA to soft-reject referrals from families who use interpreters or who live in a stigmatized neighborhood, claiming 'those cases hurt our outcomes dashboard.' Clinically appropriate capacity exists. What should the BCBA do?",
    "D",
    [
      "Agree to the filter to protect marketing metrics.",
      "Accept only interpreter-using families if they pay cash above the fee schedule.",
      "Create a fake waitlist excuse exclusively for the targeted group.",
      "Refuse discriminatory exclusion, insist on equitable access policies, and report or escalate unlawful or unethical intake steering.",
    ],
    [
      "Outcome optics do not justify discriminatory denial of care.",
      "Surcharging protected or language-access needs is coercive and inequitable.",
      "Fabricated waitlists for a targeted group are dishonest and discriminatory.",
      "Ethical practice requires nondiscriminatory access and challenging systemic exclusion.",
    ],
  ),
  authored2(
    2412,
    "E",
    "A BCBA downloads a former employer's proprietary skills assessment, removes the logo, and plans to sell it inside a new private practice as an original tool. A colleague who helped build the assessment is never credited, and the old employment agreement prohibited taking work product. Which choice BEST addresses intellectual-property and honesty duties?",
    "B",
    [
      "Sell the relabeled tool; employment agreements never apply to clinical materials.",
      "Do not misappropriate or misrepresent the tool as original; use only materials the BCBA has rights to use, with accurate attribution and lawful permission where required.",
      "Sell it solely to out-of-state clients to avoid detection.",
      "Have an RBT listed as author to distance the BCBA from ownership claims.",
    ],
    [
      "Contractual and ethical rules still apply to clinical intellectual property.",
      "Honesty and respect for others' work product prohibit theft, misattribution, and unauthorized commercial reuse.",
      "Geographic workarounds do not make misappropriation ethical.",
      "False authorship adds misrepresentation.",
    ],
  ),
  authored2(
    2413,
    "E",
    "Parents demand immediate use of a contingent skin-shock device marketed online for self-injury after watching a viral video. No functional assessment is complete, medical and human-rights reviews are absent, less restrictive function-based options have not been tried, and the learner shows clear distress to pain-based videos. Clinic investors like the 'breakthrough' branding. What should the BCBA do?",
    "C",
    [
      "Order the device same-day to retain the contract.",
      "Begin shock trials secretly at school so parents see rapid change.",
      "Decline to implement; complete assessment, pursue least-restrictive function-based interventions, involve appropriate medical/ethical review, and obtain informed consent/assent processes before any restrictive procedure could even be considered.",
      "Trade shock implementation for a social-media testimonial about investor innovation.",
    ],
    [
      "Market pressure and parental demand do not justify unassessed highly restrictive punishment.",
      "Covert school implementation violates consent, transparency, and safety review duties.",
      "Restrictive/punitive technology requires rigorous justification, safeguards, and preferential use of less restrictive evidence-based options—not branding-driven adoption.",
      "Exchanging harmful procedures for publicity is exploitative.",
    ],
  ),
  authored2(
    2414,
    "E",
    "The BCBA owns a side company that sells chewable jewelry and sensory kits. Without disclosing ownership, the BCBA writes plans requiring families to purchase those exact products from the side company at retail markup, even when equivalent items are available cheaper elsewhere. Which correction is MOST ethical?",
    "A",
    [
      "Disclose the financial interest, remove coercive product steering, and recommend clinically justified options with transparent alternatives rather than self-dealing mandates.",
      "Increase markup because disclosure would 'confuse families.'",
      "Require purchases only from Medicaid families who 'won't notice.'",
      "List the RBT as the product recommender while retaining profits.",
    ],
    [
      "Undisclosed self-dealing impairs objectivity and can exploit clients; disclosure plus noncoercive, clinically justified recommendations are required.",
      "Avoiding disclosure to protect profit worsens the conflict.",
      "Targeting a payer group for undisclosed profit is exploitative.",
      "Using a supervisee as a front does not erase the BCBA's conflict.",
    ],
  ),
  authored2(
    2415,
    "E",
    "An employer learns a former client filed an ethics complaint related to documentation practices at the agency. Leadership drafts a statement for the BCBA to sign claiming the BCBA 'never saw irregularities'—a claim the BCBA knows is false—and threatens termination for refusal. What should the BCBA do?",
    "D",
    [
      "Sign the false statement to remain employed and later 'clarify privately.'",
      "Destroy personal notes that contradict the statement.",
      "Ask the former client to withdraw the complaint in exchange for free sessions.",
      "Refuse to sign false statements, preserve accurate records, and cooperate truthfully with proper investigative processes while seeking appropriate counsel/support for retaliation concerns.",
    ],
    [
      "Knowingly false statements in an ethics matter are themselves ethical violations.",
      "Destroying evidence obstructs investigation and violates integrity standards.",
      "Trading services to suppress a complaint is coercive and obstructive.",
      "Truthfulness, record integrity, and noncooperation with cover-ups are required even under job pressure.",
    ],
  ),
  authored2(
    2416,
    "E",
    "A payer's utilization reviewer demands the BCBA upload the learner's complete cumulative folder—including unrelated sexual-health notes from another provider, sibling mental-health records accidentally filed in the chart, and staff HR write-ups—into an unsecured portal shared with marketing vendors. Only a narrow progress summary is needed for the concurrent review. What is the BEST response?",
    "B",
    [
      "Upload everything requested to avoid payment delays.",
      "Disclose only the minimum necessary information through secure, authorized channels; redact or withhold nonnecessary third-party and irrelevant sensitive material per policy and law; clarify the review scope in writing.",
      "Email the full chart to the reviewer's personal Gmail for convenience.",
      "Post a redacted graph on Facebook and tell the reviewer to screenshot it.",
    ],
    [
      "Convenience and payment timing do not justify over-disclosure of sensitive information.",
      "Minimum-necessary and secure-transmission principles protect confidentiality while still meeting legitimate review needs.",
      "Personal email increases insecurity and often exceeds authorization.",
      "Social media is not an appropriate PHI channel for payer review.",
    ],
  ),
  authored2(
    2417,
    "E",
    "A fieldwork trainee asks the BCBA to attest to unrestricted supervision hours for weekends when the BCBA was out of the country and provided no contacts, observations, or feedback. The trainee offers to split a bonus if paperwork is signed by Monday's audit. Which action BEST upholds supervision integrity?",
    "C",
    [
      "Sign the attestation because the trainee is 'basically independent.'",
      "Sign only the hours and omit the bonus discussion from the file.",
      "Refuse to attest to supervision not provided, document the request, and report or correct any falsification attempts through appropriate channels.",
      "Allow the trainee to forge the BCBA's signature while the BCBA is abroad.",
    ],
    [
      "Independence impressions do not replace required supervised contacts.",
      "Signing false hours remains falsification even if the bribe is undocumented.",
      "Accurate supervision attestation is mandatory; refusing and addressing falsification attempts protects the profession and future clients.",
      "Forgery multiplies fraud and credentialing violations.",
    ],
  ),
];

export const EXPANDED2_G: BDSQuestion[] = [
  authored2(
    2501,
    "G",
    "Dressing is task-analyzed into eight links. The BCBA teaches and reinforces the first link to independence, then adds the second, then the third, progressing downstream until the full chain occurs in order. Earlier links remain in the sequence as later links are added. Which chaining method is described?",
    "B",
    [
      "Backward chaining beginning with the terminal link.",
      "Forward chaining, establishing the initial link first and advancing through subsequent links.",
      "Shape a single novel topography without sequenced links.",
      "Noncontingent reinforcement of clothing items on a fixed-time schedule.",
    ],
    [
      "Backward chaining starts at the end of the chain and moves upstream.",
      "Teaching the first step first and progressively adding later steps is forward chaining.",
      "The vignette specifies a task-analyzed chain, not undifferentiated shaping of one form.",
      "NCR does not teach sequenced independent links.",
    ],
  ),
  authored2(
    2502,
    "G",
    "A learner identifies the printed word 'STOP' only when a red octagon background is present. The BCBA gradually fades the octagon color and shape toward plain black text on white while keeping reinforcement for correct reading, until text alone controls the response. Which procedure is PRIMARY?",
    "A",
    [
      "Stimulus fading (within-stimulus feature fading) to transfer control to the critical textual stimuli.",
      "Escape extinction for incorrect readings only.",
      "Dependent group contingency for the reading group.",
      "Full physical guidance of eye gaze on every trial permanently.",
    ],
    [
      "Progressively altering stimulus features so the target stimulus gains control is stimulus fading.",
      "Extinction of errors is not the described transfer mechanism.",
      "No group payoff structure is described.",
      "Permanent full guidance prevents transfer to textual stimuli.",
    ],
  ),
  authored2(
    2503,
    "G",
    "Staff currently provide an immediate gestural prompt for hand-raising. The BCBA inserts a planned delay before the prompt—first 1 second, then 2, then 3—while independent raises contacted dense reinforcement. Prompted correct responses still earn reinforcement on a thinner schedule. Integrity tracks delay length per trial. Which prompt-fading approach BEST matches this plan?",
    "D",
    [
      "Most-to-least physical hierarchy without time delays.",
      "Simultaneous full prompting forever to prevent any errors.",
      "Removing all prompts overnight without a delay gradient.",
      "Progressive time delay to transfer stimulus control to the natural opportunity.",
    ],
    [
      "The vignette emphasizes increasing delay, not a physical prompt hierarchy.",
      "Permanent simultaneous prompting maintains prompt dependence.",
      "Abrupt removal lacks the programmed delay gradient described.",
      "Systematically lengthening the pre-prompt interval is progressive time delay.",
    ],
  ),
  authored2(
    2504,
    "G",
    "A high-school learner and BCBA write a signed agreement: complete three hygiene routines before 8:00 a.m. earns a negotiated Saturday community outing; missing the criterion postpones the outing by one week. Expectations, measurement, and renegotiation dates are explicit. Caregivers co-sign. Which procedure is this?",
    "C",
    [
      "NCR delivering outings every Saturday independent of hygiene.",
      "Respondent pairing of toothpaste with preferred music only.",
      "Contingency contracting specifying behavior, consequence, and parties' agreement.",
      "Exclusionary time-out contingent on each missed step.",
    ],
    [
      "Outings are contingent, not time-based free delivery.",
      "Respondent pairing alone does not capture the negotiated operant contract.",
      "Written/agreed specification of target behavior and contingent outcomes is contingency contracting.",
      "No time-out contingency is described as the primary procedure.",
    ],
  ),
  authored2(
    2505,
    "G",
    "After property destruction, a team proposes that the learner repeatedly restore the environment and then practice appropriate cleaning movements for several minutes (restitutional plus positive-practice overcorrection). No functional assessment is done, assent indicators are ignored, and safer reinforcement-based options are unused. As BCBA, which position BEST reflects ethical procedure selection?",
    "A",
    [
      "Decline overcorrection-as-first-line; complete assessment, prioritize less restrictive function-based reinforcement strategies, and require consent/assent review plus monitoring if any consequential procedure is later justified.",
      "Implement maximum-duration overcorrection immediately to 'send a message.'",
      "Add covert shock during restoration to speed compliance.",
      "Skip consent because overcorrection is 'just teaching responsibility.'",
    ],
    [
      "Effortful consequential procedures require strong justification, safeguards, and preferential use of less restrictive function-based options.",
      "Severity-first implementation without assessment violates least-restrictive practice.",
      "Covert aversives compound ethical violations.",
      "Moralized labels do not waive consent or assessment duties.",
    ],
  ),
  authored2(
    2506,
    "G",
    "A token economy is effective, but a teacher wants each instance of mild teasing to cost five tokens with no skill teaching, no functional hypothesis, and no floor protecting access to basic reinforcers. Teasing appears attention-maintained. Which modification BEST aligns with sound, ethical use of response cost?",
    "B",
    [
      "Implement the five-token fine immediately and remove the backup menu entirely.",
      "Pair any response-cost element with function-based teaching (e.g., appropriate attention mands), ensure fines cannot eliminate access to essentials, obtain consent, and verify attention extinction/alternative reinforcement integrity.",
      "Increase fines to twenty tokens whenever peers laugh.",
      "Apply response cost only when observers from the district visit.",
    ],
    [
      "Stripping reinforcers without teaching or functional alignment risks coercion and collapse of the system.",
      "Response cost, if used, should be embedded in a function-based package with safeguards, consent, and viable reinforcement alternatives—not standalone punitive fines.",
      "Escalating fines without function match increases aversiveness without fixing maintaining contingencies.",
      "Inconsistent, audience-driven punishment undermines integrity and ethics.",
    ],
  ),
  authored2(
    2507,
    "G",
    "A clinic debates exclusionary time-out (removal to a barren room) versus nonexclusionary time-out (ribbon/signal removing reinforcement while the learner stays) for loud interruptions maintained by peer laughter. Peers still laugh during exclusionary removals when staff discuss the event aloud. Which consideration BEST guides selection?",
    "C",
    [
      "Always choose the most isolating option first for rapid suppression.",
      "Prefer exclusionary time-out because peer laughter during removal is irrelevant.",
      "Select the least restrictive effective option that actually withholds the functional reinforcer; if peer attention continues during 'time-out,' redesign so the contingency is valid and safer alternatives are prioritized.",
      "Abandon all differential reinforcement because time-out branding is trendy.",
    ],
    [
      "Most isolating first violates least-restrictive practice.",
      "If peer attention continues, exclusionary removal may not function as time-out from the maintaining reinforcer.",
      "Time-out must be time-out from reinforcement; validity, restrictiveness, and function determine procedure choice.",
      "Trends do not replace function-based reinforcement programming.",
    ],
  ),
  authored2(
    2508,
    "G",
    "A teen's hair-pulling is treated with awareness training, a competing response (fist clench until urge passes), social support, and motivational review of inconvenience. Pulling decreases without programmed contingent shock. Which package is MOST precisely described?",
    "D",
    [
      "Forward chaining of salon appointments.",
      "NCR delivering combs every 30 seconds.",
      "Lag reinforcement for novel pulling topographies.",
      "Habit-reversal components emphasizing competing response and awareness training.",
    ],
    [
      "Chaining appointments does not match the competing-response package.",
      "Time-based comb delivery is not the described treatment.",
      "Lag schedules target variability, not habit-reversal competing responses.",
      "Awareness, competing response, and related supports constitute habit-reversal training.",
    ],
  ),
  authored2(
    2509,
    "G",
    "Escape-maintained noncompliance is high for worksheet initiation. Immediately before the target demand, the BCBA presents three rapid, easy instructions the learner already complies with at high rates, reinforces those, then presents the hard worksheet start. Compliance with initiation rises. Which antecedent strategy is PRIMARY?",
    "A",
    [
      "High-probability request sequence (behavioral momentum) preceding the low-p demand.",
      "Exclusionary time-out for each slow initiation.",
      "DRL for worksheet initiations.",
      "Stimulus equivalence matching-to-sample for worksheet icons only.",
    ],
    [
      "A burst of high-p requests before a low-p target is a high-p / momentum strategy.",
      "No time-out contingency is described as primary.",
      "DRL addresses rate limits, not pre-demand easy-request sequences.",
      "Equivalence training is not described.",
    ],
  ),
  authored2(
    2510,
    "G",
    "A learner rarely completes math warm-ups but readily plays a preferred tablet game. The BCBA arranges: first finish the warm-up to criterion, then immediately access three minutes of the tablet game. Warm-up completion increases. Which principle is being applied?",
    "B",
    [
      "Respondent extinction of tablet enjoyment.",
      "Premack principle—making a high-probability activity contingent on completing a lower-probability activity.",
      "Full extinction of all mands for the tablet.",
      "Group interdependent recess contingency.",
    ],
    [
      "The tablet remains reinforcing; it is not extinguished as a respondent CS procedure.",
      "Contingent access to a high-probability behavior as a reinforcer for a low-probability behavior is Premack.",
      "Mands are not placed on extinction in the vignette.",
      "No peer-group payoff is described.",
    ],
  ),
  authored2(
    2511,
    "G",
    "Two concurrent recreational tasks are available: Task A pays tokens on VR 5; Task B pays on VR 50. The learner allocates nearly all responding to A. Staff want more engagement with B without punishment. Preference for both tasks remains positive. Which schedule change BEST follows matching-law logic?",
    "C",
    [
      "Punish Task A responses with contingent reprimands only.",
      "Remove Task B entirely so choice disappears.",
      "Enrich Task B's reinforcement rate (and/or reduce Task A's relative richness) so allocation can shift without adding aversive consequences.",
      "Scold the learner for 'preferring the easy schedule.'",
    ],
    [
      "Punishment is unnecessary when relative reinforcement can be adjusted and raises ethical caution.",
      "Eliminating choice avoids teaching allocation under concurrent schedules.",
      "Relative rate of reinforcement governs allocation; enriching the neglected alternative is the constructive matching-based repair.",
      "Moralizing preference ignores schedule determinants.",
    ],
  ),
  authored2(
    2512,
    "G",
    "A learner's play comments are repetitive ('car goes'). The BCBA reinforces a comment only if it differs from the previous N reinforced comments (lag N), producing more varied phrases over sessions. Which procedure is this?",
    "A",
    [
      "Lag reinforcement schedule to increase response variability.",
      "DRI requiring silence incompatible with any commenting.",
      "Backward chaining of a single scripted sentence.",
      "Nonexclusionary time-out for novel comments.",
    ],
    [
      "Reinforcing responses that differ from recent responses is a lag schedule for variability.",
      "DRI silence would suppress commenting rather than diversify it.",
      "Chaining one script does not match lag contingencies on difference.",
      "Punishing novelty opposes the goal.",
    ],
  ),
  authored2(
    2513,
    "G",
    "Automatically maintained hand-biting decreases when the BCBA provides continuous access to competing matched stimulation (chewables and hand toys) and prompts engagement with those items during high-risk idle periods, without contingent reprimands. Which approach is PRIMARY in this phase?",
    "D",
    [
      "Positive punishment via contingent lemon juice.",
      "Escape extinction for academic demands only.",
      "Dependent hero group contingency for the class.",
      "Competing stimulus / enriched environment intervention reducing the EO for automatic hand-biting.",
    ],
    [
      "No contingent aversive is described; adding one would raise ethical caution without necessity here.",
      "Demand escape contingencies are not the focus of the idle-period package.",
      "No group payoff structure is described.",
      "Noncontingent access to competing stimulation is a common antecedent approach for automatic reinforcement problems.",
    ],
  ),
  authored2(
    2514,
    "G",
    "For shoe-tying, the instructor's hands shadow the learner's hands, providing only the minimum physical guidance needed moment-to-moment, then withdrawing as the learner moves independently within the same trial. Guidance increases briefly only when errors begin. Which prompting method is described?",
    "B",
    [
      "Stimulus shaping of laces into letters.",
      "Graduated guidance with moment-to-moment adjustment of physical support.",
      "Fixed full physical prompts on every trial for a month.",
      "Lag schedule for novel knot topographies.",
    ],
    [
      "Stimulus shaping alters materials, not hand-over-hand intensity within trials.",
      "Graduated guidance adjusts physical assistance continuously based on performance within the opportunity.",
      "Fixed full physical prompting lacks the within-trial withdrawal described.",
      "Lag schedules address variability, not physical guidance hierarchies.",
    ],
  ),
  authored2(
    2515,
    "G",
    "Acquisition trials on a difficult intraverbal are interspersed with previously mastered easy intraverbals at a high easy-to-hard ratio. Session cooperation improves and hard-trial accuracy rises compared with massed hard-only trials. Which programming tactic is PRIMARY?",
    "C",
    [
      "Extinction of all easy intraverbals.",
      "Exclusionary time-out after each hard-trial error.",
      "Task interspersal (easy-hard mix) to maintain reinforcement density and momentum during difficult teaching.",
      "Response cost of tokens for choosing easy trials.",
    ],
    [
      "Easy items are retained as interspersed reinforcers/momentum supports, not extinguished.",
      "Time-out is not the described mechanism.",
      "Mixing mastered easy tasks with hard tasks is task interspersal.",
      "Punishing selection of easy trials undermines the tactic.",
    ],
  ),
  authored2(
    2516,
    "G",
    "A supervisor proposes contingent forced exercise (e.g., repeated laps) after stereotypy because 'it tires them out,' with no functional assessment, no medical clearance, and no reinforcement-based plan. Stereotypy appears automatically maintained and not dangerous. What should the BCBA recommend?",
    "A",
    [
      "Reject contingent exercise as first-line aversive control; assess function, prioritize competing stimulation/DRA/antecedent enrichment, and require consent, medical input, and least-restrictive justification before any effortful punishment could be considered.",
      "Increase lap counts until stereotypy stops for a full day.",
      "Implement forced exercise secretly during recess.",
      "Replace exercise with contingent restraint without caregiver notice.",
    ],
    [
      "Contingent effort used as punishment requires high justification and is inappropriate as an unassessed default for nondangerous automatic stereotypy.",
      "Escalating aversives without assessment intensifies ethical and clinical risk.",
      "Covert punishment violates consent and transparency.",
      "Unconsented restraint is more restrictive and still unjustified here.",
    ],
  ),
  authored2(
    2517,
    "G",
    "A learner watches a peer model complete a grocery requesting chain on video, then imitates the chain with delayed prompts that fade. Independent community probes improve after multiple video exemplars across stores. Which instructional strategy is PRIMARY?",
    "D",
    [
      "Respondent conditioning using only grocery smells.",
      "NCR delivering groceries on a clock independent of requesting.",
      "Overcorrection for incorrect mands without modeling.",
      "Video modeling (observational learning) combined with prompted practice and exemplar diversity.",
    ],
    [
      "Smell pairing alone does not teach the request chain.",
      "Noncontingent grocery delivery bypasses mand training.",
      "Punishment without modeling is not described and is ethically unnecessary here.",
      "Demonstration via video plus practice and multiple exemplars is video modeling for generalization.",
    ],
  ),
  authored2(
    2518,
    "G",
    "After accuracy on letter sounds reaches 100% in acquisition, the BCBA shifts to brief, timed practice aiming for rapid correct rates with immediate feedback, then conducts retention checks days later. Accuracy stays high while rate increases. Which emphasis BEST names this phase?",
    "B",
    [
      "Baseline functional analysis of letter sounds.",
      "Fluency building (rate plus accuracy) with retention checks after acquisition.",
      "Full extinction of correct letter sounds.",
      "Positive practice overcorrection for every slow response as first-line punishment.",
    ],
    [
      "The phase follows acquisition; it is not an FA.",
      "Precision-teaching-style fluency work targets high rates of accurate responding and retention—not acquisition alone.",
      "Extinguishing correct responses opposes skill building.",
      "Default punishment for slow but correct responses is unnecessary and raises ethical caution when reinforcement-based fluency practice is available.",
    ],
  ),
  authored2(
    2519,
    "G",
    "Staff propose an escalating continuum: reprimand → response cost → exclusionary time-out → brief manual restraint—for mild off-task glancing, before any preference assessment, DRA for on-task, or antecedent revision. No crisis-level safety risk exists. Which BCBA decision BEST reflects ethical behavior-change procedure selection?",
    "C",
    [
      "Approve the full punishment ladder to demonstrate consistency.",
      "Start at restraint to save time climbing the ladder later.",
      "Reject punishment-first programming for mild off-task behavior; implement assessment-informed reinforcement and antecedent strategies first, and reserve restrictive consequation for justified, consented, monitored conditions only.",
      "Randomize which aversive is used daily so the learner cannot adapt.",
    ],
    [
      "Consistency does not justify unnecessary restrictive ladders.",
      "Starting at the most restrictive end violates least-restrictive ethics.",
      "Function-based reinforcement and antecedent interventions are first-line; punishment hierarchies for mild behavior without assessment are ethically and procedurally inappropriate.",
      "Unpredictable aversives increase coercion without clinical justification.",
    ],
  ),
];
