/**
 * Authored Mock Exam 2 expanded items — Domains B, C, F.
 * Independent study content only; not affiliated with the BACB.
 * Harder application vignettes than Mock Exam 1; unique stems.
 */
import type { BDSQuestion } from "@/lib/content-types";
import { authored2 } from "@/content/mockExam/exams/bcbaPractice2/expandedAuthoredHelper";

export const EXPANDED2_B: BDSQuestion[] = [
  authored2(
    2101,
    "B",
    "A learner’s aggression was historically reinforced by escape. Staff then reinforced an alternative break card on FR 1 while placing aggression on extinction; aggression fell near zero. Two months later, the break card contacts extinction during a staffing shortage. Aggression reappears at high rates even though the physical classroom is unchanged. Which process BEST accounts for the reappearance?",
    "C",
    [
      "Spontaneous recovery after a temporal break from the extinction context alone",
      "Renewal driven solely by a return to the original physical setting",
      "Resurgence of a previously reinforced response when the more recently reinforced alternative contacts extinction",
      "Habituation to demand materials that abolishes escape value",
    ],
    [
      "Spontaneous recovery follows time away from extinction without requiring extinction of a replacement response.",
      "Renewal is context-change reappearance; the vignette emphasizes extinction of the alternative, not a setting shift.",
      "Recovery of an earlier reinforced operant when a later alternative is extinguished defines resurgence.",
      "Habituation would reduce stimulus effectiveness; here a contingency change on the alternative precedes the increase.",
    ],
  ),
  authored2(
    2102,
    "B",
    "In Classroom A, a student’s call-outs produce teacher attention on a dense VR schedule. Simultaneously, in Classroom B with a different teacher, call-outs produce near-zero attention. After Classroom A abruptly thins attention to a very lean schedule, call-outs increase sharply in Classroom B even though Classroom B’s contingencies never changed. What phenomenon is MOST clearly illustrated?",
    "A",
    [
      "Behavioral contrast: rate change in one component alters responding in an unchanged concurrent component",
      "Stimulus generalization of thinning because both rooms share desks",
      "Matching law undermatching within a single VI schedule",
      "Respondent sensitization to teacher proximity across rooms",
    ],
    [
      "An increase in the unchanged component after enrichment/thinning changes in another component is classic behavioral contrast.",
      "Shared furniture does not explain a selective rate increase tied to a contingency change elsewhere.",
      "Undermatching concerns relative allocation versus relative reinforcement; the vignette is cross-component contrast.",
      "Sensitization is a respondent process; the data pattern is operant and contingency-linked.",
    ],
  ),
  authored2(
    2103,
    "B",
    "A BCBA teaches a conditional discrimination: given a green background, selecting “dog” is reinforced; given a red background, selecting “cat” is reinforced. Errors surge when backgrounds are faded to pastel shades that still differ chromatically. Which analysis is MOST precise?",
    "D",
    [
      "The learner never formed any discrimination because topography varied across trials",
      "Pastel shades functioned as unconditioned punishers suppressing all selections",
      "The green/red cues were establishing operations for edible reinforcers",
      "Stimulus control was tied to salient background features; fading reduced discriminability of the conditional cues",
    ],
    [
      "Differential reinforcement under distinct backgrounds indicates a discrimination had formed under training hues.",
      "Nothing indicates pastel shades were contingent punishers; errors reflect loss of cue control.",
      "Backgrounds signaled which comparison was correct—discriminative/conditional control—not MOs for edibles.",
      "When critical features become less discriminable, conditional stimulus control weakens—matching the error surge.",
    ],
  ),
  authored2(
    2104,
    "B",
    "A therapist delivers a preferred video clip 2 seconds after every instance of hand-raising, but also delivers the same clip on a dense time-based schedule whether or not hand-raising occurs. Hand-raising stays near baseline. When the noncontingent clips stop and clips follow only hand-raising, rates climb. What BEST explains the earlier failure?",
    "B",
    [
      "Two-second delays make reinforcement conceptually impossible for any operant",
      "Contiguity without a dependency (contingency) is insufficient; noncontingent delivery weakened the response–reinforcer relation",
      "Video clips cannot function as reinforcers for motor responses",
      "The rise after removing NCR proves respondent conditioning of hand-raising",
    ],
    [
      "Brief delays can still support reinforcement when a clear dependency exists.",
      "Reinforcement requires a contingency; adventitious contiguity amid NCR often fails to strengthen the target.",
      "Later contingent gains show the clip can reinforce hand-raising.",
      "The effective change is operant contingency arrangement, not CS–US elicitation of raising.",
    ],
  ),
  authored2(
    2105,
    "B",
    "During matching-to-sample, a highly salient border around incorrect comparisons draws looking, and accuracy collapses even though the sample–correct relation was previously mastered with plain cards. Softening the border restores accuracy. Which stimulus-control concept BEST fits?",
    "A",
    [
      "Overshadowing: a more salient irrelevant feature competes with control by the relevant sample–comparison relation",
      "Masking: a known discrimination is temporarily blocked by an added simultaneous element while the underlying relation remains intact",
      "Reflexivity failure because identity matching was never probed",
      "An abolishing operation that reduces the value of tokens used as consequences",
    ],
    [
      "A salient competing feature that captures control away from the trained relation is overshadowing.",
      "Masking typically involves a known skill failing in the presence of a disruptor while control can still be shown under other tests; here the border appears to have captured control during teaching/performance.",
      "Reflexivity concerns identity matching probes, not border salience effects.",
      "No MO manipulation of token value is described; accuracy tracks the visual feature change.",
    ],
  ),
  authored2(
    2106,
    "B",
    "Under a rich FI schedule for puzzle completion, a learner begins pacing in stereotyped paths during the early portion of each interval, with pacing peaking at intermediate times unrelated to puzzle contact. Pacing was never explicitly reinforced. Which account is MOST consistent?",
    "C",
    [
      "Pacing is a pure mand for puzzles under an EO for task materials",
      "Pacing is escape-maintained because staff remove the puzzle when pacing occurs",
      "Schedule-induced (adjunctive) pacing emerging as a byproduct of intermittent reinforcement timing",
      "Pacing is an SD that occasions puzzle completion through equivalence",
    ],
    [
      "No specific reinforcement of pacing by puzzle delivery is described.",
      "Contingent puzzle removal is not stated; pacing occurs within the FI timing structure.",
      "Adjunctive behaviors often appear under intermittent schedules during post-reinforcement/early-interval periods without direct reinforcement.",
      "Treating pacing as an SD/equivalence node mislabels a temporally patterned adjunctive operant.",
    ],
  ),
  authored2(
    2107,
    "B",
    "A teenager accurately states the classroom rule “raise hand before speaking” and can recite consequences, yet continues blurting when peer laughter follows blurting. After peer laughter is blocked and hand-raises contact teacher attention, blurting declines. What does this contrast MOST strongly illustrate?",
    "D",
    [
      "Rule-governed behavior always overrides direct contingency control",
      "Verbal repertoires cannot participate in classroom stimulus control",
      "Contingency-shaped blurting is impossible once a rule has been stated",
      "Stated rules may fail to control responding when conflicting direct contingencies are richer; rearranging consequences changes behavior",
    ],
    [
      "The vignette shows the rule failed until contingencies changed—opposite of rules always overriding.",
      "Rules can influence behavior; the issue is competing reinforcement for blurting.",
      "Blurting was maintained by peer laughter—clear contingency shaping—despite the rule.",
      "When direct reinforcement outcompetes instructional control, contingency change—not restating the rule—is decisive.",
    ],
  ),
  authored2(
    2108,
    "B",
    "Before a difficult worksheet, a teacher’s approach historically predicts increased demands and has been correlated with rising problem behavior that produces escape. Neutral approaches during free play do not evoke the same pattern. Which MO classification BEST fits the pre-worksheet approach?",
    "B",
    [
      "CMO-S (surrogate) because it was paired with food deprivation",
      "CMO-R (reflexive): a warning stimulus whose onset increases the value of escape from the worsening condition it signals",
      "CMO-T (transitive) establishing a worksheet pencil as a conditioned reinforcer for a locked cabinet",
      "Unconditioned EO for pain that does not depend on learning history",
    ],
    [
      "No food-deprivation pairing is described.",
      "A learned warning cue that establishes escape as more valuable (and evokes escape behavior) is a CMO-R.",
      "CMO-T establishes value of a missing tool/complementary stimulus; the vignette centers on escape from signaled worsening.",
      "The evocative pattern is tied to a learned demand-warning history, not an unconditioned pain EO.",
    ],
  ),
  authored2(
    2109,
    "B",
    "On concurrent VI schedules, a student allocates 70% of responses to Option A, which yields about 50% of obtained reinforcers, and 30% to Option B. Backup magnitudes are equal. Which description is MOST accurate?",
    "A",
    [
      "Undermatching: response allocation is less extreme than predicted by strict matching to relative reinforcement",
      "Overmatching: response ratios are more extreme than reinforcement ratios",
      "Perfect matching because any nonzero allocation to both alternatives satisfies the law",
      "Ratio strain unique to concurrent VI arrangements",
    ],
    [
      "70/30 responding against 50/50 reinforcement is less differentiated than strict matching—undermatching.",
      "Overmatching would show more extreme response bias than the reinforcer ratio.",
      "Matching is quantitative; unequal allocation with equal obtained reinforcement violates strict matching.",
      "Ratio strain concerns lean ratio schedules collapsing; this is concurrent choice allocation.",
    ],
  ),
  authored2(
    2110,
    "B",
    "A mild wristband vibration follows each instance of property destruction and initially suppresses it. After weeks of continuous use, destruction returns despite uninterrupted vibration delivery on every instance, with no change in vibration intensity. Which interpretation is MOST defensible?",
    "C",
    [
      "The vibration became an SD for destruction through discrimination training",
      "Negative reinforcement of destruction by vibration offset fully explains the return",
      "Repeated exposure can reduce aversive effectiveness (habituation), weakening positive punishment",
      "Extinction of destruction occurred because vibrations removed all tangible reinforcers",
    ],
    [
      "If vibration were an SD for destruction, rates would increase from the start of pairing, not suppress then recover.",
      "Offset of a brief vibration is not described as the functional escape contingency driving destruction.",
      "Initial suppression then recovery under continued identical punishers is consistent with loss of aversive efficacy.",
      "Vibrations are added stimuli; they do not constitute extinction of tangible maintenance.",
    ],
  ),
  authored2(
    2111,
    "B",
    "A chained FR 5 → FI 30-s schedule requires five sorting responses to produce a clock, after which the first correct file-press after 30 s produces a break. Sorting becomes reliable, but file-pressing shows a scallop only after the clock appears. What BEST characterizes stimulus control in this arrangement?",
    "D",
    [
      "Both links are under simple concurrent VI control without discriminative cues",
      "The clock is an EO that abolishes the value of the break",
      "Sorting is respondent because it precedes the clock in time",
      "The clock functions as a conditioned reinforcer for sorting and as an SD for file-pressing in the terminal link",
    ],
    [
      "Chained schedules impose successive links with link-specific stimuli, not concurrent VI choice.",
      "Clock onset enables the terminal contingency; it does not abolish break value.",
      "Sorting is maintained by producing the next-link stimulus—an operant chain—not Pavlovian elicitation.",
      "In chains, completing early links produces a stimulus that both reinforces the prior response and sets the occasion for the next.",
    ],
  ),
  authored2(
    2112,
    "B",
    "A child says “water” while pointing to a closed bottle under water deprivation and receives water. Separately, after hearing a peer say “wa-,” the child says “water” and receives praise. A third time, when asked “What do you drink?” the child says “water” for praise. Which statement BEST captures the controlling variables?",
    "B",
    [
      "All three are pure tacts because the phonemic form is identical",
      "The instances are multiply classifiable: mand (EO + specific reinforcement), echoic (verbal auditory match), and intraverbal (verbal SD without point-to-point correspondence)",
      "All three are echoics because each follows some environmental event",
      "The question-answering instance is a mand because praise is a specific reinforcer for water",
    ],
    [
      "Same topography can reflect different verbal operants; form alone does not unify class.",
      "EO + characteristic reinforcement, vocal model with point-to-point match, and verbal SD without correspondence map to mand, echoic, and intraverbal.",
      "Not every antecedent is a vocal model with correspondence.",
      "Praise is generalized conditioned reinforcement typical of intraverbals/tacts, not the specific reinforcer defining the mand.",
    ],
  ),
  authored2(
    2113,
    "B",
    "After A–B and B–C training, probes show A–A, B–B, and C–C identity matching, but A–C and C–A remain at chance. Which conclusion is MOST precise?",
    "A",
    [
      "Reflexivity is evident, but symmetry/transitivity of the nodal class relations are not yet demonstrated",
      "Full stimulus equivalence is shown because identity matching defines equivalence",
      "Symmetry of A–B is proven by A–A identity scores",
      "Transitivity is confirmed whenever reflexivity probes pass",
    ],
    [
      "Identity matching supports reflexivity; failed A–C/C–A means derived relational proof is incomplete.",
      "Equivalence requires derived relations among class members, not only identity.",
      "Symmetry of A–B would be B–A, not A–A.",
      "Reflexivity does not substitute for transitive probes.",
    ],
  ),
  authored2(
    2114,
    "B",
    "A signal light precedes occasional loud peer noise in a group room. A learner learns to press a switch during the light, which prevents the noise from occurring. Presses rarely occur in the light’s absence. Presses continue even on sessions when noise would not have occurred. Which contingency BEST describes the switch pressing?",
    "C",
    [
      "Escape: pressing terminates noise that has already begun",
      "Positive punishment of pressing by noise delivery",
      "Discriminated avoidance: an SD signals that pressing postpones/prevents an aversive event",
      "Free-operant avoidance without any warning stimulus",
    ],
    [
      "Escape removes an ongoing aversive; here pressing prevents onset during the warning.",
      "Noise is prevented by pressing, not presented contingent on pressing as a punisher.",
      "A warning stimulus that occasions a response preventing an aversive is discriminated avoidance.",
      "Free-operant avoidance lacks a discrete warning SD; the light is discriminative.",
    ],
  ),
  authored2(
    2115,
    "B",
    "Two topographies—ripping papers and swiping materials—each reliably produce work removal and increase under demand contexts, while a third topography (humming) does not affect demands and remains stable. Which concept BEST organizes ripping and swiping?",
    "D",
    [
      "They form a topographic response class defined by identical muscle movements",
      "They are respondent CRs elicited by worksheet ink color",
      "They are members of an equivalence class with humming as the node",
      "They belong to the same functional response class maintained by escape",
    ],
    [
      "Response classes in applied analysis are often functional, not limited to shared topography.",
      "No respondent elicitation analysis is provided; consequences organize the pattern.",
      "Equivalence concerns derived stimulus relations, not shared escape maintenance.",
      "Different topographies sharing the same reinforcing consequence constitute a functional class.",
    ],
  ),
  authored2(
    2116,
    "B",
    "A dense variable-time schedule of attention is added during seatwork. Attention-maintained shouting decreases without shouting contacting extinction explicitly, while task engagement rises modestly. What is the BEST mechanistic account?",
    "B",
    [
      "VT attention punishes shouting through contingent reprimands embedded in the schedule",
      "Noncontingent attention can abolish/attenuate the EO for attention-maintained problem behavior, reducing its evocative strength",
      "VT schedules convert shouting into an FI scallop pattern",
      "The decrease proves shouting was escape-maintained all along",
    ],
    [
      "VT delivers attention time-based, not as contingent reprimands for shouting.",
      "NCR often functions as an AO for the functional reinforcer, lowering motivation for problem behavior.",
      "Scallops are FI operant patterns for the reinforced response; shouting is decreasing, not FI-shaped.",
      "Attention NCR selectively implicates attention value, not escape.",
    ],
  ),
  authored2(
    2117,
    "B",
    "Baseline shows steady compliance under intermittent praise. After a high-rate praise “boost” phase in the same setting, a disruptor (loud transition noise) is introduced. Compliance decreases less than it did for a yoked peer who received only lean praise before the same disruptor. Which principle MOST directly predicts the difference?",
    "A",
    [
      "Behavioral momentum: higher reinforcer rates in the presence of a discriminative context increase resistance to change",
      "Premack principle ranking noise as a high-probability reinforcer for compliance",
      "Ratio strain from lean VI schedules during the boost phase",
      "Stimulus equivalence between noise and praise tokens",
    ],
    [
      "Momentum research links richer reinforcement history in a context to greater persistence under disruption.",
      "Premack concerns using high-probability behavior as a reinforcer, not persistence under disruptors.",
      "The boost was rich, not lean; strain would predict collapse, not relative persistence.",
      "Equivalence does not explain differential resistance to change under disruptors.",
    ],
  ),
  authored2(
    2118,
    "B",
    "A learner’s aggression increases when a favorite aide is absent and decreases when that aide returns, even though programmed demand and attention contingencies are held constant by protocol. Preference probes show the aide’s playful voice is highly preferred. Which interpretation BEST fits the rate shift?",
    "C",
    [
      "Aide absence is an SD for aggression because aggression never occurs when the aide is present",
      "Aide presence is a conditioned punisher for aggression",
      "Aide absence may function as an EO establishing attention/social reinforcers as more valuable, elevating attention-maintained aggression",
      "The pattern proves automatic reinforcement because social variables changed",
    ],
    [
      "Correlation with absence alone does not define an SD without differential consequence availability; MO effects can evoke without signaling a change in contingency.",
      "Decreases when the aide returns suggest reduced motivation or competing reinforcement, not punishment by the aide’s presence.",
      "Losing a preferred social partner can establish attention as more valuable and evoke behavior that historically produced it.",
      "Sensitivity to aide presence/absence implicates social variables, contrary to an automatic account.",
    ],
  ),
];

export const EXPANDED2_C: BDSQuestion[] = [
  authored2(
    2201,
    "C",
    "Two observers record aggression counts of 18 and 14 in the same 20-minute session. The BCBA must report total count IOA. Which calculation and interpretation are MOST appropriate?",
    "B",
    [
      "IOA = 18/14 = 129%, indicating excellent agreement",
      "IOA = (smaller/larger) × 100 = 14/18 ≈ 78%, which may be inadequate for high-stakes decisions",
      "IOA = (18 − 14)/18 = 22% disagreement reported as IOA",
      "Total count IOA cannot be computed unless interval-by-interval data exist",
    ],
    [
      "IOA conventions use smaller over larger, and values over 100% are not the standard report.",
      "Total count IOA is smaller/larger × 100; ~78% often falls below preferred thresholds for important targets.",
      "Disagreement percentage is not the IOA metric requested.",
      "Total count IOA is specifically for continuous event counts without requiring intervals.",
    ],
  ),
  authored2(
    2202,
    "C",
    "Observers use partial-interval recording for low-rate, brief head-hitting. Mean interval-by-interval IOA is 94%, but almost all disagreements occur in the few intervals scored as occurrences by either observer. Which IOA refinement BEST exposes that problem?",
    "D",
    [
      "Unscored-interval IOA only, because it ignores intervals with any occurrence",
      "Total duration IOA, because interval methods cannot assess agreement on rare events",
      "Trial-by-trial IOA for free-operant head-hitting without trial structure",
      "Scored-interval IOA, which evaluates agreement only on intervals at least one observer marks as occurrence",
    ],
    [
      "Unscored-interval IOA focuses on intervals neither marks—often inflating agreement for rare behaviors.",
      "Duration IOA is a different dimensional measure; the issue is occurrence agreement on rare intervals.",
      "Trial-by-trial IOA applies to discrete trials, not free-operant interval records.",
      "Scored-interval IOA is sensitive when occurrences are rare and disagreements cluster there.",
    ],
  ),
  authored2(
    2203,
    "C",
    "A BCBA graphs correct math problems per minute on a standard celeration chart and reports a ×2 celeration across a week of intervention. What does that report MOST directly convey?",
    "A",
    [
      "Response rate approximately doubled per week along a multiplicative trend",
      "Accuracy reached exactly 200% of opportunities",
      "IOA doubled from baseline to intervention",
      "Latency was cut in half on every trial",
    ],
    [
      "Celeration describes multiplicative change in rate over time; ×2/week indicates doubling per week.",
      "Celeration concerns rate change, not a percent-correct ceiling of 200%.",
      "IOA is agreement between observers, not celeration.",
      "Latency is a different dimensional quantity than rate celeration.",
    ],
  ),
  authored2(
    2204,
    "C",
    "Staff score worksheet completion via permanent product after sessions. Products look complete, yet spot video review shows peers finished many items for the learner. Which measurement concern is PRIMARY?",
    "C",
    [
      "Poor interobserver agreement on the permanent product scores themselves",
      "Insufficient interresponse-time sensitivity of product measures",
      "Threat to validity: the product does not accurately reflect the learner’s behavior",
      "Observer drift in the operational definition of worksheet lines",
    ],
    [
      "Product scores may agree perfectly while still misattributing who behaved.",
      "IRT is not the dimension permanent product is meant to capture here.",
      "Validity fails when the measure does not represent the intended individual’s behavior.",
      "Definitions of lines may be stable; the core issue is authorship of the product.",
    ],
  ),
  authored2(
    2205,
    "C",
    "When a novel data collector with a clipboard stands beside a learner, on-task percentages jump relative to sessions scored from a discreet camera. Definitions and training are identical. What artifact is MOST likely?",
    "B",
    [
      "Measurement decay from discontinuous interval length",
      "Observer reactivity: behavior changes because observation is discriminable",
      "Treatment integrity drift in the independent variable",
      "Ceiling effects inherent to momentary time sampling",
    ],
    [
      "Interval length is unchanged across conditions in the vignette.",
      "Discriminable observation altering the target is observer reactivity.",
      "IV integrity concerns implementation of intervention, not the observation cue effect described.",
      "MTS can miss events, but the jump tied to a visible observer points to reactivity.",
    ],
  ),
  authored2(
    2206,
    "C",
    "Stereotypy occurs in rapid bursts exceeding 30 per minute. The team needs a feasible estimate of occurrence during 10-minute samples without continuous counting. Which strategy is MOST defensible?",
    "A",
    [
      "Short partial-interval recording, acknowledging overestimation risk for brief events",
      "Latency to first stereotypy only, as a complete substitute for occurrence estimation",
      "Trials-to-criterion across academic discrete trials",
      "Whole-interval recording to maximize sensitivity to brief bursts",
    ],
    [
      "Partial interval is commonly used for high-rate brief behavior when continuous count is impractical, with known overestimation bias disclosed.",
      "Latency ignores repeated bursts after the first instance.",
      "Trials-to-criterion measures acquisition, not stereotypy occurrence in free operant samples.",
      "Whole-interval underestimates brief/high-rate behavior and is a poor sensitivity choice here.",
    ],
  ),
  authored2(
    2207,
    "C",
    "An observer starts a timer when a demand is presented and stops it when the learner begins the first active step. Separately, another measure records time from the end of one shout to the onset of the next shout. Which pairing correctly labels these measures?",
    "D",
    [
      "Both are duration measures of a single episode",
      "First is IRT; second is latency",
      "First is rate; second is celeration",
      "First is latency to initiation; second is interresponse time (IRT)",
    ],
    [
      "Neither description times a full episode from onset to offset of one response.",
      "The labels are reversed relative to standard definitions.",
      "Neither procedure yields count/time rate or multiplicative celeration.",
      "Demand-to-start is latency; time between successive shout onsets/offsets is IRT.",
    ],
  ),
  authored2(
    2208,
    "C",
    "Across a month, Observer A’s partial-interval percentages steadily rise while Observer B’s remain flat for the same sessions, even though mean IOA computed weekly stays above 90% because disagreements are symmetric early then shift. What problem should the BCBA suspect FIRST?",
    "C",
    [
      "Perfect accuracy because high IOA guarantees valid data",
      "Unscored-interval IOA inflation only",
      "Observer drift: gradual, systematic change in applying the definition by one observer",
      "That partial interval inevitably produces rising trends independent of behavior",
    ],
    [
      "High IOA does not ensure accuracy or stability of definition application over time.",
      "The vignette’s pattern is a systematic divergence over weeks, classic drift—not merely unscored-interval math.",
      "One observer’s gradual criterion shift with preserved average agreement signals observer drift.",
      "Partial interval bias is directional for occurrence estimation, not an automatic upward trend over months.",
    ],
  ),
  authored2(
    2209,
    "C",
    "A skill probe reports 80% correct (8/10 trials). A separate observation reports shouting in 80% of partial intervals. A trainee treats these percentages as interchangeable evidence of “80% performance.” What distinction should the BCBA emphasize?",
    "B",
    [
      "Both percentages are rate measures scaled to a 0–100 metric",
      "Percent correct indexes accuracy on discrete opportunities; percent of intervals estimates occurrence under discontinuous recording—different dimensional meanings",
      "Interval percentages always equal trial percentages when both equal 80",
      "Only percent correct can ever exceed chance levels",
    ],
    [
      "Percent correct is not count per unit time; interval percent is not rate.",
      "Identical numerals can reflect different quantities and threats to interpretation.",
      "Equality of numerals does not imply equal measurement meaning.",
      "Both can take various values; the issue is construct meaning, not chance ceilings.",
    ],
  ),
  authored2(
    2210,
    "C",
    "A BCBA must choose a dimensional quantity: time from SD onset to response onset for compliance, versus how long rocking lasts once it begins. Which pair correctly maps quantity to dimension?",
    "A",
    [
      "Latency (temporal locus relative to an event) vs duration (temporal extent)",
      "Duration vs count",
      "IRT vs permanent product",
      "Celeration vs topography",
    ],
    [
      "Time to initiate after an SD is latency; time occupied by rocking is duration—locus vs extent.",
      "The second measure is duration, but the first is not count.",
      "IRT is between responses; permanent product is outcome-based, matching neither description cleanly.",
      "Celeration is change in rate; topography is form—not the temporal measures described.",
    ],
  ),
  authored2(
    2211,
    "C",
    "Session lengths vary from 12 to 28 minutes across a week. Raw aggression counts are 6, 6, and 6. A supervisor concludes behavior is “perfectly stable.” What correction is MOST important?",
    "C",
    [
      "Stability of counts always implies stability of rate",
      "Convert each session to latency before graphing",
      "Report rate (or count per standard time unit); equal counts across unequal durations can mask changing rates",
      "Switch to whole-interval percent to remove time from the analysis",
    ],
    [
      "Equal counts in longer sessions imply lower rates—counts alone mislead.",
      "Latency does not summarize overall session occurrence.",
      "Standardizing by time prevents false stability conclusions when durations vary.",
      "Whole-interval still embeds time-sampling biases and does not fix unequal session length for event totals.",
    ],
  ),
  authored2(
    2212,
    "C",
    "During group instruction, an observer notes at each 2-minute mark how many of eight students are oriented to the teacher, then graphs the percent of the group on-task. Which procedure is this?",
    "D",
    [
      "Continuous duration recording for each student simultaneously",
      "Trial-by-trial IOA computation",
      "Planned activity check (PLACHECK) is incorrect because more than one student is observed",
      "PLACHECK (planned activity check): momentary group count converted to a percentage",
    ],
    [
      "Continuous duration for eight students concurrently is not described; sampling is momentary.",
      "IOA compares observers; this describes a primary measurement procedure.",
      "PLACHECK is specifically designed for groups; multiple students are expected.",
      "Momentary headcounts of a group yielding percent engagement is PLACHECK.",
    ],
  ),
  authored2(
    2213,
    "C",
    "Two observers produce identical interval scores (IOA 100%), yet both systematically start scoring “aggression” whenever a peer cries, contrary to the written definition requiring physical contact. Which statement is MOST accurate?",
    "B",
    [
      "Reliability and accuracy are both guaranteed by 100% IOA",
      "Data may be reliable (consistent) yet inaccurate relative to the true definition",
      "Accuracy is proven; validity remains unknown",
      "IOA below 80% is required before accuracy can be questioned",
    ],
    [
      "Agreement does not prove correspondence to the definition or true events.",
      "Observers can agree on a shared error—reliability without accuracy.",
      "Accuracy is precisely what fails when both misapply the definition.",
      "High IOA does not preclude accuracy problems; the threshold claim is backward.",
    ],
  ),
  authored2(
    2214,
    "C",
    "A team debates continuous event recording versus 30-second momentary time sampling for a moderate-rate target during 1:1 sessions with one trained observer available. Continuous recording is feasible. Which recommendation BEST follows measurement selection logic?",
    "A",
    [
      "Prefer continuous event recording when feasible for the clearest dimensional picture of count/rate",
      "Always prefer MTS because discontinuous methods are inherently more valid",
      "Use MTS exclusively whenever IOA might be collected later",
      "Prefer whole-interval for brief problem behavior to avoid underestimation",
    ],
    [
      "Continuous measurement minimizes sampling error when resources allow.",
      "Discontinuous methods trade precision for feasibility; they are not inherently more valid.",
      "IOA can be collected with continuous methods via dual observers or video.",
      "Whole-interval underestimates brief behavior—opposite of a good default here.",
    ],
  ),
  authored2(
    2215,
    "C",
    "While graphing learner aggression, a BCBA also scores whether staff delivered the escape extinction procedure correctly on each demand trial (implemented vs not). Across days, aggression drops only on sessions with high correct implementation. What measurement practice is illustrated by the staff scoring?",
    "C",
    [
      "Interobserver agreement on the dependent variable alone",
      "Social validity interviewing of staff preferences",
      "Treatment integrity (procedural fidelity) measurement of the independent variable",
      "Permanent product recording of aggression intensity",
    ],
    [
      "Staff scoring concerns IV delivery, not agreement on aggression.",
      "Integrity checklists are not the same as social validity interviews.",
      "Measuring whether the intervention was implemented as designed is treatment integrity.",
      "Staff implementation codes are not permanent products of aggression.",
    ],
  ),
];

export const EXPANDED2_F: BDSQuestion[] = [
  authored2(
    2301,
    "F",
    "A clinic presents all leisure items simultaneously, allows free engagement for 5 minutes without removal after selection, and ranks items by percent of intervals interacted. Which preference assessment is this?",
    "A",
    [
      "Free-operant preference assessment",
      "MSWO with replacement after each selection",
      "Paired-stimulus forced choice across all dyads",
      "Progressive-ratio breakpoint assessment",
    ],
    [
      "Unrestricted concurrent access timed for engagement is free-operant preference assessment.",
      "MSWO removes selected items and re-presents remainders; replacement would be MSW, not this free access format.",
      "Paired-stimulus presents two items per trial, not free group access.",
      "PR assessments manipulate schedule requirements to test reinforcer efficacy, not free engagement rankings.",
    ],
  ),
  authored2(
    2302,
    "F",
    "An MSW (with replacement) repeatedly returns the same toy to the array after selection. One item dominates nearly every trial, preventing ranking of lower items. What is the MOST appropriate adjustment?",
    "C",
    [
      "Conclude no preferences exist among the remaining items",
      "Switch immediately to an alone-condition FA of toy play",
      "Use MSWO (without replacement) or paired-stimulus methods that force sampling across items",
      "Increase array size while keeping replacement to intensify dominance",
    ],
    [
      "Dominance under replacement often masks relative ranks rather than proving indifference.",
      "FA of play does not solve preference hierarchy problems.",
      "Without-replacement or paired methods compel engagement with multiple items to differentiate ranks.",
      "Larger arrays with replacement can worsen single-item monopolization.",
    ],
  ),
  authored2(
    2303,
    "F",
    "In a paired-stimulus assessment, the learner selects the item on the left on 18 of 20 trials regardless of which object is placed left. Rankings therefore appear orderly but unstable across side-counterbalanced sessions. What threat is MOST likely?",
    "B",
    [
      "Absolute reinforcer efficacy proven by side preference",
      "Position bias systematically distorting stimulus preference rankings",
      "Multiple-stimulus overselection identical to MSWO",
      "Undermatching in concurrent VI preference",
    ],
    [
      "Side preference indicates position control, not item reinforcer value.",
      "Consistent left selection despite item swaps is classic position bias.",
      "This is a paired-stimulus format issue, not MSWO overselection.",
      "Matching law concurrent schedules are not the assessment procedure described.",
    ],
  ),
  authored2(
    2304,
    "F",
    "High-preference music fails to increase a sorting response when delivered contingently, yet a moderate-preference snack produces clear increases under the same schedule. Preference ranks were stable. What is the BEST next interpretive step?",
    "D",
    [
      "Discard all preference assessments as invalid forever",
      "Treat music as the functional reinforcer because preference rank was higher",
      "Conclude sorting is multiply maintained by escape and attention",
      "Treat preference and reinforcer assessments as related but distinct; rely on contingent efficacy data for intervention selection",
    ],
    [
      "A preference–reinforcer mismatch on one item does not void the assessment approach.",
      "Higher preference rank did not predict reinforcement function for sorting.",
      "No FA data on sorting’s problem-behavior function are provided.",
      "Preference predicts likelihood; reinforcer assessments confirm function for a target response.",
    ],
  ),
  authored2(
    2305,
    "F",
    "Indirect tools suggest attention; ABC data suggest escape; a standard FA shows differentially high rates in escape. The team still wants to write an attention BIP because “interviews feel convincing.” Which synthesis is MOST defensible?",
    "A",
    [
      "Weight the FA differentiation most heavily; design escape-based treatment while monitoring for multiply maintained patterns",
      "Prioritize interviews whenever caregivers are emotionally confident",
      "Average the three methods into an “attention/escape 50-50” function without further analysis",
      "Discard the FA because it contradicted the interview",
    ],
    [
      "Experimental differentiation is the strongest functional evidence among the three when safely obtained.",
      "Confidence is not a validity metric for indirect tools.",
      "Mechanical averaging of conflicting methods is not sound functional synthesis.",
      "Contradiction is a reason to trust careful FA more, not discard it.",
    ],
  ),
  authored2(
    2306,
    "F",
    "An FA shows elevated aggression in both attention and escape conditions relative to play and alone, with both test conditions high. What is the MOST appropriate functional interpretation pending further analysis?",
    "C",
    [
      "Inconclusive automatic reinforcement because alone was low",
      "Attention only, because social conditions were elevated",
      "Likely multiply maintained by attention and escape under the tested contingencies",
      "Tangible maintenance despite tangible not being elevated",
    ],
    [
      "Low alone with elevated social-test conditions argues against primary automatic reinforcement.",
      "Escape was also elevated; attention-only is incomplete.",
      "Two differentiated social functions support a multiply maintained interpretation.",
      "No tangible elevation is described.",
    ],
  ),
  authored2(
    2307,
    "F",
    "Self-injury is too intense for a full extended FA. The BCBA runs brief sessions, advances quickly across conditions, and uses contingency reversals when a condition elevates. Which approach is being adapted?",
    "B",
    [
      "MSWO preference assessment with replacement",
      "Brief functional analysis methods emphasizing rapid condition changes and reversals",
      "Structured descriptive assessment with conditional probabilities only",
      "Component analysis of a treatment package",
    ],
    [
      "Preference arrays are not FA condition manipulations.",
      "Brief FA designs use short sessions, rapid alternation, and reversals to identify function under constraints.",
      "Descriptive methods observe naturally occurring contingencies without systematic test conditions.",
      "Component analysis evaluates treatment elements after function-based intervention exists.",
    ],
  ),
  authored2(
    2308,
    "F",
    "Severe SIB precludes repeatedly evocating full episodes. The BCBA instead measures time from condition onset to the first precursor (jaw clench) historically chained to SIB, comparing conditions. Which FA variation is this?",
    "D",
    [
      "Trial-based FA embedded in classroom trials only",
      "Interview-informed synthesized contingency analysis (IISCA) by definition",
      "Free-operant preference assessment of precursors",
      "Latency-based FA using time-to-first-response (or precursor) as the primary index",
    ],
    [
      "Trial-based FA uses discrete trials with presence/absence in each trial segment—not primarily latency curves.",
      "IISCA synthesizes contingencies from interviews; latency FA is defined by the dependent measure.",
      "Preference assessment does not test FA conditions for problem behavior.",
      "Comparing latencies to first target/precursor across conditions is a latency-based FA strategy.",
    ],
  ),
  authored2(
    2309,
    "F",
    "Classroom staff run 1–2 minute trials: a test segment presenting the putative EO/SD and contingency, then a control segment. Occurrence vs nonoccurrence is scored per segment across many embedded trials. Which method matches this description?",
    "A",
    [
      "Trial-based functional analysis",
      "Extended alone-condition automatic screen only",
      "Paired-stimulus preference assessment",
      "Multiple-baseline across settings design for treatment",
    ],
    [
      "Brief embedded test/control segments scored occurrence/nonoccurrence define trial-based FA.",
      "Alone screens are continuous alone periods, not alternating test/control trial segments.",
      "Paired-stimulus compares item choices, not EO contingencies for problem behavior.",
      "Multiple-baseline is an experimental treatment design, not this assessment structure.",
    ],
  ),
  authored2(
    2310,
    "F",
    "Caregiver interview suggests problem behavior peaks when demands and diverted adult attention co-occur. An FA that tests those contingencies together (synthesized) produces clear differentiation from control, while isolated attention or escape tests were ambiguous. What BEST describes the assessment logic?",
    "C",
    [
      "Synthesized contingencies are unethical whenever isolation is ambiguous",
      "Ambiguous isolated tests prove the behavior has no function",
      "Interview-informed synthesized contingency analysis can capture ecologically combined contingencies that isolated tests miss",
      "Synthesis always indicates automatic reinforcement",
    ],
    [
      "Synthesis can be appropriate when ecologically valid combinations are hypothesized—especially if isolation fails.",
      "Ambiguity suggests limited ecological match or power, not absence of function.",
      "IISCA-style logic intentionally combines reported contingencies to improve differentiation.",
      "Synthesis concerns social contingency combinations, not automaticity.",
    ],
  ),
  authored2(
    2311,
    "F",
    "Before running demand FA conditions, a BCBA presents varied tasks and ranks which produce the most problem behavior or refusal, then uses high-aversion tasks in escape tests. What assessment step is this?",
    "B",
    [
      "Competing stimulus assessment for automatic SIB",
      "Demand (task) assessment to identify evocative academic/work materials for escape tests",
      "MSWO of edible reinforcers",
      "Procedural integrity scoring of extinction",
    ],
    [
      "Competing stimulus assessments identify stimuli that suppress automatic behavior when available.",
      "Pre-FA demand assessments select tasks that reliably evoke escape-related problem behavior.",
      "Edible MSWO ranks preference, not demand aversiveness.",
      "Integrity scoring measures implementation, not task evocativeness.",
    ],
  ),
  authored2(
    2312,
    "F",
    "Hand mouthing persists in an enriched alone condition. The BCBA presents candidate stimuli and identifies items associated with the lowest mouthing rates when freely available, later using them in noncontingent competing-stimulus procedures. Which assessment is this?",
    "A",
    [
      "Competing stimulus assessment",
      "Paired-stimulus FA of escape",
      "Trial-based preference assessment with replacement",
      "Latency FA of attention",
    ],
    [
      "Identifying stimuli that displace/reduce automatically maintained behavior is a competing stimulus assessment.",
      "Escape FA involves demand contingencies, not item displacement of mouthing in alone.",
      "The goal is suppression of problem behavior, not simple preference ranking.",
      "Latency FA indexes time to problem behavior across social/test conditions.",
    ],
  ),
  authored2(
    2313,
    "F",
    "A school psychologist describes a “functional analysis” that only coded antecedents (task type, grouping) without manipulating consequences. Rates differed by task difficulty. Which critique is MOST accurate?",
    "D",
    [
      "Consequence-free coding is the gold-standard experimental FA",
      "Antecedent-only comparisons fully isolate reinforcement functions",
      "Task difficulty differences prove automatic reinforcement",
      "That procedure is closer to structural/descriptive analysis; without consequence manipulation, reinforcement function is not experimentally demonstrated",
    ],
    [
      "Experimental FA systematically arranges consequences across test/control conditions.",
      "Antecedents alone cannot confirm which consequence maintains behavior.",
      "Difficulty effects may suggest escape motivation but do not prove automaticity.",
      "Structural analyses relate behavior to stimulus conditions; function requires contingency tests.",
    ],
  ),
  authored2(
    2314,
    "F",
    "Conditional probability analysis of ABC data shows P(attention|aggression) is high, but P(aggression|attention opportunity) is also elevated during easy leisure, and play-condition FA rates are low when attention is withheld contingent on aggression. What is the SAFEST interpretation?",
    "B",
    [
      "High P(attention|aggression) alone proves attention maintenance",
      "Descriptive conditional probabilities can reflect coincidence or routine staff responding; FA contingency tests provide stronger functional evidence",
      "FA play-condition results must be discarded whenever descriptive probabilities are high",
      "Automatic reinforcement is confirmed by any attention following aggression",
    ],
    [
      "Staff often attend after severe behavior regardless of function—correlation ≠ functional confirmation.",
      "Descriptive probabilities are hypothesis-generating; experimental contingency control clarifies function.",
      "Disconfirming FA data warrant caution about descriptive inferences, not automatic discard of FA.",
      "Attention following behavior does not define automatic reinforcement.",
    ],
  ),
  authored2(
    2315,
    "F",
    "A team requests only a VB-MAPP skills profile before writing a BIP for escape-maintained aggression. The BCBA insists on function-based assessment of aggression in addition to skills testing. What BEST justifies that insistence?",
    "C",
    [
      "Skills assessments already identify maintaining reinforcers for problem behavior",
      "BIP content should ignore function if skill deficits are documented",
      "Curriculum/skills tools describe repertoires; FBA/FA methods are needed to identify contingencies maintaining problem behavior",
      "Escape maintenance cannot coexist with any mand deficit",
    ],
    [
      "Skills tools map verbal/learner repertoires, not problem-behavior reinforcement functions.",
      "Function-based treatment remains central for problem behavior even when skills gaps exist.",
      "Distinct assessment purposes: skills vs function of problem behavior.",
      "Mand deficits often accompany escape problems; they are not mutually exclusive.",
    ],
  ),
  authored2(
    2316,
    "F",
    "During an attention FA condition, the therapist is supposed to divert attention and deliver brief attention contingent on problem behavior. Video shows nearly continuous therapist talking unrelated to the contingency. Attention-condition rates are undifferentiated from play. What is the PRIMARY assessment threat?",
    "A",
    [
      "Poor procedural fidelity in the attention test condition, compromising functional differentiation",
      "Proof that the behavior is automatically maintained",
      "Evidence that play is an establishing operation for aggression",
      "Confirmation that IOA on the DV was below standard",
    ],
    [
      "If attention is not withheld and delivered as designed, the attention test is invalid and differentiation fails.",
      "Undifferentiation under a corrupted attention condition does not confirm automatic function.",
      "Play is typically a control with noncontingent attention; the vignette implicates therapist error in the test.",
      "The described threat is IV integrity, not DV IOA.",
    ],
  ),
  authored2(
    2317,
    "F",
    "A learner’s problem behavior is near zero in standard FA conditions but reliably occurs when a sibling receives parent attention while the learner’s preferred tablet is restricted—matching caregiver reports of home triggers. Isolated attention and tangible tests were flat. Which next step is MOST aligned with assessment best practice?",
    "D",
    [
      "Ignore ecological reports because standard FA conditions were flat",
      "Conclude the behavior has no operant function",
      "Write an attention extinction plan solely from the flat attention condition",
      "Test an interview-informed synthesized or idiosyncratic contingency that combines diverted attention with tangible restriction",
    ],
    [
      "Flat standard conditions with clear ecological reports warrant refined tests, not dismissal.",
      "Absence of differentiation in standard tests does not prove non-operant behavior.",
      "A flat attention condition under isolation should not drive an attention plan when ecology points elsewhere.",
      "Idiosyncratic/synthesized tests targeting reported combined contingencies are appropriate when standard tests fail to capture the context.",
    ],
  ),
];
