/**
 * Expanded authored items — Domains E (Ethics) and G (Behavior-change procedures).
 * Independent study only. Not affiliated with the BACB.
 */
import type { BDSQuestion } from "@/lib/content-types";
import { authored } from "@/content/mockExam/exams/bcbaFull6e/expandedAuthoredHelper";

export const EXPANDED_E: BDSQuestion[] = [
  authored(
    1301,
    "E",
    "A school team asks a BCBA to begin intensive escape-extinction protocols for a nonverbal middle-schooler. The principal argues that assent is unnecessary because the learner 'will never understand the forms.' Legal guardians previously signed general education consent but were never offered a plain-language description of extinction risks or alternatives. What should the BCBA do FIRST?",
    "B",
    [
      "Implement the protocol immediately—guardian signatures already satisfy all ethical obligations.",
      "Pause intensive programming until guardians receive understandable information and the team documents assent-sensitive procedures appropriate to the learner's response repertoire.",
      "Proceed without guardian involvement if the IEP team votes unanimously.",
      "Replace extinction with physical punishment so assent becomes irrelevant.",
    ],
    [
      "General signatures without procedure-specific understanding do not meet informed consent standards for high-risk interventions.",
      "Ethics codes emphasize informed consent and assent-sensitive practice; intensive procedures require clear explanation of risks, benefits, and alternatives before implementation.",
      "IEP voting cannot waive guardian informed consent for behavior-analytic services.",
      "Escalating aversives worsens ethical risk and ignores consent/assent duties.",
    ],
  ),
  authored(
    1302,
    "E",
    "An RBT records a classroom session on a personal phone to 'show the team how well manding looks,' then posts a 20-second clip to a private Instagram story. Two classmates' faces and a classroom white board with the client's full name are briefly visible. The BCBA discovers the post two hours later. Which action is MOST consistent with confidentiality obligations?",
    "C",
    [
      "Leave the post up if the story expires within 24 hours and no outsider comments.",
      "Congratulate the RBT for creative documentation and request the original file for the clinical record.",
      "Direct immediate removal, document the breach, notify appropriate parties per organizational and legal policy, and retrain staff on PHI and media prohibitions.",
      "Ask the RBT to crop faces tomorrow and repost a 'cleaner' version for marketing.",
    ],
    [
      "Ephemeral posting still discloses protected information; expiration does not cure the breach.",
      "Personal social media is not a lawful clinical documentation channel for identifiable media.",
      "Protecting confidentiality requires stopping further disclosure, documenting, following breach pathways, and correcting practice conditions that allowed the leak.",
      "Reposting identifiable material continues unauthorized disclosure.",
    ],
  ),
  authored(
    1303,
    "E",
    "A BCBA has provided home services for two years. After discharge planning begins, the caregiver invites the BCBA to become a paid weekend babysitter 'because you already know all the strategies,' and also asks the BCBA to join the family's private group chat for school gossip. Objectivity concerns and blurred boundaries are emerging. What is the BEST next step?",
    "A",
    [
      "Decline the babysitting arrangement, clarify professional boundaries, and keep communication limited to clinically necessary, documented channels.",
      "Accept babysitting only if paid cash so the dual relationship stays off the agency ledger.",
      "Join the group chat but mute notifications to reduce influence.",
      "Transfer the case silently without explaining boundary concerns to anyone.",
    ],
    [
      "Multiple relationships that impair objectivity or exploit trust should be avoided or resolved; declining extra-role contact and maintaining professional channels protects clients and the analyst.",
      "Cash payment does not remove conflict or exploitation risk.",
      "Entering informal social channels still creates dual-relationship and confidentiality risks.",
      "Abrupt silent transfer without documentation and transition planning creates new ethical problems.",
    ],
  ),
  authored(
    1304,
    "E",
    "Parents request that a newly certified BCBA independently design and supervise a pediatric feeding protocol involving texture fading for a child with a complex medical history, including prior aspiration events. The BCBA's graduate training included only introductory feeding coursework and no supervised medical-collaboration experience. Clinic leadership says 'just start—insurance authorized it.' What should the BCBA do?",
    "D",
    [
      "Begin immediately because payer authorization equals clinical competence.",
      "Implement the protocol but omit medical consultation to avoid delaying billable hours.",
      "Tell parents feeding is outside ABA entirely and refuse any further discussion.",
      "Decline independent implementation beyond current competence, seek appropriate consultation/referral and medical clearance pathways, and document scope limits transparently.",
    ],
    [
      "Authorization is a funding decision, not a competence determination.",
      "Skipping medical collaboration for aspiration-risk feeding is unsafe and outside responsible practice.",
      "Feeding can be within behavior analysis with proper collaboration; blanket refusal without referral pathways is incomplete.",
      "Practicing within competence, arranging consultation/referral, and securing needed clearances align with ethics regarding scope and client protection.",
    ],
  ),
  authored(
    1305,
    "E",
    "During an audit, a BCBA notices that several session notes from last month list targets that were never run and include fabricated probe percentages matching an authorization milestone. The supervisee who authored the notes says the clinical director ordered 'clean graphs for renewal.' Which response BEST upholds documentation integrity?",
    "B",
    [
      "Rewrite remaining notes to match the fabricated percentages so the chart is internally consistent.",
      "Stop further falsification, preserve evidence, correct the record through proper amendment procedures, and escalate through required organizational and professional reporting channels.",
      "Delete the notes entirely so auditors find nothing.",
      "Ignore the issue if the learner's behavior actually improved in other settings.",
    ],
    [
      "Compounding false entries deepens fraud and ethical violations.",
      "Honest documentation, correction via legitimate amendment, and reporting of falsification are required; directive pressure does not excuse fabrication.",
      "Destruction of records obstructs oversight and may violate law and ethics.",
      "Outcome anecdotes do not authorize false clinical records.",
    ],
  ),
  authored(
    1306,
    "E",
    "An agency owner instructs a BCBA to bill adaptive behavior treatment with protocol modification for a home block in which only an RBT was present and the BCBA completed no concurrent direction, observation, or protocol modification. The owner emails, 'We need the units or payroll slips.' What is the MOST ethical billing response?",
    "A",
    [
      "Refuse to bill services not rendered as described, document the directive, and pursue internal compliance and, if needed, external reporting pathways.",
      "Bill the higher code and write a note claiming remote 'mental supervision' occurred.",
      "Split the difference by billing half units without a clinical note.",
      "Allow the RBT to sign as BCBA for that date only.",
    ],
    [
      "Billing integrity requires accurate representation of services delivered; refusing false claims and documenting pressure protect clients, payers, and professional standards.",
      "Inventing supervision contact misrepresents the service.",
      "Partial false billing remains fraudulent representation.",
      "Credential misrepresentation compounds the ethical and legal breach.",
    ],
  ),
  authored(
    1307,
    "E",
    "A BCBA learns that a colleague altered IOA sheets after the fact so a grant report would show 90% agreement. The colleague asks the BCBA to 'stay quiet because everyone does cleanup edits.' No client is in immediate physical danger, but research and clinical decisions rely on those data. What should the BCBA do?",
    "C",
    [
      "Stay silent to preserve workplace harmony and hope the grant ends soon.",
      "Confront the colleague publicly on social media with screenshots.",
      "Document observed facts, refuse participation in the falsification, and report through appropriate supervisory, organizational, and professional channels as required.",
      "Offer to help rewrite remaining IOA sheets so both names share liability.",
    ],
    [
      "Silence enables ongoing integrity violations affecting clients and science.",
      "Public shaming is not a substitute for professional reporting pathways and may create new confidentiality problems.",
      "Ethics expectations include addressing and reporting research/clinical data falsification through proper channels while protecting the integrity of the record.",
      "Joining the falsification creates shared ethical and legal exposure.",
    ],
  ),
  authored(
    1308,
    "E",
    "A clinic asks its BCBA to post a testimonial video stating the program 'guarantees BACB exam-level outcomes and 100% elimination of aggression in eight weeks,' using a client's first name and school. Guardians verbally said 'sure' in the hallway but signed no media release, and no outcome data support the guarantee. Which public-statement approach is MOST appropriate?",
    "D",
    [
      "Post the video because hallway agreement equals informed media consent.",
      "Post only the guarantee language and blur the face—no release needed.",
      "Post with the client's initials to create plausible deniability.",
      "Decline misleading guarantees and identifiable disclosures; use only accurate, authorized public information consistent with consent and truthfulness standards.",
    ],
    [
      "Casual hallway assent without documented informed media consent is insufficient for identifiable publicity.",
      "False outcome guarantees remain unethical even if faces are blurred.",
      "Initials plus school context can still identify minors and do not cure false claims.",
      "Public statements must be truthful, non-guaranteeing where unwarranted, and respectful of confidentiality/consent limits.",
    ],
  ),
  authored(
    1309,
    "E",
    "Funding for a learner's home program ends in three weeks. The BCBA has data showing clinically significant progress and remaining risk during transitions. Leadership wants services stopped on the authorization end date with no caregiver meeting and no referral list, citing 'business efficiency.' What termination practice is MOST ethical?",
    "B",
    [
      "Stop on the end date without notice because payers, not clinicians, control transitions.",
      "Provide timely notice, discuss risks and options, assist with clinically appropriate transition/referrals, and document the plan and communications.",
      "Continue unpaid daily services indefinitely regardless of agency constraints without any plan.",
      "Discharge immediately today to avoid awkward conversations later.",
    ],
    [
      "Payer timelines do not eliminate duties to plan discontinuance responsibly.",
      "Ethical discontinuation includes reasonable notice, transition support, and documentation—not abrupt abandonment framed as efficiency.",
      "Unbounded unpaid practice without a structured transition plan is not a sustainable or clearly planned alternative.",
      "Earlier abrupt discharge worsens abandonment risk.",
    ],
  ),
  authored(
    1310,
    "E",
    "A family requests that mealtime teaching avoid pork for religious reasons and that praise avoid certain phrases that conflict with their cultural norms. Staff call the requests 'overly sensitive' and continue using preferred clinic scripts and snack reinforcers that violate the family's guidelines. Graphs improve, but caregivers report eroded trust. What should the BCBA prioritize?",
    "A",
    [
      "Revise procedures and reinforcer menus to honor lawful cultural and religious preferences while maintaining clinical effectiveness, and retrain staff on culturally responsive practice.",
      "Keep existing reinforcers because progress graphs outweigh caregiver values.",
      "Discharge the family for noncompliance with clinic culture.",
      "Ignore the request until annual plan review in eleven months.",
    ],
    [
      "Cultural humility and respect for client values are ethical responsibilities; effective programming can usually be adapted without abandoning evidence-based methods.",
      "Outcome graphs do not justify dismissing culturally important constraints.",
      "Discharge for value-based requests is punitive and ethically unjustified when adaptations are feasible.",
      "Delaying needed cultural accommodations damages rapport and may reduce social validity.",
    ],
  ),
  authored(
    1311,
    "E",
    "Guardians with limited English proficiency signed a dense English consent packet after a 90-second summary from an untrained front-desk staff member. Midway through assessment, they report they did not understand restraint contingencies or data-sharing with the school. Services have not yet included restraint. What is the BCBA's BEST action?",
    "C",
    [
      "Continue assessment unchanged because signatures are already on file.",
      "Have the child translate technical terms for the parents during the next session.",
      "Pause disputed elements, obtain interpretation/translation support, re-explain procedures and risks, and re-secure informed consent before proceeding with those components.",
      "Email a machine-translated PDF overnight and assume comprehension.",
    ],
    [
      "Signatures without understanding do not constitute informed consent.",
      "Using a child as interpreter for parental consent is inappropriate and unreliable.",
      "Informed consent requires comprehension; remedying language barriers and re-consenting protects autonomy and ethics.",
      "Unverified machine translation alone may not ensure understanding of high-stakes procedures.",
    ],
  ),
  authored(
    1312,
    "E",
    "A well-meaning classroom aide photographs a behavior support plan header containing diagnoses and then texts it to a parent group chat 'so everyone can help keep the strategies consistent.' Several unrelated families now have the document. The BCBA is notified by a caregiver. What should the BCBA do NEXT?",
    "B",
    [
      "Thank the aide for collaboration and ask chat members to delete messages privately without agency notification.",
      "Contain further disclosure, follow breach-notification and documentation procedures, retrain staff on PHI minimum-necessary rules, and coordinate lawful communications with affected parties.",
      "Post a clarifying note in the same group chat with more clinical detail to prevent rumors.",
      "Ignore the incident if the strategies were already somewhat public at school.",
    ],
    [
      "Informal deletion requests without organizational process under-manage a confidentiality breach.",
      "Confidentiality breaches require containment, proper notification/documentation pathways, and systems fixes—not casual workarounds.",
      "Adding clinical detail to a group chat expands the breach.",
      "Partial public knowledge does not authorize unauthorized redisclosure of protected information.",
    ],
  ),
  authored(
    1313,
    "E",
    "A BCBA is asked to provide clinical supervision to a close friend who is also the BCBA's tenant in a rental property the BCBA owns. The friend is applying fieldwork hours toward certification and wants informal evening feedback without contracts. Which arrangement BEST manages multiple-relationship risk?",
    "D",
    [
      "Supervise informally because friendship increases honesty.",
      "Supervise only if rent is reduced in exchange for free fieldwork hours.",
      "Agree to supervise but hide the landlord relationship from the agency.",
      "Decline or restructure so that supervisory authority is not combined with landlord/friendship conflicts; arrange alternative qualified supervision with clear contracts if services proceed.",
    ],
    [
      "Friendship alone does not remove conflicts that impair objectivity.",
      "Trading rent for supervision exploits and conflates financial and evaluative roles.",
      "Concealing conflicts violates transparency and integrity expectations.",
      "Avoiding or restructuring conflicting roles protects objectivity, fairness, and supervisee welfare.",
    ],
  ),
  authored(
    1314,
    "E",
    "During a team meeting, caregivers ask the BCBA to 'just prescribe a low-dose stimulant' because waitlists for psychiatry are long and the BCBA 'knows behavior best.' The BCBA holds no medical license. What is the MOST appropriate response?",
    "A",
    [
      "Clarify that prescribing medication is outside the BCBA's scope, decline to prescribe or recommend specific drug regimens as if authorized, and support appropriate medical referral pathways.",
      "Suggest a specific medication and dose privately after the meeting.",
      "Write the prescription under the supervising physician's name without physician involvement.",
      "Promise medication recommendations in exchange for continued ABA authorization.",
    ],
    [
      "Competence and scope limits prohibit practicing medicine; ethical practice includes clear boundaries and facilitating proper referrals.",
      "Private dosing advice still exceeds scope and risks harm.",
      "Unauthorized prescribing is illegal and unethical.",
      "Trading unauthorized medical advice for funding is coercive and out of scope.",
    ],
  ),
  authored(
    1315,
    "E",
    "Before an external quality review, a clinical manager asks the BCBA to rescale y-axes and omit two weeks of elevated problem behavior so progress 'reads cleaner for the binder.' The underlying spreadsheet would remain unchanged on the shared drive. What should the BCBA do?",
    "C",
    [
      "Create the cleaned binder graphs because the raw spreadsheet still exists somewhere.",
      "Omit only the worst day and call it 'outlier management.'",
      "Refuse to present misleading graphics, insist on accurate data displays with context for variability, and escalate if pressured to falsify visual analysis.",
      "Hand the reviewer a narrative with no graphs to avoid the issue.",
    ],
    [
      "Parallel accurate files do not excuse knowingly deceptive presentation to reviewers.",
      "Selective omission to manufacture improvement is still misrepresentation.",
      "Documentation and graphic integrity require honest portrayal of the data; refusing deceptive visuals upholds ethics.",
      "Avoiding graphs does not correct pressure to misrepresent outcomes and may itself obscure evaluation.",
    ],
  ),
  authored(
    1316,
    "E",
    "Near month's end, utilization is below contracted hours. Operations staff ask the BCBA to schedule make-up sessions the family never requested and to document them as caregiver training even if caregivers cannot attend. The learner is available, but no training content is planned. Which choice BEST protects billing integrity?",
    "B",
    [
      "Document caregiver training for empty sessions to meet utilization targets.",
      "Only schedule and bill medically necessary, consented services that are actually delivered and accurately described; address utilization through honest planning with stakeholders.",
      "Bill the hours as direct treatment while writing caregiver-training goals retroactively.",
      "Have the RBT fabricate caregiver signatures on remote-training attestations.",
    ],
    [
      "Documenting services not rendered is fraudulent.",
      "Accurate billing and honest service planning are required; utilization pressure does not justify false claims.",
      "Mislabeled services remain integrity violations.",
      "Fabricated attestations compound fraud and documentation breaches.",
    ],
  ),
  authored(
    1317,
    "E",
    "A learner consistently turns away, pushes materials, and uses a break card when a particular discrete-trial program begins. Staff interpret this as 'noncompliance to push through' and block escape for 15 minutes despite escalating distress and no safety crisis. Guardians want assent honored when the learner clearly withdraws. What should the BCBA do?",
    "A",
    [
      "Treat clear withdrawal indicators as assent withdrawal, pause or redesign the aversive arrangement, and use less intrusive, assent-sensitive teaching strategies with documented consent.",
      "Increase blocking duration until the learner stops resisting.",
      "Remove the break card so escape responses cannot be measured.",
      "Continue unchanged because guardians signed a general treatment consent last year.",
    ],
    [
      "Assent-sensitive practice requires recognizing and honoring withdrawal indicators and adjusting procedures rather than coercively overriding them absent imminent safety needs.",
      "Prolonged coercive blocking intensifies ethical and clinical harm.",
      "Removing communication tools to hide escape is countertherapeutic and disrespectful of assent.",
      "Prior general consent does not authorize ignoring present assent withdrawal for non-crisis teaching.",
    ],
  ),
  authored(
    1318,
    "E",
    "A BCBA resigns with two weeks' notice. Twelve active clients will lose their only supervisor. Leadership plans to reassign cases the day after the BCBA's last day with no caregiver meetings, no written transition summaries, and no interim contacts listed. The BCBA still has access to records this week. What is the MOST responsible action available to the BCBA?",
    "D",
    [
      "Leave without preparing transitions because leadership owns all continuity duties exclusively.",
      "Email raw data files to personal accounts to 'help later' outside agency policy.",
      "Tell caregivers to sue the agency and refuse any transition paperwork.",
      "Within role and policy, complete concise transition summaries, advocate for timely caregiver notice and interim coverage, and document efforts to prevent abandonment.",
    ],
    [
      "Analysts share responsibility to facilitate orderly discontinuance/transition even when organizations are primarily responsible for coverage systems.",
      "Removing PHI to personal accounts creates confidentiality violations.",
      "Encouraging litigation instead of transition planning does not fulfill client-protection duties.",
      "Ethical termination/transition includes reasonable steps to support continuity, notice, and documentation before services end.",
    ],
  ),
  authored(
    1319,
    "E",
    "A BCBA is invited to speak at a community fair and plans to describe 'our proprietary cure protocol aligned with BACB requirements,' implying organizational endorsement. The talk would include before/after photos of identifiable clients without releases. Which revision BEST aligns with ethical public statements?",
    "B",
    [
      "Keep cure language and photos if the fair is educational rather than commercial.",
      "Remove cure/affiliation implications and identifiable media; present accurate, non-sensational information about behavior analysis with proper disclaimers and authorized materials only.",
      "Use the photos but add a footnote saying 'not affiliated' in 6-point font.",
      "Claim BACB partnership to increase attendance, then clarify privately if asked.",
    ],
    [
      "Educational settings do not excuse false cure claims or unauthorized identifiable disclosures.",
      "Truthful public communications avoid false guarantees and unauthorized endorsements/affiliations and protect confidentiality.",
      "Tiny disclaimers do not cure identifiable unauthorized photos or misleading cure claims.",
      "False implied affiliation is unethical whether or not later clarified.",
    ],
  ),
];

export const EXPANDED_G: BDSQuestion[] = [
  authored(
    1401,
    "G",
    "A learner currently scribbles undifferentiated marks. The goal is independent writing of the first letter of their name. The BCBA reinforces successive approximations—first any mark on paper, then marks with closer directionality, then a recognizable letter form—while previously reinforced cruder forms are placed on extinction. Which procedure is being applied?",
    "A",
    [
      "Shaping of a terminal topography through differential reinforcement of successive approximations.",
      "Backward chaining of a task analysis with terminal-link mastery first.",
      "Noncontingent reinforcement delivered on a fixed-time schedule.",
      "DRL to reduce rate while preserving the same topography.",
    ],
    [
      "Reinforcing progressive approximations toward a terminal response while extinguishing earlier forms is the definition of shaping.",
      "Chaining sequences already-defined links; the vignette builds a novel topography gradually.",
      "NCR delivers reinforcers independently of the target response.",
      "DRL addresses rate reduction, not progressive form change.",
    ],
  ),
  authored(
    1402,
    "G",
    "Handwashing is task-analyzed into six links. The BCBA prompts and reinforces the final link to independence first, then adds the preceding link, and so on until the full chain occurs in natural order. Intermediate links already mastered continue to produce the natural terminal reinforcer of clean hands plus praise. Which chaining method is described?",
    "C",
    [
      "Forward chaining starting at the first link only.",
      "Total-task presentation with equal prompting on every link each trial.",
      "Backward chaining, establishing the terminal link first and moving upstream.",
      "Shape each joint movement without a task analysis.",
    ],
    [
      "Forward chaining begins with the initial link and advances downstream.",
      "Total-task teaches all steps each opportunity rather than locking the end first.",
      "Teaching the last step first and progressively adding earlier steps is backward chaining.",
      "Shaping without a chain structure does not match the task-analysis description.",
    ],
  ),
  authored(
    1403,
    "G",
    "Staff currently use full physical guidance for utensil use. The BCBA wants independence without abrupt failure. A plan moves from full physical to partial physical, then to a light touch cue, then to a gestural prompt, with time-based delays inserted before prompts as independence emerges. Integrity checks track prompt level per trial. Which strategy BEST matches this plan?",
    "B",
    [
      "Errorless jumping from full physical to no prompt in one session.",
      "Most-to-least prompting combined with prompt delaying/fading guided by data.",
      "Extinction of all correct utensil responses.",
      "Independent group contingency for the lunch table.",
    ],
    [
      "Abrupt removal often produces errors and prompt dependence relapse.",
      "Systematic most-to-least hierarchies with delayed prompting are standard prompt-fading approaches toward independence.",
      "Extinguishing correct responses opposes skill acquisition.",
      "Group contingencies do not specify individual prompt hierarchies.",
    ],
  ),
  authored(
    1404,
    "G",
    "Functional analysis indicates aggression is maintained by adult attention. The intervention delivers dense, high-quality attention contingent on appropriate requests and context-appropriate social approaches, while aggression no longer produces attention. Escape and tangible contingencies are unchanged and rare in this context. Which differential reinforcement procedure is PRIMARY?",
    "D",
    [
      "DRO for any behavior other than aggression on a resetting interval.",
      "DRI requiring a physically incompatible posture throughout the interval.",
      "DRL aiming only to lower aggression to a preset rate.",
      "DRA reinforcing a functionally matched alternative that produces the same reinforcer class.",
    ],
    [
      "DRO omits specifying a particular alternative topography.",
      "DRI requires incompatibility; the vignette specifies alternative requests/approaches, not obligatory incompatible form.",
      "DRL reduces rate but still allows some problem behavior; the plan withholds attention for aggression entirely while reinforcing alternatives.",
      "DRA strengthens an alternative response that contacts the functional reinforcer—here, attention—while problem behavior does not.",
    ],
  ),
  authored(
    1405,
    "G",
    "A classroom team wants to reduce nose-picking without teaching a specific alternative yet. The BCBA arranges a resetting 2-minute interval: if no nose-picking occurs, the learner earns a token and the interval resets; any nose-picking resets the timer without a token. Which procedure is this?",
    "A",
    [
      "DRO — reinforcement delivered for the absence of the target behavior during an interval.",
      "DRA — reinforcement only for a predefined communicative alternative.",
      "DRI — reinforcement only when hands are physically incompatible every second.",
      "NCR — tokens delivered on a clock regardless of nose-picking.",
    ],
    [
      "Differential reinforcement of other behavior reinforces omission of the target for an interval—matching the resetting timer description.",
      "DRA requires a specified alternative response, which is not yet defined here.",
      "DRI demands an incompatible response topography, not mere absence.",
      "NCR would ignore contingencies on the target behavior.",
    ],
  ),
  authored(
    1406,
    "G",
    "A learner's hand-flapping interferes with worksheet completion and is hypothesized as automatically maintained. The BCBA reinforces sitting with hands occupying a fidget on the lap—physically incompatible with flapping—on a dense schedule, while flapping produces no programmed social consequences. Which procedure is MOST precisely described?",
    "C",
    [
      "DRL with full preservation of flapping topography at lower rates.",
      "Forward chaining of worksheet steps only.",
      "DRI by reinforcing a physically incompatible alternative response.",
      "Group interdependent contingency for the whole class.",
    ],
    [
      "DRL would still allow flapping within rate limits rather than requiring an incompatible form.",
      "Chaining addresses link sequences, not the incompatibility contingency described.",
      "Differential reinforcement of incompatible behavior targets a topography that cannot occur with the problem behavior.",
      "No group payoff structure is described.",
    ],
  ),
  authored(
    1407,
    "G",
    "A teen's humorous call-outs during lecture occur about 12 times per hour. The goal is reduction to no more than 3 per hour while preserving some social commenting. Reinforcement (points toward preferred break activities) is delivered when call-outs stay at or below the criterion in each hour; exceeding the limit withholds that hour's points. Which schedule fits BEST?",
    "B",
    [
      "DRA exclusively for a brand-new incompatible posture.",
      "DRL — reinforcement contingent on meeting a low-rate criterion for the same response class.",
      "Full extinction with zero tolerance from session one.",
      "NCR delivering points every 30 seconds independent of call-outs.",
    ],
    [
      "The plan does not require a new incompatible form as the reinforced target.",
      "Differential reinforcement of low rates reduces—but does not necessarily eliminate—a response by reinforcing low-rate performance.",
      "Zero-tolerance extinction is stricter than the stated low-rate goal.",
      "NCR would not make points contingent on the rate criterion.",
    ],
  ),
  authored(
    1408,
    "G",
    "Escape-maintained property destruction previously produced indefinite work removal. The BCBA implements escape extinction: work materials remain present and demands continue with safety procedures, while a break is available only via a taught card. Rates spike for three sessions then decline. Staff want to abandon the plan during the spike. What coaching is MOST consistent with extinction practice?",
    "A",
    [
      "Anticipate extinction bursts, maintain procedural integrity with safety supports, and continue reinforcing the functional alternative (break card).",
      "Immediately reinforcer property destruction to stop the burst.",
      "Switch to unexplained punishment without revising consent or the BIP.",
      "Declare extinction failed whenever a burst appears and permanently withdraw the procedure.",
    ],
    [
      "Temporary bursts are expected; pairing extinction with FCT/alternative reinforcement and integrity preserves humane, function-based treatment.",
      "Reinforcing destruction reinstates the functional contingency.",
      "Unplanned punishment raises ethical and procedural problems.",
      "Bursts alone do not prove failure if safety is managed and integrity holds.",
    ],
  ),
  authored(
    1409,
    "G",
    "Attention-maintained yelling occurs at high rates. Before teaching a replacement mand, the BCBA delivers scheduled adult attention every 2 minutes independent of yelling, while yelling no longer uniquely produces richer attention. Yelling decreases as baseline attention density rises. Which antecedent-to-consequence strategy is PRIMARY in this phase?",
    "D",
    [
      "DRI using an incompatible whisper response only.",
      "Positive punishment via reprimand contingent on each yell.",
      "Backward chaining of a vocal mand.",
      "NCR — time-based delivery of the functional reinforcer to reduce motivation for problem behavior.",
    ],
    [
      "No incompatible whisper contingency is specified as the main procedure.",
      "Reprimands are not described and may escalate attention-maintained behavior.",
      "Chaining a mand may be later programming; this phase is schedule-based free attention.",
      "Noncontingent reinforcement delivers the maintaining reinforcer on a time-based schedule, often abolishing the EO for problem behavior.",
    ],
  ),
  authored(
    1410,
    "G",
    "A child hits to escape math worksheets. The BCBA teaches a card exchange meaning 'break,' ensures each independent card produces a brief break, and withholds break for hitting. Prompting fades as independent exchanges rise. Which package BEST names the core procedure?",
    "C",
    [
      "Token economy with backup menu only.",
      "Dependent group contingency for the class.",
      "Functional communication training (FCT) for a mand that replaces escape-maintained hitting.",
      "Response cost without teaching a communicative alternative.",
    ],
    [
      "Tokens are not required for the described card-exchange break contingency.",
      "No peer-group payoff structure is described.",
      "FCT establishes a communicative response that produces the functional reinforcer previously maintaining problem behavior.",
      "Response cost alone does not establish the break mand.",
    ],
  ),
  authored(
    1411,
    "G",
    "A token economy awards tokens for on-task intervals exchangeable for a backup menu. After six months, tokens pile up unused, backup items rarely change, and on-task behavior declines. Preference probes show menu items are no longer preferred. Which repair BEST restores effectiveness?",
    "B",
    [
      "Increase token prices only, leaving the stale menu unchanged.",
      "Update the backup reinforcer menu based on current preference/reinforcer assessments, ensure exchange opportunities are available, and verify tokens function as conditioned reinforcers.",
      "Remove exchanges entirely and praise only at dismissal.",
      "Switch to punishment tickets without consent revision.",
    ],
    [
      "Raising prices without restoring reinforcer value often worsens contact with backup reinforcement.",
      "Token systems depend on backup reinforcer value and exchange integrity; refreshing preferences and ensuring exchanges reestablish conditioned reinforcement.",
      "Eliminating exchanges abandons the token contingency structure.",
      "Unplanned punishment shifts raise ethical and procedural concerns and do not repair reinforcer value.",
    ],
  ),
  authored(
    1412,
    "G",
    "A teacher proposes that the whole class earn extra recess only if every student meets a daily quiet-voice criterion. One student with limited self-regulation is repeatedly blamed by peers when the class loses recess. Data show peer ridicule rising. Which adjustment BEST addresses the group-contingency risk?",
    "A",
    [
      "Redesign toward independent or carefully managed interdependent goals with protections against peer scapegoating, or use a dependent hero approach that does not publicly punish one learner.",
      "Keep the interdependent rule and add public shaming charts for the lowest performer.",
      "Abandon all reinforcement systems permanently.",
      "Make recess loss longer each day the criterion is missed.",
    ],
    [
      "Interdependent contingencies can produce countercontrol and peer punishment; ethical practice redesigns group contingencies to protect learners from scapegoating.",
      "Public shaming intensifies harm.",
      "Total abandonment ignores workable alternatives.",
      "Escalating loss increases aversiveness without fixing peer dynamics.",
    ],
  ),
  authored(
    1413,
    "G",
    "A high-school learner is taught to self-monitor on-task behavior with a vibrating timer, record plus/minus on a checklist, and self-deliver points exchangeable for preferred leisure. Accuracy is trained with BCBA spot checks that fade as agreement stays high. On-task behavior rises when the system is used. Which approach is this?",
    "D",
    [
      "Noncontingent escape from all academic demands.",
      "Therapist-only DRA with no learner mediation.",
      "Respondent conditioning of the vibrating timer alone.",
      "Self-management combining self-monitoring, self-evaluation, and self-delivered consequences.",
    ],
    [
      "Demands remain; the system manages on-task performance.",
      "The learner mediates recording and point delivery—not therapist-only DRA.",
      "The timer is a prompt/cue within an operant self-management package, not a respondent procedure alone.",
      "Self-management packages typically include monitoring, evaluation against a standard, and consequence delivery by the learner.",
    ],
  ),
  authored(
    1414,
    "G",
    "Mand training used a single flashcard set with one therapist in a therapy room. Mastery criteria were met there, but community probes with novel listeners, varied materials, and natural establishing operations fail. Which programming change BEST targets generalization?",
    "B",
    [
      "Continue identical flashcard drills until community skills appear spontaneously.",
      "Program multiple exemplar training across people, settings, and materials, and incorporate natural establishing operations and reinforcement in target contexts.",
      "Thin all reinforcement to zero immediately in the therapy room only.",
      "Declare generalization unnecessary if clinical graphs look strong.",
    ],
    [
      "Narrow stimulus control rarely transfers without programmed diversity.",
      "Generalization requires deliberate exemplar diversity and practice under naturalistic stimulus and reinforcer conditions.",
      "Abrupt zero reinforcement risks extinction of the mand without building community contact.",
      "Clinical mastery does not equal generalized performance.",
    ],
  ),
  authored(
    1415,
    "G",
    "After acquisition, a BCBA withdraws daily intensive teaching but continues brief, intermittent probes of previously mastered hygiene skills across four weeks. Performance remains accurate without retightening the teaching schedule. Which outcome is being evaluated?",
    "C",
    [
      "Acquisition during dense errorless prompting only.",
      "Stimulus equivalence class formation via matching-to-sample.",
      "Maintenance of behavior over time after teaching intensity is reduced.",
      "Ratio strain under a VR 100 schedule introduced at baseline.",
    ],
    [
      "The phase described follows acquisition and reduces teaching density.",
      "No equivalence matching protocol is described.",
      "Maintenance concerns persistence of performance after intervention thinning or removal over time.",
      "No VR 100 introduction is described in this vignette.",
    ],
  ),
  authored(
    1416,
    "G",
    "A learner's aggression clusters during unstructured transitions. The BCBA inserts visual schedules, pre-transition warnings, and a brief high-probability request sequence before moving between activities, without yet changing consequences for aggression. Transition-related aggression decreases. Which class of intervention is PRIMARY?",
    "A",
    [
      "Antecedent interventions that rearrange environmental cues and transition establishing conditions.",
      "Exclusionary time-out as the sole consequence.",
      "Response cost of tokens after every aggression only.",
      "Full extinction of all mands during transitions.",
    ],
    [
      "Schedules, warnings, and high-p sequences alter antecedents/EOs before behavior occurs—classic antecedent intervention strategies.",
      "No time-out contingency is described as primary.",
      "Consequence-based response cost is not the main change described.",
      "Suppressing mands is not indicated and is not described.",
    ],
  ),
  authored(
    1417,
    "G",
    "A team proposes contingent manual restraint and loud reprimands as first-line treatment for mild task refusal without a functional assessment, crisis plan, assent review, or reinforcement-based alternatives. Data on less restrictive options are absent. As BCBA, which position BEST reflects ethical use of punishment procedures?",
    "D",
    [
      "Implement restraint immediately because refusal wastes instructional minutes.",
      "Use reprimands first for two months, then consider assessment if needed.",
      "Add restraint secretly so caregivers cannot refuse.",
      "Decline punishment-first programming; complete assessment, prioritize reinforcement-based and less restrictive options, obtain informed consent/assent review, and include safety/monitoring if restrictive procedures are ever justified.",
    ],
    [
      "Efficiency claims do not justify unassessed restrictive punishment.",
      "Skipping assessment and reinforcement alternatives violates least-restrictive, function-based practice.",
      "Covert restrictive procedures violate consent and ethics.",
      "Punishment, when used at all, requires strong clinical justification, safeguards, consent, and preferential use of less restrictive function-based strategies first.",
    ],
  ),
  authored(
    1418,
    "G",
    "An FCT break card is taught to fluency, but staff still occasionally remove work after aggression 'to keep the peace,' while sometimes ignoring independent card exchanges during busy moments. Aggression rebounds. Integrity data confirm inconsistent consequences. Which change is MOST critical?",
    "B",
    [
      "Add unexplained response cost for card use to toughen the learner.",
      "Restore treatment integrity: reinforce every appropriate card exchange on the planned schedule and ensure aggression no longer produces escape.",
      "Abandon FCT and return to continuous escape for aggression.",
      "Increase session length only, leaving contingencies unchanged.",
    ],
    [
      "Punishing the alternative communicative response undermines FCT.",
      "FCT effectiveness depends on consistent reinforcement of the communicative alternative and extinction (or consistent non-delivery) of the problem behavior's functional reinforcer.",
      "Reinstating escape for aggression reverses the functional treatment.",
      "Dose of teaching time cannot fix contradictory contingencies.",
    ],
  ),
];
