/**
 * Authored expanded items — Domains B, C, F (BCBA mock exam study bank).
 * Independent study content only; not affiliated with the BACB.
 */
import type { BDSQuestion } from "@/lib/content-types";
import { authored } from "@/content/mockExam/exams/bcbaFull6e/expandedAuthoredHelper";

export const EXPANDED_B: BDSQuestion[] = [
  authored(
    1001,
    "B",
    "During math seatwork, a student tears worksheets and then receives one-to-one adult attention for several minutes while the class continues. Over three weeks, tearing increases whenever independent work begins. Which process BEST accounts for the change?",
    "C",
    [
      "Negative punishment via loss of peer proximity during seatwork",
      "Respondent conditioning pairing worksheets with autonomic arousal alone",
      "Positive reinforcement of tearing by contingent adult attention",
      "Extinction of appropriate work because praise was delayed",
    ],
    [
      "Peer proximity loss is not the programmed consequence described; attention delivery is.",
      "Autonomic arousal may co-occur, but the vignette specifies an operant consequence that strengthens tearing.",
      "Attention follows tearing and the behavior increases under that contingency—defining positive reinforcement.",
      "Delayed praise might weaken work, but the vignette’s primary relation is attention contingent on tearing.",
    ],
  ),
  authored(
    1002,
    "B",
    "A learner’s aggression reliably produces removal of task materials and a brief break. When staff begin blocking aggression and continuing the demand without break, aggression initially intensifies, then declines across sessions. Which account is MOST precise?",
    "A",
    [
      "Extinction of escape-maintained aggression, with an extinction burst followed by decrease",
      "Positive punishment because blocking adds an aversive stimulus each instance",
      "Abolishing operation from satiation on task materials reducing motivation to escape",
      "Stimulus generalization from prior break routines to the new blocking procedure",
    ],
    [
      "Escape was the functional reinforcer; withholding it is extinction, and a temporary increase then decline fits extinction dynamics.",
      "Blocking may feel aversive, but the defining change is removal of the escape reinforcer, not a new contingent punisher schedule.",
      "Satiation would reduce escape motivation before demands; here demands continue and reinforcer contact is withheld.",
      "Generalization concerns stimulus classes across settings; this is a within-contingency extinction effect.",
    ],
  ),
  authored(
    1003,
    "B",
    "A clinic uses a response-cost system: each instance of property destruction removes two tokens from a board the learner otherwise exchanges for a preferred break. Destruction decreases sharply within a week. What BEST names the consequence process?",
    "D",
    [
      "Positive reinforcement of calm waiting by token accumulation alone",
      "Negative reinforcement via escape from the token board itself",
      "Positive punishment through presentation of a reprimand after destruction",
      "Negative punishment: contingent removal of conditioned reinforcers",
    ],
    [
      "Token accumulation may support alternative behavior, but the vignette’s active consequence for destruction is removal.",
      "Escape from the board is not described; tokens are removed contingent on destruction.",
      "No reprimand is specified; the programmed consequence is loss of tokens.",
      "Contingent removal of tokens (conditioned reinforcers) that reduces destruction is negative punishment.",
    ],
  ),
  authored(
    1004,
    "B",
    "Before lunch, a student has had no access to preferred snacks for several hours. When the teacher presents a demand to clean up, the student mands for a snack break at high rates. After a large snack at lunch, the same demand evokes few mands. What BEST explains the change?",
    "B",
    [
      "The demand became an S-delta for mands after lunch through differential reinforcement",
      "Food deprivation established an EO for snack-related mands; satiation abolished that EO",
      "Snack delivery punished mands by pairing them with caloric intake",
      "Stimulus control shifted because the teacher’s tone changed after lunch",
    ],
    [
      "No differential reinforcement of mands versus non-mands after lunch is described.",
      "Deprivation establishes an EO increasing evocative strength and reinforcer value; satiation abolishes it—matching the rate change.",
      "Snack delivery after mands would more often reinforce, not punish, under deprivation.",
      "Tone change is speculative and unnecessary when MO effects account for the data.",
    ],
  ),
  authored(
    1005,
    "B",
    "A BCBA trains a learner to press a blue switch for attention only when a green card is on the table. Presses when the card is absent produce no attention. Soon, nearly all presses occur with the card present. Which concept BEST describes the green card’s role?",
    "A",
    [
      "Discriminative stimulus (SD) signaling attention is available for switch pressing",
      "Establishing operation increasing the value of attention independent of card presence",
      "Conditioned punisher suppressing presses when the card is absent",
      "Neutral stimulus undergoing respondent pairing with attention",
    ],
    [
      "Differential reinforcement in the card’s presence versus absence establishes the card as an SD for the operant.",
      "An EO alters reinforcer value/motivation; the vignette describes differential consequences tied to a cue.",
      "Absence of attention is extinction or SΔ, not presentation of a punisher.",
      "The relation is operant stimulus control, not CS–US respondent pairing as the primary account.",
    ],
  ),
  authored(
    1006,
    "B",
    "A student’s hand-raising is reinforced on a variable-ratio 8 schedule during group instruction. After several successful sessions, the teacher abruptly shifts to VR 40. Hand-raising becomes irregular and then nearly stops despite continued intermittent praise. Which schedule phenomenon is MOST likely?",
    "C",
    [
      "Spontaneous recovery of a previously extinguished operant",
      "Behavioral contrast from concurrent classroom contingencies",
      "Ratio strain from thinning the VR schedule too abruptly",
      "Limited hold expiry on a fixed-interval schedule",
    ],
    [
      "Spontaneous recovery follows extinction rest periods, not abrupt ratio thinning.",
      "Contrast requires comparison across concurrent schedules; only one schedule change is described.",
      "Large, sudden VR increases often produce ratio strain—paused or collapsed responding under lean ratios.",
      "Limited hold and FI parameters are not the programmed schedule here.",
    ],
  ),
  authored(
    1007,
    "B",
    "A learner says “cookie” while looking at a closed jar, and staff deliver a cookie. Later, when shown a picture of a cookie with no access forthcoming, the learner says “cookie” and receives praise for labeling. How do these two utterances DIFFER most usefully for verbal-behavior analysis?",
    "B",
    [
      "Both are pure tacts because the spoken form matches the object class",
      "The first is primarily a mand under deprivation/EO; the second is primarily a tact under nonverbal SD",
      "The first is an echoic; the second is an intraverbal fill-in",
      "Both are intraverbals because they are controlled by prior verbal stimuli only",
    ],
    [
      "Form alone does not determine verbal operant class; controlling variables differ.",
      "Mand control is MO plus specific reinforcement; tact control is nonverbal stimulus plus generalized reinforcement—matching the two contexts.",
      "No vocal model (echoic) or verbal antecedent fill-in (intraverbal) is described for these instances.",
      "Nonverbal stimuli and MOs are central here, not exclusively verbal antecedents.",
    ],
  ),
  authored(
    1008,
    "B",
    "After teaching A→B and B→C matching-to-sample relations without direct A→C training, a learner selects C given A on probe trials and also selects A given C. Which equivalence property is demonstrated by the untrained A–C and C–A performances?",
    "D",
    [
      "Reflexivity only, because each stimulus matches itself",
      "Symmetry of the originally trained A→B relation alone",
      "Transitivity without symmetry, because C→A was not tested",
      "Combined symmetry and transitivity consistent with stimulus equivalence class formation",
    ],
    [
      "Reflexivity is identity matching (A→A); the vignette concerns derived A–C relations.",
      "Symmetry of A→B would be B→A; the novel relation spans A and C via the nodal B.",
      "C→A was tested (learner selects A given C), so symmetry of the derived relation is present along with transitivity.",
      "Untrained A→C (transitivity) plus C→A (symmetry of that derived relation) supports equivalence class formation.",
    ],
  ),
  authored(
    1009,
    "B",
    "A therapist repeatedly pairs a neutral buzzer with a mild puff of air to the eye until the buzzer alone elicits a blink. Separately, the same learner presses a button that historically produced tokens. Which contrast BEST distinguishes the two learning histories?",
    "A",
    [
      "Buzzer–blink is respondent (CS–CR); button–token is operant (response–consequence)",
      "Both are operant because blinking and pressing are skeletal responses",
      "Both are respondent because tokens and air puffs are unconditioned stimuli",
      "Button pressing is respondent extinction while blinking is operant discrimination",
    ],
    [
      "Elicited blink to a formerly neutral cue is respondent; button pressing maintained by tokens is operant.",
      "Topography type does not redefine Pavlovian elicitation as operant reinforcement.",
      "Tokens function as reinforcers for an operant; they are not framing the blink as US-driven alone.",
      "The assignments reverse the actual processes described.",
    ],
  ),
  authored(
    1010,
    "B",
    "A learner masters requesting help with a specific therapist using a card exchange. On a community outing with a new aide, the learner does not exchange the card and instead grabs preferred items. Which generalization failure is MOST clearly illustrated?",
    "C",
    [
      "Response generalization to a new mand topography that still contacts help",
      "Stimulus equivalence failure across card and vocal mand forms",
      "Insufficient stimulus generalization of the mand across people/settings",
      "Overgeneralization of grabbing because grabbing was never reinforced",
    ],
    [
      "Grabbing is not a taught variant of the card mand contacting help as designed.",
      "Equivalence concerns derived stimulus classes, not transfer of a trained mand across people.",
      "Performance under the training person/setting fails to occur with a new aide in community—stimulus generalization gap.",
      "Grabbing likely contacts direct access reinforcement; “never reinforced” contradicts the vignette’s outcome.",
    ],
  ),
  authored(
    1011,
    "B",
    "Staff deliver a mild reprimand each time a student leaves the carpet during circle. Leaving decreases for two days, then returns to baseline rates even though reprimands continue on every instance. Which interpretation is MOST consistent with punishment dynamics?",
    "B",
    [
      "The reprimand functioned as an SD for leaving rather than a punisher",
      "Habituation or loss of aversive effectiveness can weaken an initially effective positive punisher",
      "Negative reinforcement of staying on the carpet fully replaced any punishment process",
      "Extinction of leaving occurred because reprimands removed attention entirely",
    ],
    [
      "If the reprimand were an SD for leaving, leaving would increase, not temporarily decrease.",
      "Initial suppression then recovery despite continued delivery suggests the stimulus lost punishing efficacy (e.g., habituation).",
      "Negative reinforcement of staying is not specified; the programmed consequence was reprimand for leaving.",
      "Reprimands deliver attention; they do not constitute extinction of attention-maintained leaving.",
    ],
  ),
  authored(
    1012,
    "B",
    "A fixed-interval 5-minute schedule delivers praise for the first correct problem after each 5-minute bin. Graphing shows low responding early in each interval and a sharp increase as the 5-minute mark approaches. What pattern is this?",
    "D",
    [
      "Break-and-run pattern typical of fixed-ratio schedules",
      "Steady moderate rate characteristic of variable-interval schedules",
      "Post-reinforcement pause exclusive to differential reinforcement of low rates",
      "FI scallop: accelerating response rate toward the end of the interval",
    ],
    [
      "FR break-and-run features a pause then high steady run, not acceleration tied to elapsed interval time.",
      "VI typically produces steadier rates without a strong end-of-interval acceleration.",
      "DRL spaces responses by imposing an IRT criterion; the vignette is a standard FI.",
      "Accelerating rates near interval end under FI is the classic scallop.",
    ],
  ),
  authored(
    1013,
    "B",
    "After weeks of ignoring attention-maintained loud vocalizations (extinction), rates fall near zero. Following a two-week school break with no programmed consequences, the first day back shows a brief reappearance of loud vocalizations that then decline again without reinforcement. Which process BEST names the reappearance?",
    "A",
    [
      "Spontaneous recovery of the extinguished operant after time away from the extinction context",
      "Resurgence of an alternative mand that was never trained",
      "Renewal solely because the physical classroom was remodeled",
      "Behavioral contrast from richer reinforcement in a concurrent PE class",
    ],
    [
      "Time away from extinction followed by brief reappearance then re-decline fits spontaneous recovery.",
      "Resurgence is recovery of a previously reinforced alternative when a more recently reinforced alternative contacts extinction.",
      "Renewal is context-change reappearance; remodeling is not stated—only a temporal break.",
      "No concurrent schedule contrast data are provided.",
    ],
  ),
  authored(
    1014,
    "B",
    "A BCBA pairs a neutral token with backup snacks by delivering a snack immediately after each token for several sessions. Later, tokens alone maintain task completion when snacks are delayed until session end. What BEST describes the tokens’ current function?",
    "C",
    [
      "Unconditioned reinforcers because snacks are biologically relevant",
      "Discriminative stimuli for snack delivery that never acquire reinforcing value themselves",
      "Conditioned reinforcers that maintain behavior through a pairing/exchange history",
      "Abolishing operations that reduce the value of task completion",
    ],
    [
      "Tokens are not unconditioned; their value derives from pairing/exchange with backups.",
      "Tokens can serve as SDs in some arrangements, but here they maintain responding as reinforcers when delayed backups still follow.",
      "Pairing and later exchange establish tokens as conditioned reinforcers supporting operant task completion.",
      "Tokens increasing task completion indicates reinforcement value, not an abolishing operation.",
    ],
  ),
  authored(
    1015,
    "B",
    "During free play, a child accesses toys whether or not they complete a clean-up routine. Clean-up remains near zero. The BCBA then arranges that preferred outdoor play follows only after clean-up completion; indoor toy access continues noncontingently. Clean-up rises. Which analysis is MOST accurate?",
    "B",
    [
      "Noncontingent indoor toys punished clean-up through competing reinforcement",
      "Differential reinforcement made outdoor play contingent on clean-up while weakening the prior noncontingent outdoor access contingency",
      "Extinction of play behavior produced clean-up as a side effect of frustration",
      "The clean-up routine became an EO that established outdoor play as a reinforcer",
    ],
    [
      "Indoor NCR may compete, but the vignette’s effective change is making outdoor play contingent on clean-up.",
      "Clean-up contacts a valued consequence (outdoor play) that previously did not require clean-up—differential positive reinforcement of clean-up.",
      "Play was not extinguished; it was rearranged contingently.",
      "Outdoor play’s reinforcing value likely preceded the contingency; clean-up is the operant, not the EO for outdoor play.",
    ],
  ),
  authored(
    1016,
    "B",
    "A learner’s problem behavior occurs at high rates in a noisy cafeteria but near zero in a quiet therapy room with the same demand materials. Careful analysis shows that cafeteria noise precedes behavior and that escape from noise (via staff removing the learner) has historically followed. Which framework BEST organizes these findings?",
    "D",
    [
      "Noise is solely an SD for demands; escape is irrelevant",
      "Noise is an AO that abolishes the value of escape",
      "Demands are respondent CSs; noise is an operant reinforcer",
      "Noise may function as an aversive EO/context elevating escape motivation, with removal reinforcing problem behavior",
    ],
    [
      "Escape history is central; treating noise as only an SD for demands omits the consequence relation.",
      "An AO would decrease escape value; rates are higher in noise, suggesting establishing, not abolishing, effects.",
      "Noise removal is an operant consequence; demands are not framed as CS elicitors here.",
      "Aversive contexts can establish escape as valuable; contingent removal then reinforces the problem operant.",
    ],
  ),
  authored(
    1017,
    "B",
    "On concurrent VR schedules, a student allocates about 80% of responses to a math app that pays tokens on VR 5 and 20% to a reading app on VR 20. Token exchange values are equal. Which principle MOST directly accounts for the allocation?",
    "A",
    [
      "Matching law: relative response rates track relative reinforcement rates across alternatives",
      "Premack principle: high-probability reading reinforces low-probability math",
      "Behavioral momentum: math resistance to change depends only on session length",
      "Stimulus generalization gradient peaking at VR 5 schedule values",
    ],
    [
      "Richer VR 5 yields higher reinforcement density; allocation favoring that alternative aligns with matching.",
      "Premack concerns using a high-probability activity as a reinforcer for a low-probability one, not concurrent VR allocation.",
      "Momentum addresses persistence under disruption; the vignette concerns steady-state choice allocation.",
      "Generalization gradients concern stimulus dimensions, not concurrent schedule matching.",
    ],
  ),
];

export const EXPANDED_C: BDSQuestion[] = [
  authored(
    1101,
    "C",
    "A BCBA needs a measure that captures how often aggression occurs during 30-minute sessions and allows comparison across sessions that occasionally run 25 or 35 minutes. Which dimensional quantity is MOST appropriate?",
    "B",
    [
      "Count alone without dividing by time",
      "Rate (count per unit time) of aggression",
      "Percent of intervals with aggression using whole-interval recording",
      "Latency from session start to first aggression only",
    ],
    [
      "Raw count confounds session length differences.",
      "Rate standardizes count by time, enabling fair comparison across unequal session durations.",
      "Whole-interval percent estimates occurrence roughly and underestimates brief events; it is not the dimensional rate quantity requested.",
      "Latency describes time to first instance, not overall frequency across the session.",
    ],
  ),
  authored(
    1102,
    "C",
    "Staff want to know how long tantrums last once they begin during transitions. Observers start a timer at tantrum onset and stop at offset using a clear definition. Which measure are they collecting?",
    "A",
    [
      "Duration of each tantrum episode",
      "Interresponse time between successive tantrums",
      "Trials-to-criterion for transition compliance",
      "Momentary time sampling of tantrum presence",
    ],
    [
      "Timing from onset to offset yields duration of the episode.",
      "IRT is the time between consecutive responses’ onsets/offsets, not the length of one episode.",
      "Trials-to-criterion tracks acquisition across discrete trials, not episode length.",
      "MTS samples presence at instants; continuous timing is duration recording.",
    ],
  ),
  authored(
    1103,
    "C",
    "A teacher starts a demand and records the seconds until the learner begins the first correct step. Over baseline, this value averages 45 seconds; after prompting protocol changes, it averages 12 seconds. What was measured?",
    "C",
    [
      "Duration of the completed task chain",
      "Rate of correct steps per minute across the session",
      "Latency to initiate the correct response after the demand",
      "Percent correct on discrete-trial acquisition probes",
    ],
    [
      "Duration would time the full chain from start to finish, not only time to initiation.",
      "Rate summarizes counts over time, not delay to the first correct step.",
      "Seconds from demand to initiation is latency.",
      "Percent correct concerns accuracy across trials, not temporal delay to start.",
    ],
  ),
  authored(
    1104,
    "C",
    "Observers use 10-second partial-interval recording for stereotypy during 15-minute samples. The BCBA warns the team that the graphed percentages will likely overestimate true occurrence. Why is that warning justified?",
    "D",
    [
      "Partial interval records an interval only if stereotypy fills the entire interval",
      "Partial interval underestimates high-rate brief behaviors by design",
      "Partial interval equals continuous duration measurement when intervals are short",
      "Any stereotypy in the interval scores the whole interval, inflating estimated occurrence for brief events",
    ],
    [
      "That rule describes whole-interval recording, which underestimates.",
      "Partial interval tends to overestimate, not underestimate, brief/high-rate events.",
      "Even short intervals remain discontinuous estimates, not continuous duration.",
      "Scoring the full interval for any occurrence systematically overestimates absolute time spent engaging in brief stereotypy.",
    ],
  ),
  authored(
    1105,
    "C",
    "A clinic switches from partial-interval to whole-interval recording of on-task behavior to decide whether a learner meets a 80% on-task goal. After the switch, graphed on-task percentages drop even though informal observation suggests similar engagement. What BEST explains the drop?",
    "A",
    [
      "Whole-interval requires engagement throughout the interval, so brief off-task moments prevent scoring—typically underestimating on-task",
      "Whole-interval overestimates on-task relative to partial interval for the same stream of behavior",
      "Whole-interval measures latency rather than occurrence, lowering percentages mathematically",
      "Observer drift always decreases scores when methods change regardless of definition",
    ],
    [
      "Whole-interval is stringent for continuous behaviors and commonly underestimates on-task compared with partial interval.",
      "Partial interval overestimates occurrence; whole interval underestimates—opposite of this option.",
      "Whole-interval is still an occurrence estimate within intervals, not a latency measure.",
      "Method change itself alters the estimate; invoking drift as inevitable is unsupported.",
    ],
  ),
  authored(
    1106,
    "C",
    "Two observers independently score 20 discrete trials as correct or incorrect. They agree on 17 trials. Which IOA method and result are appropriate to report?",
    "B",
    [
      "Total count IOA of 85% based on summing corrects only",
      "Trial-by-trial (point-by-point) IOA of 85% (17/20)",
      "Scored-interval IOA excluding all incorrect trials from the denominator",
      "Exact agreement IOA for duration measures on each trial",
    ],
    [
      "Total count IOA compares overall totals and can mask trial-level disagreements.",
      "For trial scoring, point-by-point agreement is agreements divided by trials: 17/20 = 85%.",
      "Scored-interval IOA is for interval systems focusing on intervals with occurrence, not this discrete-trial layout.",
      "Exact agreement duration IOA applies to continuous timing data, not correct/incorrect trials.",
    ],
  ),
  authored(
    1107,
    "C",
    "A measurement system yields nearly identical scores when two trained observers record the same sessions (high IOA), yet the operational definition accidentally includes laughing during instruction as “aggression.” Decision-making based on these data is still flawed. Which quality is MOST clearly deficient?",
    "C",
    [
      "Reliability, because observers cannot agree under the written definition",
      "Accuracy, because IOA below 80% is implied by the vignette",
      "Validity, because the system consistently measures the wrong behavioral class",
      "Believability only, which is independent of definitional fit to the target",
    ],
    [
      "High IOA indicates observers apply the (flawed) definition consistently—reliability is relatively intact.",
      "The vignette states high agreement; it does not imply IOA below 80%.",
      "Consistent measurement of the wrong events is a validity problem: data do not represent the intended construct.",
      "Believability is enhanced by IOA but does not salvage invalid definitions.",
    ],
  ),
  authored(
    1108,
    "C",
    "An RBT graphs daily rate of mands on an equal-interval line graph. The BCBA wants to detect proportional multiply/divide changes in celeration across weeks for a precision-teaching aim. Which display is MORE aligned with that goal?",
    "D",
    [
      "A bar graph of weekly totals without a time axis",
      "A cumulative record that resets to zero each day",
      "A pie chart of mand topographies within one session",
      "A Standard Celeration Chart (semi-logarithmic) suited to celeration analysis",
    ],
    [
      "Bar totals obscure continuous celeration trends across calendar time.",
      "Cumulative records show add-up counts; daily reset further obscures multi-week celeration.",
      "Pie charts show part-to-whole composition, not rate change over time.",
      "The SCC’s logarithmic frequency scale is designed for celeration (multiply/divide) interpretation.",
    ],
  ),
  authored(
    1109,
    "C",
    "A team evaluates handwriting improvement by counting correctly formed letters on worksheets completed when the teacher was not continuously watching. Which measurement approach is this?",
    "A",
    [
      "Permanent product recording of letter formation outcomes",
      "Continuous duration recording of pencil grasp",
      "Momentary time sampling of on-task posture during writing",
      "Event recording of each pencil lift in real time",
    ],
    [
      "Worksheets are lasting products that can be scored after the fact—permanent product measurement.",
      "Duration of grasp requires ongoing timing of a continuous topography.",
      "MTS samples momentary states, not product quality of letters.",
      "Real-time event recording of lifts is direct observation, not product-based scoring.",
    ],
  ),
  authored(
    1110,
    "C",
    "Observers disagree about whether “flopping” includes kneeling with hands on the floor. IOA is poor on transition intervals. Which action BEST improves measurement quality first?",
    "B",
    [
      "Switch to partial-interval recording without revising the definition",
      "Tighten the operational definition with inclusive/exclusive examples and retrain observers",
      "Average the two observers’ scores and graph the mean to hide disagreement",
      "Shorten sessions so fewer opportunities for disagreement occur",
    ],
    [
      "Changing discontinuous methods does not resolve ambiguous response class boundaries.",
      "Clear operational definitions plus retraining are foundational when IOA failures track definitional ambiguity.",
      "Averaging masks unreliability and does not improve the measurement system.",
      "Fewer opportunities do not fix systematic definition problems.",
    ],
  ),
  authored(
    1111,
    "C",
    "A BCBA uses momentary time sampling every 2 minutes to estimate in-seat behavior during a 40-minute class. At each beep, the observer glances and records whether the learner is seated. Which statement about this system is MOST accurate?",
    "C",
    [
      "MTS yields an exact duration total equal to continuous timing when intervals are equal",
      "MTS overestimates duration for all behaviors more than partial-interval recording does",
      "MTS estimates the proportion of sample points with the behavior and can miss events between observations",
      "MTS is inappropriate for continuous behaviors and may only be used for discrete counts",
    ],
    [
      "MTS remains a sample; it does not equal continuous duration measurement.",
      "Partial interval more typically overestimates occurrence of brief behaviors; MTS error direction depends on behavior patterning.",
      "MTS scores presence at scheduled instants—useful estimates that can miss between-sample occurrences.",
      "MTS is commonly used for continuous behaviors such as in-seat or on-task.",
    ],
  ),
  authored(
    1112,
    "C",
    "On a cumulative record of correct math problems, the slope is steep for 10 minutes, then flat for 15 minutes, then steep again. Which interpretation of the flat segment is MOST appropriate?",
    "D",
    [
      "Response rate was negative during the flat segment",
      "The y-axis scale changed automatically mid-session",
      "Interobserver disagreement created an artificial plateau",
      "Little or no additional correct responding accumulated during that period",
    ],
    [
      "Cumulative records do not go backward for ordinary correct counts; flat means near-zero additions.",
      "Nothing indicates a mid-session axis rescaling.",
      "IOA issues are not implied by a flat cumulative slope alone.",
      "A flat cumulative slope indicates few or no new counted responses were added.",
    ],
  ),
  authored(
    1113,
    "C",
    "Two observers record duration of property destruction. Observer A times 120 seconds; Observer B times 100 seconds for the same episode. Using the shorter/longer formula for duration IOA, what should be reported?",
    "A",
    [
      "Approximately 83% duration IOA (100/120)",
      "20% IOA because the absolute difference is 20 seconds",
      "110% IOA by averaging the two durations first",
      "Trial-by-trial IOA of 0% because durations are never identical",
    ],
    [
      "Duration IOA commonly uses smaller duration divided by larger: 100/120 ≈ 83%.",
      "Absolute difference is not the standard percent agreement metric.",
      "Averaging then dividing can exceed 100% and is not the smaller/larger convention.",
      "Trial-by-trial applies to discrete trial scoring; duration uses continuous-agreement formulas.",
    ],
  ),
  authored(
    1114,
    "C",
    "A program claims “reliability” because a computer sensor logged identical aggression counts on two replays of the same video file. Caregivers still say the coded events do not match what they mean by aggression at home. Which distinction should the BCBA emphasize?",
    "B",
    [
      "Replay agreement proves social validity of the target definition",
      "Consistent sensor output shows reliability/repeatability of that coding rule, not necessarily validity or social meaningfulness",
      "If reliability is perfect, accuracy and validity are automatically satisfied",
      "Caregiver disagreement indicates the sensor’s temporal resolution is too fine",
    ],
    [
      "Social validity concerns stakeholder meaningfulness, not machine replay consistency.",
      "Repeatability under the same rule is reliability; caregivers questioning the definition flags validity/social validity concerns.",
      "Reliability does not entail accuracy or validity when the rule itself is misaligned.",
      "The conflict is definitional fit, not primarily sensor sampling rate.",
    ],
  ),
  authored(
    1115,
    "C",
    "For a skill acquired in discrete trials, the BCBA graphs percent correct per session. Sessions sometimes include 5 trials and sometimes 20 because of time. A colleague argues the graph may mislead. What is the STRONGEST measurement concern?",
    "C",
    [
      "Percent correct cannot be used for discrete-trial data under any condition",
      "Unequal trials are irrelevant because percent always equalizes difficulty",
      "Small denominators make percentages unstable; a 5-trial session can swing wildly compared with 20-trial sessions",
      "Percent correct measures latency and therefore conflicts with acquisition graphs",
    ],
    [
      "Percent correct is a standard discrete-trial summary when trial counts are adequate and comparable.",
      "Percent does not equalize the sampling stability of small versus large trial blocks.",
      "With few trials, each error moves the percentage dramatically—comparability across unequal denominators is a real concern.",
      "Percent correct is an accuracy measure, not latency.",
    ],
  ),
];

export const EXPANDED_F: BDSQuestion[] = [
  authored(
    1201,
    "F",
    "A BCBA needs a rapid classroom preference screen for six edible items with a learner who selects when an array is presented. The BCBA presents all six, allows one selection, removes that item, and re-presents the remaining items until the array is exhausted, repeating across sessions. Which assessment is this?",
    "A",
    [
      "Multiple-stimulus without replacement (MSWO) preference assessment",
      "Paired-stimulus (forced-choice) preference assessment",
      "Free-operant preference assessment with unrestricted access to all items",
      "Progressive-ratio reinforcer assessment of break-point values",
    ],
    [
      "Array presentation with removal after selection and re-presentation of remainders is MSWO.",
      "Paired-stimulus presents two items at a time across pairings, not a shrinking full array.",
      "Free-operant allows concurrent access without successive removal from a forced array.",
      "Progressive-ratio tests reinforcer efficacy under increasing schedule requirements, not preference ranking via selection arrays.",
    ],
  ),
  authored(
    1202,
    "F",
    "MSWO ranks a tablet first, yet when the BCBA delivers tablet access contingent on a non-preferred sorting task, sorting does not increase across three sessions. Preference rankings for other items remain stable. What is the MOST appropriate next assessment step?",
    "C",
    [
      "Conclude the learner cannot be reinforced by tangible stimuli",
      "Replace preference assessment with a descriptive ABC only",
      "Conduct a reinforcer assessment testing whether contingent tablet access increases a target response relative to baseline",
      "Switch immediately to an alone-condition functional analysis of sorting",
    ],
    [
      "One failed contingency does not prove tangibles never reinforce; efficacy must be tested and alternatives considered.",
      "ABC describes problem behavior contexts; it does not establish whether a preferred item functions as a reinforcer for sorting.",
      "Preference ≠ reinforcement function; a reinforcer assessment directly tests contingent delivery effects on behavior.",
      "FA conditions target problem-behavior function, not whether tablet reinforces sorting.",
    ],
  ),
  authored(
    1203,
    "F",
    "Caregivers complete an interview and a rating scale suggesting attention maintains aggression. Direct ABC data over five days show aggression primarily when difficult tasks are presented and typically followed by task removal, with little attention delivery. Which conclusion is MOST defensible?",
    "B",
    [
      "Indirect tools are gold-standard; ignore descriptive data when they conflict",
      "Indirect and descriptive results diverge—treat attention as tentative and prioritize escape as a leading hypothesis pending experimental analysis",
      "Descriptive data prove automatic reinforcement because task removal is irrelevant",
      "Rating scales alone justify an attention extinction plan without further assessment",
    ],
    [
      "Indirect methods are useful but not definitive when contradicted by observation.",
      "Conflict warrants cautious hypotheses; descriptive patterns point to escape, and FA can confirm.",
      "Task removal following aggression supports escape, not automatic reinforcement.",
      "Ethics and best practice require converging evidence before function-based extinction plans.",
    ],
  ),
  authored(
    1204,
    "F",
    "During a functional analysis, aggression is high in escape and low in attention, tangible, and play (control). Demand fading and break contingencies are being considered. Which functional interpretation is BEST supported?",
    "D",
    [
      "Aggression is multiply maintained by attention and escape equally",
      "Aggression is maintained by automatic reinforcement because control is low",
      "The FA is inconclusive because tangible was not the highest condition",
      "Aggression is primarily escape-maintained under the tested conditions",
    ],
    [
      "Attention was low; equal multiple control is not indicated.",
      "Low control with high escape points to social-negative reinforcement, not automatic.",
      "A clear elevated escape condition with low others is conclusive for escape under those tests.",
      "Differentially high escape rates support an escape function interpretation.",
    ],
  ),
  authored(
    1205,
    "F",
    "In an FA, hand mouthing is elevated and undifferentiated across alone, attention, escape, and tangible conditions, remaining high in alone. Which interpretation is MOST consistent?",
    "A",
    [
      "Behavior is likely automatically maintained (sensory consequences independent of social mediation)",
      "Behavior is exclusively escape-maintained because demands appear in one condition",
      "Undifferentiated patterns always mean the FA was improperly implemented",
      "Attention is the function because mouthing can be seen by others",
    ],
    [
      "High rates in alone and similar elevation across conditions commonly indicate automatic reinforcement.",
      "Exclusive escape would show differentiation with elevated escape relative to alone/control.",
      "Undifferentiated patterns can be informative (automatic) or sometimes procedural—but alone elevation supports automatic.",
      "Visibility to others does not establish attention as the maintaining reinforcer.",
    ],
  ),
  authored(
    1206,
    "F",
    "A school team wants only interviews and a FAST checklist before writing a BIP for severe self-injury, citing time pressure. The BCBA recommends adding direct observation and, if safe/feasible, experimental analysis. What BEST justifies that recommendation?",
    "B",
    [
      "Indirect assessments are unethical in all cases and never contribute useful information",
      "Indirect tools can misidentify function; descriptive and experimental methods improve confidence before function-based treatment",
      "Experimental FA is required by law for every BIP regardless of risk or setting constraints",
      "Direct observation replaces the need for any operational definition of self-injury",
    ],
    [
      "Indirect methods can contribute hypotheses; the issue is over-reliance without converging evidence.",
      "Stronger assessment hierarchies reduce false function identification and improve BIP match to maintaining variables.",
      "FA is best practice when indicated but is not universally legally mandated in every context without clinical judgment.",
      "Operational definitions remain necessary for any direct measurement system.",
    ],
  ),
  authored(
    1207,
    "F",
    "ABC continuous recording shows that peer teasing often precedes hitting, and hitting is frequently followed by peers leaving the area. Staff attention is inconsistent afterward. Which functional hypothesis is MOST coherent with these descriptive data?",
    "C",
    [
      "Hitting is maintained by access to tangible preferred toys exclusively",
      "Hitting is maintained by adult attention in the form of reprimands alone",
      "Hitting may be maintained by socially mediated negative reinforcement (escape from peer teasing) and/or peer avoidance",
      "Hitting is automatically maintained because peers are not therapists",
    ],
    [
      "Toy access is not the consistent consequent in the vignette.",
      "Adult reprimands are described as inconsistent; peer departure is the clearer consequent pattern.",
      "Teasing as antecedent and peers leaving as consequence support escape/avoidance of aversive peer interactions.",
      "Social peer consequences can maintain behavior; “not therapists” does not imply automatic function.",
    ],
  ),
  authored(
    1208,
    "F",
    "A BCBA conducts a free-operant preference assessment: multiple leisure items are available simultaneously, and the observer records duration of engagement with each item without removing items after contact. What is a PRIMARY advantage of this format?",
    "D",
    [
      "It always produces a clearer ordinal rank than MSWO for edibles",
      "It requires problem behavior to occur before preferences can be scored",
      "It forces selection of a single item by blocking access to all competitors",
      "It allows measurement of engagement under low demand and can be useful when learners do not select from arrays",
    ],
    [
      "MSWO often yields clearer ranks; free-operant may show engagement without forced ranking.",
      "Preference assessment does not require problem behavior as a prerequisite.",
      "Free-operant specifically does not force single-item selection via removal/blocking as in MSWO.",
      "Simultaneous access and duration recording suit learners who engage but do poorly with selection arrays.",
    ],
  ),
  authored(
    1209,
    "F",
    "An FA attention condition shows moderate aggression, but video review reveals the therapist accidentally delivered brief breaks after several aggressive responses during that condition. Escape and play conditions were implemented as written. How should the BCBA treat the attention-condition data?",
    "A",
    [
      "Interpret cautiously or repeat the condition—procedural drift confounded attention with escape contingencies",
      "Treat the results as clean evidence of multiply controlled aggression",
      "Discard the entire FA permanently and rely only on caregiver interview",
      "Relabel the attention condition as tangible because breaks involve leaving the table",
    ],
    [
      "Unplanned escape during “attention” contaminates interpretation; integrity repair/replication is needed.",
      "Multiple control should not be inferred from a known integrity failure.",
      "One compromised condition does not obligate abandoning experimental analysis entirely.",
      "Breaks following aggression are escape-like, but arbitrarily relabeling without retesting is poor practice.",
    ],
  ),
  authored(
    1210,
    "F",
    "A preschool team needs a broad early-learner skills picture spanning mands, tacts, listener skills, and barriers, with milestone levels to guide IEP priorities. Which tool is MOST specifically designed for that purpose among common ABA curricula assessments?",
    "B",
    [
      "A scatterplot of problem behavior across clock hours only",
      "VB-MAPP milestone and barriers assessment components",
      "A progressive-ratio reinforcer assessment schedule alone",
      "An alone-condition FA without skill probes",
    ],
    [
      "Scatterplots organize problem-behavior timing, not verbal/skill repertoires.",
      "VB-MAPP is built to assess verbal behavior milestones and related barriers for early learners.",
      "Progressive ratio tests reinforcer strength, not a curriculum skills profile.",
      "FA alone conditions assess automatic reinforcement of problem behavior, not skill repertoires.",
    ],
  ),
  authored(
    1211,
    "F",
    "An agency already uses a detailed task-analysis style inventory of hundreds of discrete skills across domains (e.g., self-help, academic, social) with criterion-referenced scoring to build programs. Which tool does this description BEST match?",
    "C",
    [
      "Standard Celeration Chart aiming aims list",
      "FAST indirect function checklist",
      "ABLLS-R (or similar ABLLS) skills grid assessment",
      "Brief MSWO edible preference hierarchy only",
    ],
    [
      "SCC aims guide fluency measurement, not a multi-domain skills inventory of this type.",
      "FAST screens hypothesized functions of problem behavior.",
      "ABLLS-type assessments provide extensive criterion-referenced skill grids for program development.",
      "MSWO ranks preferences, not broad skill repertoires.",
    ],
  ),
  authored(
    1212,
    "F",
    "Before teaching a 12-step dressing chain, the BCBA probes each step without prompts across three days and records independent performance. Several middle steps are never completed independently. What is the PRIMARY purpose of this assessment activity?",
    "D",
    [
      "To identify the function of problem behavior during dressing",
      "To establish preference hierarchies for clothing items",
      "To compute IOA on caregiver interview responses",
      "To obtain a skill baseline that identifies which chain steps require instruction",
    ],
    [
      "Step probing without measuring consequences of problem behavior is not an FBA.",
      "Clothing preference is not what independent step probes assess.",
      "IOA on interviews is unrelated to performance probes of dressing steps.",
      "Baseline skill assessment maps current independent performance to guide where to teach.",
    ],
  ),
  authored(
    1213,
    "F",
    "A paired-stimulus preference assessment yields a clear hierarchy. The BCBA then tests the top item against a low-ranked item by delivering each contingent on an arbitrary response in alternating micro-sessions and comparing response rates. What was the second procedure?",
    "A",
    [
      "A reinforcer assessment evaluating relative reinforcing efficacy of ranked items",
      "A multiple-stimulus with replacement preference assessment",
      "A descriptive structural analysis of classroom seating",
      "An experimental FA tangible condition without control",
    ],
    [
      "Contingent delivery with rate comparison tests whether preferred items actually reinforce responding.",
      "MSW is a preference array method, not contingent reinforcer testing.",
      "Structural analysis examines environmental antecedents/settings for problem behavior.",
      "FA tangible conditions test problem-behavior function, not arbitrary response reinforcement by ranked items.",
    ],
  ),
  authored(
    1214,
    "F",
    "Scatterplot data collected across two weeks show self-injury clustered almost exclusively during unstructured hallway transitions after lunch, with near-zero rates during seated academic blocks. Interviews had suggested “random” occurrence. How should these findings guide hypothesis development?",
    "B",
    [
      "Discard scatterplot data because interviews are more valid for temporal patterns",
      "Hypothesize context-specific variables during transitions (e.g., noise, crowding, demands to move) and plan targeted descriptive or experimental analysis in those periods",
      "Conclude automatic reinforcement solely because academic blocks are low",
      "Assume attention function because hallways contain adults",
    ],
    [
      "Direct temporal patterns often correct inaccurate interview impressions.",
      "Time-clustered data point assessment toward transition-related antecedents/consequences rather than global “random” accounts.",
      "Low academic rates do not by themselves prove automatic reinforcement.",
      "Adult presence is insufficient to identify attention as the maintaining consequence.",
    ],
  ),
  authored(
    1215,
    "F",
    "A learner’s property destruction is high in tangible and escape FA conditions and low in attention and play. Caregivers report destruction when denied snacks and when presented with chores. Which statement BEST synthesizes assessment results?",
    "C",
    [
      "The FA is invalid whenever two conditions are elevated",
      "Only chore-related escape can be treated; tangible denial must be ignored",
      "Findings support multiple control (access and escape); intervention should address both functional relations",
      "Play-condition rates being low disproves any social function",
    ],
    [
      "Multiple elevated test conditions are interpretable as multiple control when control remains low.",
      "Ignoring a supported tangible function risks incomplete treatment.",
      "Converging FA and caregiver contexts for both denial and chore escape support multiply maintained destruction.",
      "Low play supports differentiation from control; it does not erase social test-condition elevations.",
    ],
  ),
  authored(
    1216,
    "F",
    "After indirect assessment, a BCBA writes: “When presented with multi-step vocational tasks, learner engages in loud vocal protest; protest is typically followed by staff completing the task for the learner. Hypothesis: protest is maintained by escape from task demands.” What makes this a strong functional hypothesis statement?",
    "D",
    [
      "It names a topography without referencing antecedents or consequences",
      "It attributes protest to an internal personality trait that explains all settings",
      "It asserts a function without describing the contingency that would produce reinforcement",
      "It ties a specific antecedent class and a plausible maintaining consequence into a testable contingency account",
    ],
    [
      "Strong hypotheses specify controlling variables, not topography alone.",
      "Trait explanations are not function-based contingency hypotheses.",
      "The sample statement does include a maintaining consequence (task completion by staff / escape).",
      "Antecedent (multi-step tasks) + behavior + consequence (escape via staff completion) yields a clear, testable functional hypothesis.",
    ],
  ),
];
