/**
 * Authored expanded mock items — Domains A, D, H, I.
 * Independent study only. Not affiliated with the BACB.
 */
import type { BDSQuestion } from "@/lib/content-types";
import { authored } from "@/content/mockExam/exams/bcbaFull6e/expandedAuthoredHelper";

export const EXPANDED_A: BDSQuestion[] = [
  authored(
    901,
    "A",
    "During case consultation, a colleague insists that a client's covert self-statements are causes of aggression but cannot themselves be analyzed as behavior because they are unobservable. A second colleague argues that verbal reports of those self-statements are behavior under environmental control and can enter contingency analysis with appropriate measurement caveats. Which stance MOST closely reflects radical behaviorism?",
    "B",
    [
      "Agree that private events are permanently outside behavior-analytic scope and refer all such concerns to nonbehavioral disciplines.",
      "Treat private events as behavior subject to the same selection contingencies as public behavior, while acknowledging observational constraints on measurement.",
      "Require physiological imaging before any verbal report of private events may be discussed in case formulation.",
      "Adopt methodological behaviorism by defining only publicly observed motor topographies as legitimate subject matter.",
    ],
    [
      "Radical behaviorism does not exile private events from analysis; referral alone does not answer the philosophical question.",
      "Radical behaviorism includes private events as behavior influenced by environmental history, while remaining honest about measurement limits.",
      "Imaging may inform some questions but is not required for treating verbal reports as behavior under contingency analysis.",
      "Methodological behaviorism restricts analysis to public events; radical behaviorism explicitly includes private events.",
    ],
  ),
  authored(
    902,
    "A",
    "A trainee explains a sudden drop in tantrum rate by inventing three nested motivational constructs that were never measured, then adds a fourth when the graph still looks uneven. The supervisor asks which scientific attitude is MOST violated by stacking unverified mechanisms when a simpler contingency account already fits the data.",
    "A",
    [
      "Parsimony—prefer the simplest explanation that accounts for the observed data rather than multiplying untested constructs.",
      "Determinism—assume behavior is lawful, so any account is acceptable if it sounds causal.",
      "Empiricism—require that every explanation cite a brand-name published protocol regardless of fit.",
      "Pragmatism—judge explanations solely by how persuasive they sound to caregivers in the moment.",
    ],
    [
      "Parsimony favors explanatory sufficiency with the fewest assumptions; redundant constructs without data violate that attitude.",
      "Determinism asserts lawfulness of behavior; it does not license unconstrained construct proliferation.",
      "Empiricism emphasizes observation and measurement; it does not demand protocol name-dropping over data fit.",
      "Pragmatism evaluates usefulness of an account for prediction and control, not momentary rhetorical appeal.",
    ],
  ),
  authored(
    903,
    "A",
    "A school team debates why a student's escape-maintained aggression decreased after lunchtime recess was lengthened. One clinician attributes the change to free will and a sudden 'decision to be good.' Another frames the change as selection by consequences operating on the student's repertoire in that context. Which philosophical orientation BEST supports the second clinician's account?",
    "C",
    [
      "Mentalism that treats inner agency as the primary causal unit independent of environment.",
      "Dualism that separates mind-caused choices from environmentally selected operants.",
      "Selectionism—variation and differential reinforcement shape which responses persist in a given context.",
      "Nativism that treats all rate changes as unfolding maturational schedules unaffected by contingencies.",
    ],
    [
      "Mentalistic free-will accounts bypass environmental selection and conflict with behavior-analytic foundations.",
      "Dualism preserves a nonenvironmental causal realm; selectionism keeps causation in contingency history.",
      "Selectionism explains repertoire change via variation and differential consequences across phylogenetic, ontogenetic, and cultural levels.",
      "Maturational nativism does not explain contingency-correlated shifts tied to recess duration changes.",
    ],
  ),
  authored(
    904,
    "A",
    "A BCBA declines to endorse a popular packaged curriculum until the clinic can collect its own session-by-session data showing whether the package changes the target response under the local conditions. A stakeholder complains that waiting for data is 'anti-innovation.' Which scientific attitude MOST justifies the BCBA's stance?",
    "D",
    [
      "Fatalism—outcomes are fixed, so data collection cannot alter practice decisions.",
      "Structuralism—classify topographies without relating them to environmental function.",
      "Circular reasoning—define the intervention as effective because it is marketed as evidence-based.",
      "Empiricism—ground claims about effectiveness in systematic observation and measurement rather than reputation alone.",
    ],
    [
      "Fatalism contradicts the assumption that behavior is open to environmental influence and measurement.",
      "Structural classification alone does not validate intervention effects under local conditions.",
      "Marketing labels are not substitutes for observation; circular endorsement is the problem, not the solution.",
      "Empiricism requires that effectiveness claims rest on observed data, including local evaluation when adopting packages.",
    ],
  ),
];

export const EXPANDED_D: BDSQuestion[] = [
  authored(
    911,
    "D",
    "A BCBA plans a multiple-baseline design across three classroom routines for a student's hand-raising. Intervention begins in morning circle while math and dismissal remain in baseline. Hand-raising rises only in morning circle; the untreated routines stay flat. Which conclusion is MOST strongly supported?",
    "A",
    [
      "Staggered change coincident with intervention introduction supports experimental control across baselines.",
      "Any upward drift in one baseline proves the intervention is ineffective in all settings.",
      "Simultaneous change across all three routines is required before claiming a functional relation.",
      "Multiple-baseline logic is invalid unless a full withdrawal phase is embedded in every routine.",
    ],
    [
      "MBD persuasion rests on response change mapping to staggered introduction while untreated baselines remain stable.",
      "Stable untreated baselines with change where treated is evidence for control, not against it.",
      "Simultaneous change across baselines would threaten, not fulfill, MBD logic.",
      "Withdrawal is characteristic of reversal designs; MBD does not require withdrawal in every tier.",
    ],
  ),
  authored(
    912,
    "D",
    "An ABAB reversal for escape-maintained property destruction shows clear suppression in both B phases and recovery toward baseline in both A phases. Midway through the second B phase, the classroom also introduces a new aide who systematically removes demands after disruption. What is the MOST serious threat to interpreting the second B-phase data?",
    "C",
    [
      "Insufficient social validity of the graph scale used in the progress report.",
      "Failure to use a changing-criterion design when rate data are available.",
      "Confounding—the aide's demand removal covaries with the planned intervention, weakening internal validity.",
      "Obligatory use of alternating treatments whenever two adults are present in a room.",
    ],
    [
      "Graph aesthetics and social validity matter clinically but are not the primary validity threat described.",
      "Design choice preference is secondary; the vignette's threat is an uncontrolled concurrent change.",
      "A concurrent uncontrolled contingency (demand removal) confounds attribution of the second B-phase effect to the planned IV.",
      "ATD is not mandatory simply because multiple adults are present; the issue is confounding, not design fashion.",
    ],
  ),
  authored(
    913,
    "D",
    "A clinic compares two prompt-fading strategies within sessions using an alternating-treatments design. Session notes document that therapists often begin a trial with Strategy 1's prompts and then switch mid-trial to Strategy 2 when the learner hesitates. Graphs are later presented as cleanly favoring Strategy 2. What analytic problem is MOST critical?",
    "B",
    [
      "Changing-criterion phases were not labeled on the abscissa.",
      "Multitreatment interference / condition bleed-through prevents clean attribution of differential effects.",
      "Reversal designs cannot evaluate prompting procedures under any circumstances.",
      "Internal validity is automatically assured when two conditions appear on one graph.",
    ],
    [
      "Changing-criterion labeling is irrelevant to an ATD comparison of two prompt strategies.",
      "ATD requires discriminable, non-blended conditions; mid-trial switching produces interference that limits causal claims.",
      "Reversal designs can evaluate many procedures; the vignette's flaw is ATD condition integrity, not reversal prohibition.",
      "Plotting two series does not guarantee internal validity when conditions are contaminated.",
    ],
  ),
  authored(
    914,
    "D",
    "A changing-criterion design targets words read per minute. Criterion steps rise from 40 to 55 to 70, and reinforcement is programmed for meeting each step. Data show the learner's rate tracking each new criterion, but session logs reveal that edible reinforcers were often delivered on a fixed-time schedule unrelated to whether the criterion was met. Which design logic is MOST undermined?",
    "D",
    [
      "Multiple-baseline stagger across untreated peers in the same classroom.",
      "Withdrawal of the entire reading curriculum during baseline probes.",
      "Alternation of two unrelated reading curricula within each minute.",
      "Correspondence between criterion shifts and differential reinforcement for meeting those criteria.",
    ],
    [
      "Peer stagger is an MBD feature, not the core logic threatened in this changing-criterion vignette.",
      "Curriculum withdrawal is not required for changing-criterion persuasion.",
      "Within-minute curriculum alternation is not the design in use here.",
      "Changing-criterion designs persuade when performance covaries with criterion steps that are actually reinforced differentially.",
    ],
  ),
  authored(
    915,
    "D",
    "Baseline for aggression is highly variable and already trending downward before any intervention begins. The team starts DRA anyway and later attributes the continued decrease solely to DRA. Which critique MOST directly addresses internal validity?",
    "A",
    [
      "Pre-intervention downward trend and variability make it difficult to isolate DRA as the cause of further decreases.",
      "Any variable baseline automatically validates intervention effects once a phase line is drawn.",
      "Internal validity concerns apply only to group designs, never to single-case graphs.",
      "Downward baseline trends prove DRA will be ineffective, so the design should be abandoned without analysis.",
    ],
    [
      "Unstable or trending baselines threaten demonstrations of experimental control; continued decrease may reflect ongoing baseline processes.",
      "Phase lines do not create experimental control when baseline already predicts the 'effect.'",
      "Internal validity is central to single-case experimental logic, not exclusive to group designs.",
      "A trending baseline warns against premature causal claims; it does not by itself prove future ineffectiveness of a well-controlled evaluation.",
    ],
  ),
  authored(
    916,
    "D",
    "In a multiple-baseline across settings, the BCBA introduces intervention in Setting 1 and Setting 2 on the same calendar day because staffing is convenient that afternoon. Both settings improve together while Setting 3 remains in baseline. What is the PRIMARY design problem?",
    "B",
    [
      "Using three settings exceeds the maximum tiers allowed in multiple-baseline designs.",
      "Inadequate stagger—concurrent introduction in two settings weakens the demonstration that change tracks independent introductions.",
      "Baseline data in Setting 3 must be deleted once any other setting improves.",
      "Multiple-baseline designs forbid improvement in more than one setting under any timeline.",
    ],
    [
      "Three tiers are common and acceptable; the issue is timing of introductions, not tier count.",
      "MBD control depends on staggered introductions; simultaneous starts in two tiers reduce opportunities to show independent covariation.",
      "Untreated tiers should remain in baseline for comparison; deleting them removes the control series.",
      "Improvement in treated tiers is expected; the flaw is concurrent, not sequential, introduction.",
    ],
  ),
  authored(
    917,
    "D",
    "After a successful intervention phase for elopement, the team briefly returns to baseline conditions (withdrawal) and observes a clear increase in elopement approximating prior baseline levels. Intervention is then reinstated and elopement drops again. What does the withdrawal pattern MOST support?",
    "C",
    [
      "That the behavior is irreversible and therefore unsuitable for any single-case evaluation.",
      "That only a changing-criterion design can demonstrate control for elopement.",
      "Experimental control via reversal—behavior covaries with presence versus absence of the intervention contingency.",
      "That withdrawal phases are unethical in all cases and invalidate the entire dataset.",
    ],
    [
      "Recovery toward baseline indicates reversibility under these conditions, strengthening rather than forbidding analysis.",
      "Changing-criterion is one option among others; reversal recovery specifically supports ABAB-style control.",
      "Classic reversal/withdrawal logic: behavior worsens when the IV is removed and improves when reinstated.",
      "Withdrawal can raise ethical concerns in some cases, but a carefully managed brief withdrawal that shows recovery is analytically informative, not automatically invalidating.",
    ],
  ),
  authored(
    918,
    "D",
    "A BCBA presents an AB design for a toilet-training package: baseline, then intervention, with a clear level change. Stakeholders ask whether the graph alone establishes a functional relation equal to a completed reversal. What is the MOST accurate response?",
    "D",
    [
      "AB designs provide the strongest possible demonstration of experimental control in applied work.",
      "Any level change after a phase line proves causation regardless of threats.",
      "AB designs are never useful for clinical decision-making because they lack all validity.",
      "AB designs can suggest a promising effect but offer weaker control than designs that replicate effects across phases, tiers, or conditions.",
    ],
    [
      "AB is among the weaker demonstrations; stronger control comes from replication strategies (reversal, MB, ATD, etc.).",
      "Phase-line coincidence is necessary but not sufficient; threats to internal validity remain.",
      "AB can still guide cautious clinical decisions while remaining experimentally modest.",
      "Without replication across withdrawals, baselines, or alternating conditions, causal confidence remains limited compared with stronger single-case designs.",
    ],
  ),
  authored(
    919,
    "D",
    "During a reversal evaluation of a DRA plan, a parent begins delivering the same functional reinforcer at home on an inconsistent schedule while clinic phases continue. Clinic graphs still look orderly by phase. Which concern should the BCBA prioritize when interpreting experimental control?",
    "A",
    [
      "Extraexperimental contingency changes (history/confounding) may influence responding and muddy phase comparisons.",
      "Home reinforcement automatically converts the design into a perfect multiple baseline across people.",
      "Orderly clinic graphs guarantee that home contingencies cannot affect internal validity.",
      "Parent-delivered reinforcement is irrelevant because experimental control is judged only by axis labels.",
    ],
    [
      "Uncontrolled concurrent changes outside the planned IV are classic threats to internal validity in single-case work.",
      "Unplanned home delivery is not a structured MB across people; it is a potential confound.",
      "Visual orderliness does not cancel uncontrolled concurrent contingencies that may drive or mask effects.",
      "Axis labels do not establish control; contingency integrity across environments does.",
    ],
  ),
];

export const EXPANDED_H: BDSQuestion[] = [
  authored(
    921,
    "H",
    "Two functionally equivalent interventions reduce a preschooler's attention-maintained screaming in clinic probes. Intervention A yields slightly faster clinic suppression; Intervention B is strongly preferred by teachers and can be run during circle time without extra staffing. Goals are socially important to the family. Which selection priority is MOST defensible?",
    "C",
    [
      "Always choose the clinically fastest option and ignore implementer preference.",
      "Select whichever package uses the most novel technology to impress stakeholders.",
      "Weigh social validity and contextual fit with efficacy—prefer the plan teachers can implement with sustained fidelity in the natural routine.",
      "Defer all selection decisions until a published meta-analysis names a single mandatory protocol.",
    ],
    [
      "Speed alone is insufficient if the faster plan cannot be sustained with integrity in context.",
      "Novelty is not a selection criterion over efficacy, fit, and acceptability.",
      "Domain H selection balances effect with social validity and feasibility so real-world fidelity is achievable.",
      "External evidence informs but does not replace individualized selection under local constraints and stakeholder values.",
    ],
  ),
  authored(
    922,
    "H",
    "Functional analysis indicates a child's aggression is primarily escape-maintained during academic demands. Staff propose a dense attention-delivery package because 'attention fixes most behaviors' on their caseload. What is the MOST defensible next emphasis when selecting the intervention?",
    "A",
    [
      "Match the intervention to function—e.g., teach and reinforce an alternative escape/request response and adjust demand aversiveness—rather than defaulting to mismatched attention.",
      "Implement noncontingent attention exclusively because it is easiest to script on a timer.",
      "Begin with contingent reprimands to suppress aggression before analyzing function fit.",
      "Delay any function-based plan until aggression has been ignored for two weeks across all contexts.",
    ],
    [
      "Function-matching is the primary sieve for intervention selection when FA indicates escape maintenance.",
      "Ease of timing does not justify a mismatched maintaining reinforcer as the primary plan.",
      "Reprimands may worsen escape-maintained behavior and skip function-based positive approaches.",
      "Blanket extinction without a function-matched alternative is neither least-restrictive nor selection-best practice here.",
    ],
  ),
  authored(
    923,
    "H",
    "A reinforcement-based plan for property destruction has been in place for three weeks with incomplete integrity checks. Frustrated staff propose adding contingent basket holds 'to get control quickly.' No medical contraindication review or revised consent has occurred. What is the MOST defensible response?",
    "D",
    [
      "Add restraint immediately because staff frustration itself establishes clinical necessity.",
      "Keep the current plan forever without troubleshooting because escalation is never allowed in ABA.",
      "Replace all reinforcement with continuous physical guidance as a first-line educational strategy.",
      "First verify integrity, dosage, reinforcer efficacy, and EO variables; escalate only with least-restrictive sequencing, documented rationale, and informed consent.",
    ],
    [
      "Staff distress is a signal to support the team, not an automatic justification for restrictive procedures.",
      "Least-restrictive practice allows escalation after analytic troubleshooting—not perpetual inaction.",
      "Continuous physical guidance as a default skips function-based, less restrictive options.",
      "Domain H prioritizes integrity troubleshooting and least-restrictive effective procedures before adding restrictive components with proper consent.",
    ],
  ),
  authored(
    924,
    "H",
    "Weekly graphs show rising independent mands, but the BCBA has not observed sessions in over a month. An RBT reports 'following the plan,' yet peer notes suggest prompts are being skipped. What should the BCBA do FIRST before changing program targets?",
    "B",
    [
      "Raise mastery criteria immediately based solely on the submitted graphs.",
      "Conduct direct observation and score treatment integrity against the written protocol before interpreting outcomes or modifying targets.",
      "Discharge the client because unverified graphs imply services are unnecessary.",
      "Switch to a new curriculum package without assessing whether the current plan was implemented as designed.",
    ],
    [
      "Outcome graphs without integrity data can mislead; raising criteria may punish a fidelity problem.",
      "Treatment integrity observation is required to know whether data reflect the intended independent variable.",
      "Discharge decisions require more than suspicion of data quality; integrity assessment comes first.",
      "Curriculum hopping without integrity assessment confounds interpretation further.",
    ],
  ),
  authored(
    925,
    "H",
    "A 10-year-old receiving clinic-based services consistently pulls away, says 'stop,' and covers their ears when a new tactile prompt hierarchy is introduced, even after rapport routines. Caregivers previously signed broad consent for 'prompting as needed.' What is the MOST appropriate immediate emphasis?",
    "A",
    [
      "Honor ongoing assent signals—pause or modify the procedure, check comfort and alternatives, and obtain intervention-specific informed consent before continuing aversive prompting.",
      "Increase prompt intrusiveness to push through protest because broad consent already covers all prompts.",
      "Ignore vocal protests if acquisition graphs are trending upward.",
      "Continue unchanged and address assent only at annual plan review.",
    ],
    [
      "Assent and dignity require responsive modification; material procedure changes also warrant specific informed consent.",
      "Broad prior consent does not authorize ignoring clear dissent or escalating aversive prompting without review.",
      "Progress data do not override present assent/withdrawal signals during potentially aversive procedures.",
      "Assent is ongoing, not an annual paperwork event only.",
    ],
  ),
  authored(
    926,
    "H",
    "A family's mealtime and greeting customs differ from the clinic's default social-skills targets. The RBT drafts goals that require the child to abandon home cultural practices during family meals 'to look more typical at school.' Caregivers express discomfort. What is the MOST culturally responsive selection/implementation move?",
    "C",
    [
      "Keep the clinic-default goals unchanged and label caregiver concern as noncompliance.",
      "Add punishment for any home-cultural greeting forms observed in clinic.",
      "Collaborate with the family to revise goals and procedures so valued cultural practices are respected while targeting only skills that serve the client's meaningful contexts.",
      "Discharge the family for having values that differ from staff preferences.",
    ],
    [
      "Dismissing caregiver values undermines social validity and partnership.",
      "Punishing cultural practices is neither ethical nor culturally responsive intervention selection.",
      "Cultural responsiveness in Domain H means co-constructing goals that fit family values and functional contexts without imposing unnecessary assimilation.",
      "Value differences call for collaborative revision, not termination.",
    ],
  ),
  authored(
    927,
    "H",
    "After four weeks, a DRA plan for task refusal shows no reliable improvement despite verified integrity above 90% and adequate reinforcer assessments. Demand aversiveness and EO conditions have been reviewed. What is the MOST data-based next modification?",
    "B",
    [
      "Continue the identical plan indefinitely because integrity is high, regardless of outcome trend.",
      "Modify the intervention based on the data—adjust parameters or select a better-supported function-matched alternative and evaluate the change experimentally.",
      "Abandon all data collection and rely on staff anecdotes for the next quarter.",
      "Add an unrelated sensory diet package without linking changes to the functional assessment.",
    ],
    [
      "High integrity with flat outcomes signals the need for analytic change, not perpetual repetition.",
      "Domain H expects data-based modification when a well-implemented plan fails to produce meaningful change.",
      "Anecdotes without ongoing measurement undermine accountable modification.",
      "Unrelated add-ons that ignore function obscure rather than clarify the path to improvement.",
    ],
  ),
  authored(
    928,
    "H",
    "A residential program wants to adopt a restrictive egress-blocking procedure for a client whose elopement is maintained by access to outdoor play. A less restrictive, function-matched plan (functional communication + scheduled outdoor access) has not been tried with integrity. What selection decision is MOST consistent with least-restrictive practice?",
    "D",
    [
      "Install egress blocking first because it is administratively simple for night staff.",
      "Use the most restrictive option available to guarantee zero elopement risk forever.",
      "Skip function-matched alternatives if leadership prefers environmental restriction.",
      "Implement and evaluate the less restrictive function-matched plan with integrity before escalating to more restrictive environmental restriction.",
    ],
    [
      "Administrative ease does not justify skipping less restrictive, function-matched options.",
      "Least-restrictive practice seeks effective control with the least intrusion necessary, not maximal restriction by default.",
      "Leadership preference does not override least-restrictive, function-based sequencing.",
      "Try effective, less restrictive function-matched interventions with integrity before escalating restrictiveness.",
    ],
  ),
  authored(
    929,
    "H",
    "Caregivers rate a toilet-training package as highly acceptable, but probe data in the home show the child still soils when the clinic-trained routine is not prompted. Clinic sessions look mastered. Which implementation emphasis BEST addresses the discrepancy?",
    "A",
    [
      "Program generalization deliberately—train across caregivers, settings, and stimulus variations, and verify performance in the home before treating clinic mastery as sufficient.",
      "Declare success based on clinic graphs alone and end caregiver coaching.",
      "Increase clinic session length only, without ever probing the home routine.",
      "Assume social validity ratings guarantee transfer to untrained environments.",
    ],
    [
      "Social validity of the package does not replace programmed generalization and natural-environment verification.",
      "Clinic mastery without home performance is incomplete for a home-critical skill.",
      "More clinic time without home programming is a classic 'train and hope' error.",
      "Acceptability ratings matter but do not ensure stimulus control transfers to home.",
    ],
  ),
];

export const EXPANDED_I: BDSQuestion[] = [
  authored(
    931,
    "I",
    "An RBT consistently errs on stimulus-control transfer steps during DTT despite reading the protocol aloud. The supervisor has so far only emailed written reminders. What supervision strategy is MOST evidence-aligned for remediating the skill?",
    "B",
    [
      "Continue email-only feedback until graphs improve on their own.",
      "Use Behavioral Skills Training—instructions, modeling, rehearsal, and performance-based feedback—against an observable fidelity checklist, then re-probe in vivo.",
      "Reassign the case permanently without attempting structured skill building.",
      "Deliver only global praise to protect the RBT's confidence, omitting specific performance criteria.",
    ],
    [
      "Passive written reminders rarely remediate complex implementation skills.",
      "BST with performance criteria is the competency-based standard for teaching supervisee skills.",
      "Reassignment without training abandons supervisory responsibility for skill development.",
      "Nonspecific praise does not shape protocol-accurate performance.",
    ],
  ),
  authored(
    932,
    "I",
    "A clinic's training program advances trainees to independent session leadership after a single quiz score of 80%, with no live demonstration requirement. Several trainees later show critical fidelity failures. Which training approach should the supervisor insist on instead?",
    "D",
    [
      "Knowledge quizzes alone as sufficient evidence of readiness for independent practice.",
      "Time-in-seat hour totals without observing performance quality.",
      "Peer popularity ratings as the primary competency gate.",
      "Competency-based training—trainees demonstrate each critical skill to mastery criteria under observation before independent performance is authorized.",
    ],
    [
      "Quizzes assess verbal knowledge, not fluent accurate implementation under session conditions.",
      "Hours without verified performance do not establish competence.",
      "Social popularity is unrelated to protocol fidelity.",
      "Competency-based gates require observed mastery of critical skills before independent practice.",
    ],
  ),
  authored(
    933,
    "I",
    "A supervisor notices that corrective feedback to one trainee is rare, delayed, and inconsistently paired with any improvement in the trainee's correct prompt timing, while correct performances also go unacknowledged. Using PIC/NIC analysis, which change is MOST likely to strengthen desired supervisee performance?",
    "A",
    [
      "Provide positive, immediate, and certain consequences for correct performances, and ensure corrective feedback is timely and consistent rather than rare or unpredictable.",
      "Make all feedback negative, uncertain, and delayed to 'keep trainees humble.'",
      "Deliver feedback only in annual reviews so consequences remain distant from performance.",
      "Avoid observing sessions so consequences never contact supervisee behavior.",
    ],
    [
      "PIC (positive, immediate, certain) consequences for correct performance—and reliable corrective contact—are more effective than rare/uncertain/delayed feedback patterns.",
      "NIC-heavy climates suppress reporting and fail to differentially reinforce correct performance.",
      "Annual-only feedback maximizes delay and weakens contingency contact with session behavior.",
      "Without observation, performance consequences cannot systematically shape skill.",
    ],
  ),
  authored(
    934,
    "I",
    "An RBT works 40 hours in a two-week period on a caseload requiring ongoing RBT supervision. Documentation shows only 30 minutes of qualifying supervision contacts in that period, with no observation of service delivery. What supervisory correction is MOST aligned with the RBT 5% supervision standard?",
    "C",
    [
      "Treat quiz completion as a substitute for the 5% supervision contact requirement.",
      "Allow the RBT to self-attest that informal hallway chats met the standard.",
      "Increase qualifying supervision to at least 5% of the hours worked in the period, including the required observational component, and document contacts accurately.",
      "Waive supervision for experienced RBTs when caseloads are busy.",
    ],
    [
      "Didactic quizzes do not replace ongoing supervision percentage and observation requirements.",
      "Informal undocumented chats typically fail to meet structured supervision standards.",
      "RBT supervision requires meeting the percentage standard with appropriate observation and documentation for the hours worked.",
      "Experience does not eliminate the ongoing 5% supervision obligation.",
    ],
  ),
  authored(
    935,
    "I",
    "A fieldwork trainee asks the BCBA to sign a monthly experience form that includes 15 hours labeled as unrestricted activities the BCBA never discussed, observed, or assigned. The trainee says the site 'always estimates those hours.' What is the MOST responsible supervisor action?",
    "B",
    [
      "Sign the form to maintain site relationships and correct totals later if audited.",
      "Refuse to attest to hours not actually supervised or verified; document only accurate activities consistent with fieldwork requirements.",
      "Sign now and ask the trainee to invent narrative notes that match the inflated hours.",
      "Transfer signing authority to an uninvolved administrator who never met the trainee.",
    ],
    [
      "Signing inaccurate hours is a documentation integrity violation, not a relationship courtesy.",
      "Supervisors may attest only to fieldwork that meets requirements and that they can honestly verify.",
      "Fabricating notes compounds the misrepresentation.",
      "Attestation responsibility cannot be offloaded to someone without supervisory knowledge of the activities.",
    ],
  ),
  authored(
    936,
    "I",
    "A BCBA supervising an RBT begins a romantic relationship with that RBT while still evaluating the RBT's performance, assigning cases, and signing documentation. The BCBA believes feelings will not affect judgment. What is the MOST appropriate ethical supervision response?",
    "A",
    [
      "Recognize a multiple relationship that risks impaired objectivity; discontinue the dual role arrangement through appropriate transfer of supervision and document the transition.",
      "Continue both roles unchanged because intent to remain unbiased is sufficient protection.",
      "Increase evaluative power over the RBT to 'test' whether the relationship affects performance ratings.",
      "Keep the romance private and withhold disclosure from the organization while retaining supervisory authority.",
    ],
    [
      "Romantic involvement with a current supervisee is a classic multiple relationship requiring role remediation to protect objectivity and the supervisee.",
      "Good intentions do not neutralize structural conflicts in evaluative supervision relationships.",
      "Intensifying power differentials worsens, rather than solves, the conflict.",
      "Concealment preserves the conflict and adds transparency failures.",
    ],
  ),
  authored(
    937,
    "I",
    "A clinic director tells a BCBA to 'just have the RBT write the behavior plan and pick restrictive procedures' for a complex new case while the BCBA remains nominally supervisor of record. The RBT has not demonstrated competence in assessment or plan design. What is the MOST appropriate supervisory stance?",
    "D",
    [
      "Delegate plan authorship and restrictive-procedure selection wholesale because RBTs bill at a lower rate.",
      "Allow the RBT to practice beyond competence if the BCBA promises to glance at the plan later.",
      "Accept the directive without pushback to avoid workplace conflict.",
      "Decline unsafe delegation—retain responsibility for assessment and plan decisions within BCBA scope, assign only tasks within the RBT's demonstrated competence, and document concerns.",
    ],
    [
      "Cost savings do not justify delegating activities outside RBT scope and competence.",
      "Post-hoc glancing does not constitute adequate supervisory control of restricted activities.",
      "Avoiding conflict does not excuse supervisory abandonment of competent oversight.",
      "Supervisors must delegate only within competence/scope and remain accountable for restricted decision-making.",
    ],
  ),
  authored(
    938,
    "I",
    "A BCBA is resigning from a clinic in three weeks. Several trainees still need observation hours and performance feedback to complete fieldwork requirements tied to that supervisor. The clinic has not yet named a receiving supervisor. What termination-of-supervision practice is MOST responsible?",
    "C",
    [
      "Stop all contact immediately and leave trainees to find coverage without notice or transfer plan.",
      "Sign remaining anticipated hours in advance for the next two months to 'clear the books.'",
      "Provide timely notice, coordinate an orderly transfer to a qualified supervisor, continue required contacts through the transition, and document the handoff of responsibilities and pending competencies.",
      "Tell trainees to list a different BCBA's name on forms without that BCBA's agreement.",
    ],
    [
      "Abrupt abandonment harms trainees and clients and violates responsible termination expectations.",
      "Prospective attestation of uncompleted supervision is dishonest documentation.",
      "Responsible termination includes notice, continuity planning, ongoing duties through transition, and clear documentation of the supervisory handoff.",
      "Listing another BCBA without agreement falsifies supervision relationships.",
    ],
  ),
];
